- src/pymor/algorithms/pod.py
This code path was obviously ignored in some updates to the code
> [algorithms.pod] fix case of all pod values below tolerance

- src/pymor/core/interfaces.py
- src/pymortests/core/interface.py
> [core] move 'with_' from BasicInterface to ImmutableInterface

- src/pymor/playground/discretizers/numpylistvectorarray.py
- src/pymor/playground/operators/numpy.py
- src/pymordemos/thermalblock.py
This pull requests adds `NumpyListVectorArrayMatrixOperator` and `convert_to_numpy_list_vector_array` from the pymor-paper branch to the playground. Moreover,
an `--list-vector-array` option is added to the thermalblock demo, which allows to compare the performance of `NumpyVectorArray` and `ListVectorArrays` of `NumpyVectors`.
> Add ListVectorArray based NumpyMatrixOperator

- .travis.yml
- debian/print-deps.pl
This is in reference to #149  
AFAICT we're left with test failures because PySide is missing and it's unclear to me if optional fenics tests actually ran. See also #167 where I definitely missed them not running. 
Ideas on how to proceed welcome.
> Travis platform migration

- src/pymor/operators/basic.py
- src/pymor/operators/constructions.py
- src/pymor/operators/interfaces.py
- src/pymor/operators/numpy.py
- src/pymortests/operators.py
This addresses #133.
@pmli, @ftalbrecht, please take a look if you are happy with the interface. Haven't done any testing yet ...
> [operators] add 'apply_inverse_adjoint' to OperatorInterface

- src/pymor/operators/basic.py
- src/pymor/operators/constructions.py
- src/pymor/operators/ei.py
- src/pymor/operators/mpi.py
- src/pymor/vectorarrays/block.py
- src/pymor/vectorarrays/fenics.py
- src/pymor/vectorarrays/interfaces.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/mpi.py
- src/pymor/vectorarrays/numpy.py
- src/pymordemos/minimal_cpp_demo/wrapper.py
This addresses #55.
VectorArray tests run fine. However, I have not done any performance testing yet.
> Implement copy-on-write semantics for VectorArrayInterface.copy

- src/pymor/core/logger.py
@ftalbrecht, you might have an opinion ...
> [core.logger] add 'INFO2' and 'INFO3' log levels

- .travis.yml
- dependencies.py
- setup.py
This now works on travis, which separately tests pip install, and my local box.
> Remove dependency check

- .coveragerc
- setup.cfg
- src/pymor/algorithms/image.py
- src/pymor/core/exceptions.py
- src/pymor/reductors/basic.py
- src/pymor/reductors/residual.py
@andreasbuhr, @michaellaier, this might be of interest to you.
> [algorithms] add estimate_image, estimate_image_hierarchical and use them

- AUTHORS.md
- src/pymor/algorithms/image.py
- src/pymor/basic.py
- src/pymor/discretizers/parabolic.py
- src/pymor/functions/basic.py
- src/pymor/reductors/parabolic.py
- src/pymor/reductors/residual.py
- src/pymordemos/parabolic.py
- src/pymordemos/parabolic_mor.py
- src/pymortests/demos.py
This is largely based on work by Michael Laier, see #243.
> add reductor for parabolic equations

- src/pymor/operators/basic.py
- src/pymor/operators/constructions.py
- src/pymor/operators/interfaces.py
- src/pymor/operators/mpi.py
- src/pymortests/operators.py
> This removes the product argument from apply2

- src/pymor/analyticalproblems/burgers.py
- src/pymor/discretizations/basic.py
- src/pymor/discretizations/mpi.py
- src/pymor/functions/basic.py
- src/pymor/operators/basic.py
- src/pymor/operators/block.py
- src/pymor/operators/cg.py
- src/pymor/operators/constructions.py
- src/pymor/operators/ei.py
- src/pymor/operators/fv.py
- src/pymor/operators/mpi.py
- src/pymor/operators/numpy.py
- src/pymor/parameters/base.py
- src/pymor/parameters/functionals.py
> [parameters] remove global to local name mapping feature

- src/pymor/algorithms/genericsolvers.py
- src/pymor/operators/numpy.py
> Add finiteness checks to linear solvers

- src/pymor/discretizations/basic.py
Special operators are now always specified as individual `__init__` arguments, not as part of the `operators` dict. This has the following benefits:
- Special operators can be directly referred to in `__init__` without prior calling of `DiscretizationBase.__init__`. Thus, the `self.` can go away.
- It is easily possible to choose defaults for certain not-specified special operators based on other special operators (only used in sys-mor branch so far).
Moreover, we now call `build_parameter_type` already in `DiscretizationBase.__init__`.
> [discretizations] further simplify usage of DiscretizationBase

- .travis.script.bash
- src/pymor/__init__.py
So I guess everyone is annoyed by pyMOR's obtrusive import message. This commit will put this to an end ...
> Do not print version string on import

- src/pymor/__init__.py
- src/pymor/core/cache.py
- src/pymor/core/config.py
- src/pymor/core/defaults.py
- src/pymor/core/interfaces.py
- src/pymor/core/pickle.py
- src/pymor/gui/fenics.py
- src/pymor/gui/gl.py
- src/pymor/gui/matplotlib.py
- src/pymor/gui/qt.py
- src/pymor/operators/fenics.py
- src/pymor/operators/numpy.py
- src/pymor/parallel/ipython.py
- src/pymor/tools/mpi.py
- src/pymor/tools/vtkio.py
- src/pymor/vectorarrays/fenics.py
- src/pymor/vectorarrays/interfaces.py
- src/pymortests/core/config.py
- src/pymortests/demos.py
- src/pymortests/fixtures/vectorarray.py
- src/pymortests/pickling.py
This addresses #317. @renemilk, @ftalbrecht, please let me know what you think ..
> Introduce pymor.core.config module

- src/pymor/algorithms/genericsolvers.py
- src/pymor/operators/basic.py
- src/pymor/operators/block.py
- src/pymor/operators/constructions.py
- src/pymor/operators/fenics.py
- src/pymor/operators/interfaces.py
- src/pymor/operators/mpi.py
- src/pymor/operators/numpy.py
- src/pymor/playground/operators/numpy.py
- src/pymortests/block.py
- src/pymortests/fixtures/operator.py
- src/pymortests/operators.py
- src/pymortests/solver.py
> Replace apply_adjoint by apply_transpose

- src/pymor/grids/oned.py
- src/pymor/grids/rect.py
- src/pymor/grids/tria.py
- src/pymor/grids/unstructured.py
- src/pymortests/fixtures/grid.py
- src/pymortests/grid.py
> Fix grid visualize methods

- src/pymor/operators/interfaces.py
- src/pymor/vectorarrays/interfaces.py
- src/pymortests/operators.py
- src/pymortests/vectorarray.py
> Implement more arithmetic operations on VectorArrays and Operators

- src/pymor/operators/constructions.py
- src/pymortests/operators.py
> add InverseOperator and InverseTransposeOperator

- src/pymor/algorithms/gram_schmidt.py
- src/pymor/basic.py
- src/pymortests/algorithms/gram_schmidt.py
- src/pymortests/la.py
As in #334, but for the master branch,
> Biorthogonal Gram Schmidt

- src/pymor/algorithms/sylvester.py
- src/pymor/operators/numpy.py
- src/pymor/reductors/bt.py
- src/pymor/reductors/lti.py
- src/pymorexamples/heat.ipynb
- src/pymortests/sylvester.py
Added:
- biorthogonal Gram-Schmidt process in `algorithms.gram_schmidt`,
- sparse-dense Sylvester equation solver in `algorithms.sylvester`,
- TSIA (Two Sided Iteration Algorithm) in `reductors.lti`,
- yet another complex numbers bug fix.
> [sys-mor] Biorthogonalization, Sylvester equations, TSIA

- docs/source/getting_started.rst
- src/pymor/algorithms/adaptivegreedy.py
- src/pymor/algorithms/ei.py
- src/pymor/algorithms/error.py
- src/pymor/algorithms/greedy.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/discretizations/basic.py
- src/pymor/discretizers/cg.py
- src/pymor/discretizers/disk.py
- src/pymor/discretizers/fv.py
- src/pymor/gui/visualizers.py
- src/pymor/reductors/basic.py
- src/pymor/reductors/coercive.py
- src/pymor/reductors/parabolic.py
- src/pymordemos/analyze_pickle.py
- src/pymordemos/burgers.py
- src/pymordemos/burgers_ei.py
- src/pymordemos/elliptic.py
- src/pymordemos/elliptic2.py
- src/pymordemos/elliptic_oned.py
- src/pymordemos/elliptic_unstructured.py
- src/pymordemos/parabolic.py
- src/pymordemos/parabolic_mor.py
- src/pymordemos/thermalblock.py
- src/pymordemos/thermalblock_adaptive.py
- src/pymordemos/thermalblock_gui.py
- src/pymordemos/thermalblock_simple.py
- src/pymortests/gui.py
> discretization -> d, rb_discretization -> rd, ei_discretization -> ei_d

- src/pymor/algorithms/projection.py
- src/pymor/discretizers/fv.py
- src/pymor/operators/block.py
- src/pymor/operators/constructions.py
- src/pymor/operators/ei.py
- src/pymortests/fixtures/operator.py
- src/pymortests/to_matrix.py
This is more consistent with the rest of pyMOR.
> [ZeroOperator] replace source and range argument

- src/pymor/bindings/scipy.py
> [scipy] convert to CSC before splu call

- src/pymor/operators/cg.py
I added missing robin_data parameters, which should be inherited in operators/cg.
> added missing robin_data parameters in operators.cg

- src/pymortests/operators.py
> Extend test_assemble

- src/pymor/operators/numpy.py
> [NumpyMatrixOperator] make numpy arrays readonly

- src/pymor/core/defaults.py
- src/pymor/operators/numpy.py
- src/pymor/reductors/bt.py
> [py3] remove qualname argument from defaults decorator

- docs/source/bibliography.rst
- docs/source/index.rst
- src/pymor/algorithms/adaptivegreedy.py
- src/pymor/algorithms/lyapunov.py
- src/pymor/reductors/bt.py
- src/pymor/reductors/coercive.py
- src/pymor/reductors/h2.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/parabolic.py
- src/pymor/reductors/sobt.py
- src/pymor/reductors/sor_irka.py
> [docs] move all references to bibliography.rst

- src/pymor/algorithms/arnoldi.py
- src/pymor/algorithms/lyapunov.py
- src/pymor/algorithms/sylvester.py
- src/pymor/bindings/pymess.py
- src/pymor/discretizations/iosys.py
- src/pymor/operators/block.py
- src/pymor/reductors/interpolation.py
> Replace LincombOperator with + and *

- src/pymor/basic.py
> Adding sys-mor stuff to pymor.basic

- src/pymor/discretizations/iosys.py
- src/pymor/operators/block.py
- src/pymor/reductors/bt.py
- src/pymor/reductors/h2.py
> [discretizations.iosys] remove _is_like_zero_operator / _is_like_identity_operator

- notebooks/heat.ipynb
- src/pymor/discretizations/iosys.py
> use pyMOR discretization toolkit in heat.ipynb

- src/pymor/algorithms/projection.py
- src/pymor/reductors/basic.py
- src/pymor/reductors/bt.py
- src/pymor/reductors/coercive.py
- src/pymor/reductors/h2.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/parabolic.py
- src/pymor/reductors/sobt.py
- src/pymor/reductors/sor_irka.py
- src/pymordemos/parabolic_mor.py
> Align interfaces of GenericRBReductor and GenericPGReductor

- src/pymor/discretizations/iosys.py
> Add size threshold for warning about conversion to NumPy arrays

- notebooks/heat.ipynb
- notebooks/string.ipynb
- src/pymor/discretizations/iosys.py
- src/pymordemos/heat.py
- src/pymordemos/string_equation.py
> Check if slycot is available before computing Hinf norm

- src/pymor/bindings/slycot.py
> Changing matrix equation ill-conditioning warning tolerances

- docs/source/pymordocstring.py
- graveyard/disk.py
- src/pymor/algorithms/adaptivegreedy.py
- src/pymor/algorithms/image.py
- src/pymor/algorithms/projection.py
- src/pymor/algorithms/rules.py
- src/pymor/algorithms/to_matrix.py
- src/pymor/basic.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/bindings/pyamg.py
- src/pymor/bindings/scipy.py
- src/pymor/core/cache.py
- src/pymor/core/config.py
- src/pymor/core/defaults.py
- src/pymor/core/interfaces.py
- src/pymor/core/pickle.py
- src/pymor/discretizations/basic.py
- src/pymor/discretizations/interfaces.py
- src/pymor/discretizers/cg.py
- src/pymor/domaindiscretizers/gmsh.py
- src/pymor/functions/bitmap.py
- src/pymor/grids/oned.py
- src/pymor/grids/referenceelements.py
- src/pymor/gui/gl.py
- src/pymor/gui/qt.py
- src/pymor/operators/basic.py
- src/pymor/operators/cg.py
- src/pymor/operators/ei.py
This includes the fixes from #444 without the ci integration.
> Some flake8 fixes

- .ci/travis/deploy.bash
- docs/source/release_notes.rst
- docs/source/substitutions.py
> Release notes for pyMOR 0.5

- src/pymor/grids/_unstructured.pyx
- src/pymor/tools/inplace.pyx
- src/pymor/tools/relations.pyx
As suggested in official docs https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#globally
> explicitly set cython language_level in each file

- README.md
> [README] add PyPI badges

- notebooks/heat.ipynb
- notebooks/string.ipynb
- src/pymordemos/delay.py
- src/pymordemos/heat.py
- src/pymordemos/string_equation.py
Changes from #589 unrelated to arithmetic operators.
> Notebooks and demos improvements

- src/pymordemos/thermalblock_gui.py
backport of #593 onto the release branch
> Fix thermalblock_gui demo not starting

- .ci/docker/install_checks/debian_buster/Dockerfile
- .ci/docker/install_checks/debian_stretch/Dockerfile
- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
- setup.py
> add minimal python requirement in setup.py

- .ci/azure/pipeline-osx.yml
- .ci/azure/pipeline-win.yml
- dependencies.py
- requirements.txt
- src/pymor/core/cache.py
- src/pymortests/cache.py
> Replace sqlite caching

- src/pymor/algorithms/sylvester.py
This avoids the bug in #624 and somewhat simplifies the implementation.
> Remove as_source/range_array in solve_sylv_schur

- src/pymor/algorithms/ei.py
- src/pymor/operators/ei.py
- src/pymor/operators/numpy.py
> Replace numpy.linalg.solve by scipy.linalg.solve

- src/pymor/reductors/h2.py
- src/pymor/reductors/sor_irka.py
Related to https://github.com/pymor/pymor/pull/592#issuecomment-467588737
> Logger change for IRKA and related methods

- notebooks/delay.ipynb
- src/pymor/models/iosys.py
> Arithmetic operations for LinearDelayModel

- src/pymor/vectorarrays/numpy.py
> [NumpyVectorSpace] fix issue 662

- AUTHORS.md
- src/pymor/vectorarrays/interfaces.py
> Fixed complex norms

- dependencies.py
- requirements-optional.txt
- src/pymortests/demos.py
> xfail when GMSH setup not usable

- .ci/gitlab/ci.yml
- .ci/gitlab/script.bash
- .ci/gitlab/template.ci.py
- .ci/gitlab/test_docs.bash
- dependencies.py
- requirements-ci.txt
This should ensure that mybinder builds work.
Merge when ready
> Add a repo2docker step to CI

- src/pymor/parameters/functionals.py
- src/pymor/parameters/interfaces.py
> [parameters.functionals] implement __neg__

- src/pymor/models/iosys.py
- isolates the change from #652
> [models.iosys] change H/dH to tf/dtf in TransferFunction

- .ci/gitlab/script.bash
- Makefile
- setup.cfg
> Fix issue 685

- .binder/docker-compose.yml
- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
- Makefile
this rebases all docker commands on the compose config
and adds a makefile target to start a jupyter server
merge when ready
> Makefile improvements

- src/pymor/vectorarrays/interfaces.py
This makes it as in `NumpyVectorArray` and `BlockVectorArray`.
> [vectorarrays.interfaces] make real and imag properties

- src/pymor/domaindescriptions/basic.py
- src/pymor/domaindescriptions/polygonal.py
> Remove some more obsolete __repr__ methods

- src/pymor/algorithms/lyapunov.py
> [algorithms.lyapunov] use numpy broadcasting in _chol

- notebooks/parametric_heat.ipynb
- src/pymor/basic.py
- src/pymor/reductors/h2.py
> Fix parametric one-sided IRKA reductor

- src/pymor/models/iosys.py
This makes it more similar to `algorithms.lyapunov`.
> [models.iosys] use defaults instead of constant

- notebooks/parametric_string.ipynb
- src/pymor/models/iosys.py
> Fix the number of second-order singular values

- src/pymor/reductors/sobt.py
> [reductors.sobt] use lapack_driver='gesvd' in scipy.linalg.svd

- .ci/travis/script.bash
- dependencies.py
- requirements-optional.txt
- requirements-travis.txt
- src/pymor/operators/constructions.py
- src/pymor/parameters/functionals.py
- src/pymortests/operators.py
> Fix 643 in 0.5.x branch

- src/pymor/models/iosys.py
Leftover from #729.
merge when ready
> [models.iosys] fix mag_plot figure title

- src/pymor/gui/visualizers.py
> [visualizers] fix backend assignment

- .ci/gitlab/ci.yml
- .ci/gitlab/script.bash
- .ci/gitlab/template.ci.py
- dependencies.py
- notebooks/test.py
- requirements-ci.txt
- requirements-optional.txt
Note: https://github.com/pymor/pymor/compare/ci_updates?expand=1#diff-89b5c0d597ede8446ca29897b1a690e3R5
This PR will not tackle parameterization.
> Start testing notebooks

- .ci/gitlab/ci.yml
- .ci/gitlab/script.bash
- .ci/gitlab/template.ci.py
- dependencies.py
- requirements-ci.txt
- setup.cfg
Results are uploaded in a csv file like this: https://pymor.zivgitlabpages.uni-muenster.de/-/pymor/-/jobs/173239/artifacts/memory_usage.txt
> [ci] add memprof plugin for pytest

- .ci/docker/install_checks/debian_stretch/Dockerfile
> [ci] fix stretch install check

- notebooks/parametric_synthetic.ipynb
> [notebooks.parametric_synthetic] simplify parametric operator

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
> [ci] deploy hotfix for repo2docker issue #755

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
> Exclude branches starting with staging/ from running CI

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
- .ci/gitlab/trigger_binder.py
> Trigger mybinder image builds from CI

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
> CI: Fix binder step dependency install

- src/pymor/__init__.py
- src/pymor/tools/mpi.py
> Support setting THREAD_LEVEL for MPI init

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
> [ci] retry coverage submit

- src/pymor/models/iosys.py
> Type of w in freq_resp and mag_plot

- src/pymor/models/basic.py
> improve 'products' docstring of (In)StationaryModel

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
for some reason some runners were defaulting to a different image
for this step than others
> [ci] fix trigger binder step for all runners

- src/pymor/algorithms/ei.py
- add option to disable the POD in order to directly pass the interpolation basis
- small performance tweak
> Minor improvements to deim algorithm

- src/pymor/grids/oned.py
> [grids.oned] fix __repr__, fixes #798

- src/pymor/bindings/fenics.py
> Handle solver_options in FenicsMatrixOperator._assemble_lincomb

- src/pymor/algorithms/image.py
> [algorithms.image] fix CollectVectorRangeRules for ConcatenationOperator

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
- src/pymor/__init__.py
> Reenable mpi tests

- README.md
> Update Readme for 2019.2 release

- README.md
Same change as in #842 for the master branch.
> Change dependencies link in README (master)

- src/pymor/bindings/fenics.py
and remove an unneeded copy in `to_numpy`.
> Implement FenicsVectorSpace.from_numpy

- README.md
- dependencies.py
Closes #677.
It also edits the part about installing additional packages (mentions additionally that pymess also has dense matrix equation solvers).
> Recommend installing pymess from source

- README.md
Same as #901, but for gh-pages branch.
> Recommend installing pymess from source (gh-pages)

- src/pymor/vectorarrays/numpy.py
> Add a warning to not instantiate NumpyVectorArray directly.

- src/pymor/parameters/base.py
@HenKlei, as discussed earlier. @TiKeil, you may want to take a look as well.
> Add Parameters.dim and Mu.to_numpy

- .ci/gitlab/common_test_setup.bash
- .ci/gitlab/test_docs.bash
- .ci/gitlab/test_pip_installed.bash
- .ci/installed_pytest.ini
- conftest.py
- src/pymor/algorithms/pod.py
- src/pymor/parameters/base.py
- src/pymortests/algorithms/pod.py
- src/pymortests/parameters.py
- src/pymortests/vectorarray.py
This supersedes #976 entirely and includes the current state of #973 (since after the CI fix I ran into a new failure in the POD test, which gets resolved with that).
> Ci hotfix+fix 961

- .mailmap
Similar to #733.
Running `git shortlog -nse` before:
```
3284  Stephan Rave <stephanrave@uni-muenster.de>
1280  René Fritze <rene.fritze@uni-muenster.de>
713  Petar Mlinarić <mlinaric@mpi-magdeburg.mpg.de>
155  Felix Schindler <felix.schindler@wwu.de>
78  Stephan Rave <mail@stephanrave.de>
73  Tim Keil <tim.keil@wwu.de>
39  Linus Balicki <linus.balicki@ovgu.de>
36  Michael Laier <m_laie01@uni-muenster.de>
29  Andreas Buhr <andreas@andreasbuhr.de>
14  Hendrik Kleikamp <hendrik.kleikamp@uni-muenster.de>
12  Michael Schaefer <michael.schaefer@uni-muenster.de>
9  Christian Himpe <himpe@mpi-magdeburg.mpg.de>
9  Dennis Eickhorn <d.eickhorn@uni-muenster.de>
5  Falk Meyer <falk.meyer@uni-muenster.de>
2  Julia Brunken <julia.brunken@uni-muenster.de>
1  Hendrik Kleikamp <h_klei18@uni-muenster.de>
1 …
```
> Update mailmap before 2020.1 release

- README.md
> Mention PDE solvers versions used to test the bindings in README.md

- docs/source/pymor_defaults.py
- notebooks/elliptic_oned.ipynb
- notebooks/heat.ipynb
- notebooks/parametric_heat.ipynb
- src/pymor/discretizers/builtin/gui/jupyter/__init__.py
- src/pymor/discretizers/builtin/gui/jupyter/matplotlib.py
- src/pymor/discretizers/builtin/gui/jupyter/patch.py
- src/pymor/discretizers/builtin/gui/matplotlib.py
- src/pymor/discretizers/builtin/gui/visualizers.py
This PR combines #1009 and #966 and fixes the remaining phantom draw issue. 
It also sets the backend for documentation vis to `MPL`.
> MPL visualisation: fix 1D + animate series

- docs/source/_static/pymor.css
- docs/source/_templates/layout.html
- docs/source/conf.py
- docs/source/tutorial_mor_with_anns.rst
Docs are already at: https://docs.pymor.org/sphinx-theme/generated/pymor.algorithms.html
Now waiting for rebuild after rebase on master
> New Sphinx theme

- .github/workflows/link_check.yml
- README.md
- docs/RELEASE_CHECKLIST.md
Thanks to @HenKlei for noticing
> Fixes some out-of-date links in README

- src/pymor/bindings/fenics.py
- src/pymor/discretizers/builtin/gui/visualizers.py
> Make visualizers immutable

- .binder/docker-compose.yml
- Makefile
- README.md
just set PYMOR_SUDO=1 in your env
please test @TiKeil
> [make] facilitate using compose with sudo

- README.md
> [readme] feature the new logo

- docs/source/_static/pymor.css
- docs/source/conf.py
Backport of #1081 to 2020.1.x.
> Backport: Add logo to docs

- _layouts/default.html
> Add link to pyMOR school to the webpage

- src/pymor/discretizers/builtin/cg.py
> Backport: Fix AdvectionOperatorP1

- docs/source/tutorial_mor_with_anns.rst
> Added possibility to download the code in Tutorial for ANNs

- docs/source/tutorial_mor_with_anns.rst
- src/pymor/algorithms/adaptivegreedy.py
- src/pymor/algorithms/error.py
- src/pymor/algorithms/greedy.py
- src/pymor/core/logger.py
- src/pymor/discretizers/builtin/domaindiscretizers/gmsh.py
- src/pymor/discretizers/builtin/grids/gmsh.py
- src/pymor/tools/timing.py
- src/pymordemos/analyze_pickle.py
- src/pymordemos/burgers.py
- src/pymordemos/burgers_ei.py
- src/pymordemos/fenics_nonlinear.py
- src/pymordemos/hapod.py
- src/pymordemos/neural_networks.py
- src/pymordemos/neural_networks_fenics.py
- src/pymordemos/thermalblock.py
- src/pymordemos/thermalblock_gui.py
> Replace time.time with time.perf_counter

- src/pymor/algorithms/samdp.py
Fixes issue which allowed exact eigenvalue to be passed to the `_twosided_rqi` function.
> [algorithms.samdp] check for complex eigenvalue before RQI

- src/pymor/analyticalproblems/thermalblock.py
or did I understand this wrong, @sdrave?
> [analyticalproblems] fix Thermalblock docs

- src/pymor/discretizers/builtin/gui/jupyter/matplotlib.py
- src/pymor/discretizers/builtin/gui/matplotlib.py
this fixes the issue mentioned in #1123 for me, but I did not test it widely
> [discretizers.builtin] allow to set the aspect ratio in matplotlib plots

- src/pymor/discretizers/builtin/gui/gl.py
- src/pymordemos/parabolic_mor.py
- src/pymordemos/thermalblock.py
- src/pymordemos/thermalblock_adaptive.py
- src/pymordemos/thermalblock_simple.py
this is already based on #1176 or else CI would not go forward atm.
> Fix OGL regression + remove broken show usage

- src/pymor/algorithms/svd_va.py
- src/pymortests/algorithms/svd_va.py
> Never return more modes then VectorArray dimension in method_of_snapshots

- README.md
- docs/RELEASE_CHECKLIST.md
Applies the README fixes from #1187 to the master branch.
> Fix docs link [master]

- docs/source/conf.py
- docs/source/gen_apidoc.py
- src/pymor/core/base.py
Thanks to @HenKlei , we already found a way how to include documented private functions. This solves #1184 and finishes the problem discussed in #1155
> [docs.sphinx] also add :private-members:

- .binder/docker-compose.yml
> fix issue 1193

- src/pymor/discretizers/builtin/gui/qt.py
> Added missing parameters for Matplotlib1DWidget

- docs/source/release_notes/2020.2.rst
Something went wrong with #1216....
> [docs] edit release notes

- .github/workflows/flake8.yml
- .github/workflows/label.yml
I just need to check if github prevents the new fixed action to work from the fork only
> fix flake8 check for forks

- dependencies.py
- requirements-optional.txt
- src/pymortests/lyapunov.py
The urls for the wheels will have to be changed back to 
their final location before this PR can be merged
> update pymess wheels and re-enable tests

- .github/workflows/git_checks.yml
- .github/workflows/process_linter_results.yml
This seems to be exactly what discussed during the developer meeting.
> Use annotations instead of review for linter

- src/pymor/algorithms/samdp.py
- src/pymortests/algorithms/samdp.py
This PR changes the `which` argument of `samdp` such that it is different from the `which` argument in `eigs`.
> [algorithms.samdp] rename which argument

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
- .github/workflows/git_checks.yml
Aside from making the GitLab CI template more readable,
this PR also prevents me from comitting unresolved merge
conflicts unnoticed ever again.
> Some CI update

- AUTHORS.md
- src/pymor/basic.py
- src/pymor/reductors/mt.py
- src/pymordemos/heat.py
- src/pymordemos/parametric_heat.py
- src/pymordemos/parametric_string.py
- src/pymordemos/string_equation.py
This PR adds a new reductor who uses modal truncation to reduce the given model. A small example on how to use the reductor is given in the demo for the heat equation.
> Modal truncation

- AUTHORS.md
- CONTRIBUTING.md
- README.md
- docs/RELEASE_CHECKLIST.md
- logo/README.md
I started using `markdownlint`, so I fixed some issues it found. The only remaining issues are that `README.md` is not starting with a title and HTML tags in `logo/README.md`, which I guess is fine.
> Fix some Markdown issues

- .github/workflows/linter.yml
It seems to me that the linter does not report on docstring issues.
> flake8 PR check for docstrings

- src/pymor/operators/constructions.py
- src/pymor/operators/numpy.py
- src/pymortests/operators.py
> Fix lstsq FutureWarning in NumpyMatrixOperator.apply_inverse

- src/pymor/analyticalproblems/elliptic.py
> Fixes for documentation of stationary problem

- src/pymor/operators/interface.py
> Improve OperatorInterface._radd_sub

- src/pymor/operators/mpi.py
Fixes #1316.
@josefinez, does this work for you?
> Let MPIOperator.assemble return self when operator is unchanged

- src/pymor/models/iosys.py
- src/pymor/reductors/h2.py
- src/pymordemos/delay.py
- src/pymordemos/heat.py
- src/pymordemos/string_equation.py
- src/pymortests/iosys_add_sub_mul.py
This PR should significantly increase the coverage of `iosys.py`.
**Update** (API changes): `h2_norm` moved from `TransferFunction` to `InputOutputModel`, `h2_inner` added to `InputOutputModel`.
> Test system operations, other fixes and improvements

- setup.cfg
- src/pymor/discretizers/builtin/fv.py
- src/pymor/discretizers/builtin/gui/gl.py
- src/pymor/discretizers/builtin/gui/matplotlib.py
- src/pymortests/affine_grid.py
- src/pymortests/pickling.py
These are all safe changes, except https://github.com/pymor/pymor/commit/cf758a57313cbf2292cf386ae20707691727d0e3
Looks like the linter found an actual bug here?
> Fix warnings

- .ci/azure/pipeline-osx.yml
- src/pymor/analyticalproblems/text.py
- src/pymortests/analyticalproblem.py
- src/pymortests/core/cache.py
- src/pymortests/demos.py
- src/pymortests/gui.py
This PR fixes a few issues from  #1174
> Fix a few platform specific issues

- docs/source/developer_docs.rst
> [docs] fix rst link

- docs/source/tutorial_lti_systems.md
> [docs] remove system norm subsections

- src/pymor/discretizers/builtin/gui/matplotlib.py
> Fix height of plots generated by 1d matplotlib visualizer

- src/pymortests/parameters.py
> Add test for parameters.parse(mu)

- docs/source/developer_docs.rst
- docs/source/index.rst
- [docs] note directly invoking pytest
- [docs] remove empty API doc section for demos
> doc pytest

- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/operators/list.py
- src/pymor/vectorarrays/list.py
> Introduce ListVectorSpace.vector_type and make make_array smarter

- docs/source/release_notes/2021.1.rst
- docs/source/release_notes/all.rst
I started working on the 2021.1 release notes file. Feel free to add to the file or change my suggested PRs mentioned in the notes.
> Release notes for 2021.1

- src/pymor/algorithms/error.py
- src/pymor/basic.py
- src/pymordemos/parabolic_mor.py
- src/pymordemos/thermalblock.py
- src/pymordemos/thermalblock_adaptive.py
- src/pymordemos/thermalblock_simple.py
This
- allows to split the plotting from the data collection
- allows to customize what is plotted a bit more:
* allow to specify names for the custom plots
* allow to disable/enable plotting of effectivities
* allow to disbale/enable plotting of conditions
* allow to plot custom values along errors
> Update error analysis

- docs/source/tutorial_optimization.md
I put some work in decreasing lines of code and being able to hide more code for presentations !
> Refactor optimization tutorial

- src/pymortests/vectorarray.py
> [tests] tighten vecarray COW + add regression test case

- src/pymor/discretizers/builtin/cg.py
- src/pymor/discretizers/builtin/fv.py
- src/pymor/models/basic.py
- src/pymor/models/interface.py
- src/pymor/operators/constructions.py
- src/pymortests/fixtures/operator.py
Also use `NumpyConversionOperator` in the discretizers to ensure that `output_functional.range` always is a `NumpyVectorSpace`.
> Add NumpyConversionOperator

- src/pymor/algorithms/gram_schmidt.py
> Edit `gram_schmidt_biorth` docstring

- .ci/gitlab/deploy_docs.bash
- docs/source/autoapi_pymor.py
- src/pymor/bindings/dunegdt.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/bindings/pymess.py
- src/pymor/bindings/slycot.py
- src/pymor/models/neural_network.py
- src/pymor/reductors/neural_network.py
- [docs] add repeasted `if` workaround for autoapi
- [docs] fix sphinx build
closes #1343
> Autoapi workarounds

- .ci/azure/pipeline-osx.yml
- .ci/azure/pipeline-win.yml
- dependencies.py
- requirements-optional.txt
- requirements.txt
- src/pymor/algorithms/samdp.py
I changed the stopping criterion in the RQI from the relative change of the solution to the relative residual. I am not sure why I have not implemented it this way in the first place. This fixes #1519 for me, @renefritze can you confirm this?
> Change RQI stopping criterion

- docs/Makefile
- docs/source/conf.py
- docs/source/minimal_cpp_demo/CMakeLists.txt
- src/pymortests/affine_grid.py
- src/pymortests/conftest.py
- src/pymortests/fixtures/grid.py
- src/pymortests/function.py
- src/pymortests/grid.py
- [tests|affine_grid] also scale tolerances for larege abs coord values
- [tests] make np.testing monkeying into a global auto use fixture
- [tests] make JAC entity drawn from a hypothesis strategy
> Fix Weekly CI jobs

- .github/workflows/pytest_results.yml
- [ci] disable pytest result commenting on PRs
- fixup! explicit fail to test pytest annotations
> Disable Pytest PR Comments

- src/pymor/bindings/fenics.py
Similar to what is done for NumpyMatrixOperator, calling `apply_inverse` on a `FenicsMatrixOperator` creates a `LinearSolver` object and stores it as a private attribute of the operator. In particular for direct solvers, this dramatically speeds up repeated `apply_inverse` calls as the LU decomposition is only computed once and stored in the solver object. A new default allows to disable this behavior.
> FEniCS: Save LinearSolver object in FenicsMatrixOperator to accelerate repeated solves

- .ci/gitlab/install_checks/debian-bullseye/check.bash
- .github/workflows/conda_tests.yml
- .pre-commit-config.yaml
> [ci|github] also run on pull-requests, but not duplicate

- src/pymor/algorithms/lyapunov.py
> fix incorrect docstring

- src/pymor/analyticalproblems/burgers.py
- src/pymor/discretizers/builtin/list.py
- src/pymor/operators/numpy.py
- src/pymor/parameters/base.py
- src/pymor/scripts/pymor_demo.py
- src/pymor/tools/floatcmp.py
- src/pymordemos/elliptic.py
- src/pymortests/algorithms/svd_va.py
- src/pymortests/solver.py
this PR removes unused imports and fixes some more flake8 errors.
> remove unused imports

- src/pymor/discretizers/builtin/cg.py
> Fix default value of AdvectionOperatorP1.advection_function

- docs/source/conf.py
Following https://gist.github.com/bskinn/0e164963428d4b51017cebdb6cda5209
and potentially waiting on the situation with scipy being resolved in #1557
> [docs] update intersphinx mappings

- docs/source/tutorial_builtin_discretizer.md
- src/pymor/analyticalproblems/expressions.py
Fixes #1569. @peoe, please take a look ..
Further, the error handling has been improved.
> Traverse ast to parse literals in Expressions

- .mailmap
maps all my author appearances to one as @pmli suggested.
> add mailmap entries for @artpelling

- AUTHORS.md
- src/pymor/reductors/basic.py
- src/pymor/reductors/bt.py
This PR will enable discrete-time classical BT.
> enable discrete-time BT

- .mailmap
- AUTHORS.md
- docs/source/bibliography.bib
- docs/source/substitutions.py
- src/pymor/algorithms/symplectic.py
- src/pymor/operators/symplectic.py
- src/pymortests/algorithms/symplectic.py
This PR adds symplectic basis generation techniques which is required for structure-preserving MOR of Hamiltonian systems.
> Algorithms for symplectic MOR

- src/pymortests/base.py
- src/pymortests/lyapunov.py
- src/pymortests/riccati.py
This PR shall implement the wrapper mentioned by @renefritze in issue #1578.
@HenKlei: Can you have a look at this and confirm that it is implemented in the right file and works as intended?
> Add decorator for required test modules

- src/pymor/models/neural_network.py
- src/pymortests/neural_network.py
Thanks to @jacktang for spotting the mistake and providing the fix.
This also adds a regression test for the issue
Closes #1649
> [models.nn] fix output_functional not properly assigned

- src/pymor/operators/interface.py
As a fallback for operators which do not implement their own linear solvers, `Operator.apply_inverse` calls out to an unpreconditioned LGMRES, which usually fails to converge.
As a better alternative, we now try to first convert the operator to a `NumpyMatrixOperator` by calling `to_matrix`, converting the `source` and `range` arrays via `to_numpy`/`from_numpy`. This is useful, for instance, if one has to deal with `BlockOperators` of `NumpyMatrixOperators`. If this approach fails, the LGMRES fallback is still used.
Additionally, when these default implementations are used, a warning is now logged. The warning can be silenced by explicitly specifying `to_matrix` or `generic_lgmres` as the solver in `solver_options`.
> Provide a default implementation of apply_inverse by converting to a NumPy/SciPy matrix

- setup.cfg
- src/pymortests/neural_network.py
Addresses the long execution time of `test_linear_function_fitting` mentioned in #1665.
> Reduce neural network test

- src/pymor/vectorarrays/list.py
- src/pymortests/vectorarray.py
> Fix ComplexifiedVector.scal

- docs/source/autoapi_pymor.py
- docs/source/heat_equation.py
- docs/source/myst_code_init.py
- docs/source/substitutions.py
- docs/source/unstable_heat_equation.py
- src/pymor/analyticalproblems/domaindescriptions.py
- src/pymor/core/base.py
- src/pymor/core/logger.py
- src/pymor/discretizers/builtin/cg.py
- src/pymor/discretizers/builtin/grids/interfaces.py
- src/pymor/discretizers/builtin/gui/jupyter/threejs.py
- src/pymor/parameters/base.py
- src/pymor/parameters/functionals.py
- src/pymordemos/analyze_pickle.py
- src/pymordemos/burgers_ei.py
I have resolved all basic flake8 issues here that were not related to the docstrings. As mentioned in #1551, there are 34 issues left to solve, 32 of which are `D205 1 blank line required between summary line and description`.
Going by what @sdrave preached today, I looked at the history to find out who is to blame.
The award for most issues in one file goes to @pmli and `./src/pymor/discretizers/builtin/grids/interfaces` with a whopping 19 of 20 total D205 in that file 🏆 
The remaining 14 issues are listed below:
@sdrave:
@pmli:
@renefritze:
Fixes #1551
> resolve all remaining flake8 issues (fixes #1551)

- src/pymor/algorithms/image.py
- src/pymor/algorithms/newton.py
- src/pymor/algorithms/projection.py
- src/pymor/analyticalproblems/expressions.py
- src/pymor/analyticalproblems/functions.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/scipy.py
- src/pymor/core/base.py
- src/pymor/core/cache.py
- src/pymor/core/defaults.py
- src/pymor/discretizers/builtin/domaindiscretizers/gmsh.py
- src/pymor/operators/interface.py
- src/pymor/operators/numpy.py
- src/pymor/parallel/ipython.py
- src/pymor/tools/io/matrices.py
- src/pymordemos/thermalblock_gui.py
This is cherry-picked from #1487.
> Fix pylint raise-missing-from

- src/pymortests/demos.py
> Reduce parametric string demo size during testing

- docs/source/conf.py
Split off from #1680 
Only adage form that PR that doesn't need more changes in the autoapi innards.
> [docs] show inheritance

- src/pymortests/fixtures/grid.py
This should fix the problems with `test_vtkio`
> [tests] refactor interval drawing to reduce filtering amount

- docs/source/release_notes/2022.1.rst
Added description of PRs for symplectic MOR.
> Symplectic MOR in release notes

- conftest.py
the largest will be used in weekly scheduled pipelines
> [tests] derandomize all but the largest hypothesis profiles

- docs/source/index.rst
> [docs] fix Python typo

- .github/workflows/pytest_results.yml
This is a prerequisite for #1758
> [ci] limit what counts as a pytest result file

- .ci/gitlab/ci.yml
- .ci/gitlab/common_test_setup.bash
- .ci/gitlab/submit.bash
- .ci/gitlab/template.ci.py
- .ci/gitlab/test_mpi.bash
- .ci/gitlab/test_numpy_git.bash
- .ci/gitlab/test_oldest.bash
- .ci/gitlab/test_tutorials.bash
- .ci/gitlab/test_vanilla.bash
- .codecov.yml
- .github/workflows/conda_tests.yml
This should help with fluctuating cov percentages
> Split coverage upload into separate job

- src/pymor/models/iosys.py
> [models.iosys] set cache_region to 'memory'

- .ci/gitlab/pypi_deploy.bash
- src/pymor/algorithms/rules.py
- src/pymor/core/config.py
- src/pymor/operators/mpi.py
- src/pymortests/mpi_run_demo_tests.py
- [ci] use non-legacy upload endpoint for pypi
- [MPIOperator] fix apply_adjoint implementation
- [RuleTable] let get_children return a list
- [fenics] reset dlopen flags after dolfin import
> Backports for #1779 + #1782 + #1781

- src/pymor/reductors/aaa.py
- src/pymordemos/dd_parametric_heat.py
p-AAA PR is #1756.
@lbalicki Feel free to reject, merge, or edit as you like.
> p-AAA PR edits

- docs/source/conf.py
This hopefully solves the current CI-issues in #1496, see also https://github.com/spatialaudio/nbsphinx/issues/24.
> Add console highlighting extension to `conf.py`

- src/pymor/core/config.py
> [config] treat colab like vanilla ipython

- docs/Makefile
> [docs] re-enable parallel build

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
- .github/labeler.yml
- .markdownlint.yml
- .pre-commit-config.yaml
- AUTHORS.md
- CONTRIBUTING.md
- README.md
- docs/source/getting_started.md
- docs/source/release_notes/2020.1.rst
- docs/source/tutorial_basis_generation.md
- docs/source/tutorial_external_solver.md
- docs/source/tutorial_mor_with_anns.md
- docs/source/tutorial_optimization.md
- logo/README.md
- src/pymor/analyticalproblems/expressions.py
- src/pymor/models/symplectic.py
- src/pymor/reductors/neural_network.py
- src/pymor/tools/typer.py
- src/pymordemos/burgers_dmd.py
This ports the fixes and from #1625 and also the markdown linter that was added there.
> From pr 1625

- docs/source/developer_docs.md
> [docs] update notes for the git{lab,hub} bridge service

- .codecov.yml
- .gitignore
- .pre-commit-config.yaml
- setup.cfg
- src/pymor/core/exceptions.py
- src/pymor/discretizers/fenics/cg.py
- src/pymor/scripts/pymor_demo.py
- src/pymordemos/neural_networks_instationary.py
- src/pymortests/base.py
- src/pymortests/demos.py
- [tests] turn missing records for check_results into an exception
- [setup] re-introduce coverage exception for version.py
> Improve test coverage

- src/pymor/analyticalproblems/functions.py
- src/pymortests/discretizers/fenics.py
Please have a look at the failure @sdrave. 
I came across this on a branch I'm still wanting
to finish that increases coverage in badly covered areas.
> [tests] exercise the fenics discretizer

- src/pymortests/reductors/mt.py
This should increase MT coverage to 94%.
See https://github.com/pymor/pymor/issues/1516#issuecomment-1397055593
> Test modal truncation options

- .ci/gitlab/template.ci.py
- docs/source/tutorial_mor_with_anns.md
- src/pymor/models/iosys.py
- src/pymor/reductors/basic.py
> Fixes in `LTIModel` time-stepping

- src/pymor/discretizers/builtin/cg.py
I came across some bugs and strange things in the cg discretizer.
> Some fixes in the cg discretizers

- CITATION.cff
This seems to be used by Zenodo (and possibly other places).
> Add Hendrik to `CITATION.cff`

- src/pymor/operators/block.py
- src/pymortests/operators/block.py
> Implement BlockOperator.jacobian by computing Jacobians of blocks

- .github/workflows/conda_cov_upload.yml
- .github/workflows/conda_tests.yml
See https://github.com/codecov/codecov-action/issues/837.
> Fix failing codecov uploads.

- docs/source/tutorial_basis_generation.md
> Backport:  Improve basis generation tutorial

- docs/RELEASE_CHECKLIST.md
- docs/RELEASE_PROCESS.md
This is only a first draft, so please add your thoughts here or in a discussion on this @pymor/all. Of course, the number of weeks have to be filled at some point.
> Release process/schedule

- requirements-ci-oldest-pins.in
This file should have been included in #2014.
> [CI] Add missing requirements-ci-oldest-pins.in

- src/pymor/reductors/interpolation.py
> Make GenericBHIReductor an abstract class

- src/pymor/algorithms/projection.py
- src/pymor/operators/ei.py
> Fix typo in `ProjectedEmpiciralInterpolatedOperator`

- src/pymor/algorithms/projection.py
- src/pymor/algorithms/simplify.py
This branch contains 2 fixes, related to an issue on `ExpandRules` [here](https://github.com/pymor/pymor/issues/2074) and `ProjectRules` [here](https://github.com/pymor/pymor/issues/2072).
> Fix ProjectRules ExpandRules 

- docs/source/tutorial_projection.md
- src/pymor/algorithms/projection.py
- src/pymor/operators/block.py
- src/pymor/operators/constructions.py
- src/pymortests/algorithms/projection.py
> Add suffix to names in `project`

- AUTHORS.md
- docs/source/bibliography.bib
- src/pymor/algorithms/riccati.py
- src/pymor/basic.py
- src/pymor/bindings/scipy.py
- src/pymor/models/iosys.py
- src/pymor/reductors/bt.py
- src/pymordemos/phlti.py
- src/pymortests/algorithms/lyapunov.py
- src/pymortests/algorithms/riccati.py
This PR implements PRBT for passive LTIModels.
> Positive real balanced truncation (PRBT)

- docker/Dockerfile.ci-oldest
- requirements-ci-oldest.txt
- src/pymor/bindings/slycot.py
> Remove code for older slycot

- docs/source/tutorial_basis_generation.md
- docs/source/tutorial_builtin_discretizer.md
- docs/source/tutorial_projection.md
For 5 mins, I thought that cg stands for Conjugate Gradient and then at some point I was too confused :smile:
> Fix a few typos in tutorials

- src/pymortests/fixtures/operator.py
> Test sparse matrices and arrays

- src/pymor/algorithms/symplectic.py
- src/pymordemos/symplectic_wave_equation.py
- src/pymortests/algorithms/symplectic.py
- renames `psd_cotengent_lift` method
> Fix "cotangent" typo

- README.md
> Backport of "Remove mention of mamba"

- .ci/gitlab/docs_deploy.bash
> Backport #2151

- docs/source/getting_started.md
> Backport #2156

- src/pymor/reductors/aaa.py
This fixes #2165 for me. I also removed `np.vectorize` from the implementation since it is not really necessary and is slightly slower than just doing the manual loop.
> Fix Deprecation in p-AAA

- docs/source/tutorial_vectorarray.md
- docs/source/tutorials.md
> Add tutorial on VectorArray basics

- src/pymor/parameters/base.py
- src/pymortests/parameters/parameters.py
> Fix parsing of scalar time-dependent parameter values

- pyproject.toml
- requirements-ci-oldest-pins.in
- requirements-ci-oldest.txt
- src/pymor/discretizers/builtin/gui/jupyter/kthreed.py
- src/pymor/discretizers/builtin/gui/matplotlib_base.py
- src/pymor/discretizers/builtin/gui/qt/gl.py
- src/pymor/discretizers/builtin/gui/qt/matplotlib.py
> Handle matplotlib.cm.get_cmap deprecation

- docs/source/_static/pymor.css
- docs/source/_templates/layout.html
I did some jQuery hacking and this is probably what @artpelling was looking for, right?
> Added functionality to collapse long lists in the api reference

- src/pymor/reductors/aaa.py
- src/pymortests/reductors/paaa.py
Fixes #2210. For me it works for parametric/non-parametric and all MIMO scenarios.
> p-AAA MIMO Fix

- src/pymor/algorithms/pod.py
- src/pymortests/algorithms/pod.py
> Add optional argument for returning coefficients in POD

- docs/source/bibliography.bib
- src/pymor/reductors/aaa.py
- ran `bibtex-tidy` v1.11.0 with:
```bash
bibtex-tidy docs/source/bibliography.bib --modify --omit=abstract,keywords \
--curly --numeric --months --space --align=14 --blank-lines --sort \
--sort-fields --strip-comments --trailing-commas --remove-empty-fields --wrap
```
> Run bibtex-tidy

- .pre-commit-config.yaml
- pyproject.toml
This hook has more [configuration options](https://github.com/pappasam/toml-sort/tree/main?tab=readme-ov-file#configuration-file) than the one in #2125.
> Add toml-sort hook

- .codecov.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/actions/miniconda_tests/action.yml
- .github/labeler.yml
- .github/workflows/add_labels.yml
- .github/workflows/citation.yml
- .github/workflows/conda_cov_upload.yml
- .github/workflows/conda_tests.yml
- .github/workflows/enforce-labels.yml
- .github/workflows/external_pr_mirror.yml
- .github/workflows/external_pr_unmirror.yml
- .github/workflows/git_checks.yml
- .github/workflows/link_check.yml
- .github/workflows/pyproject_toml_changes.yml
- .markdownlint.yml
- .pre-commit-config.yaml
- CITATION.cff
- pyproject.toml
Has more [configuration options](https://lyz-code.github.io/yamlfix/#configuration-options) than the one in #2124.
> Add yamlfix hook

- src/pymor/reductors/mt.py
> Backport: Avoid assumption of exact complex conjugation in MTReductor

- AUTHORS.md
- CONTRIBUTING.md
- docs/RELEASE_PROCESS.md
As discussed in #2218.
Turns out, we already state that attributions are made unless the author does not want it. I have added some sentences clarifying that
- Attributions mention GitHub user name and name from GitHub profile in the future
- `AUTHORS.md` is updated as part of the release process.
> Clarify how attributions are made

- conftest.py
- pyproject.toml
- src/pymor/discretizers/builtin/grids/subgrid.py
- src/pymortests/algorithms/basic.py
- src/pymortests/algorithms/bernoulli.py
- src/pymortests/algorithms/eigs.py
- src/pymortests/algorithms/lyapunov.py
- src/pymortests/algorithms/projection.py
- src/pymortests/algorithms/rand_la.py
- src/pymortests/algorithms/riccati.py
- src/pymortests/algorithms/samdp.py
- src/pymortests/algorithms/sylvester.py
- src/pymortests/algorithms/to_matrix.py
- src/pymortests/complex_values.py
- src/pymortests/fixtures/function.py
- src/pymortests/fixtures/operator.py
- src/pymortests/fixtures/parameter.py
- src/pymortests/neural_network.py
- src/pymortests/operators/block.py
- src/pymortests/operators/operators.py
- src/pymortests/reductors/loewner.py
- src/pymortests/reductors/paaa.py
- src/pymortests/strategies.py
- src/pymortests/vectorarray.py
> Add Ruff NPY rules, rework test randomization

- src/pymor/discretizers/builtin/grids/subgrid.py
> Make Subgrid.indices_from_parent_indices more readable

- src/pymor/discretizers/builtin/cg.py
> Use np.add.at to assemble vectors in builtin discretization toolkit

- src/pymor/algorithms/eigs.py
> Make eigs a bit more robust w.r.t. breakdowns in arnoldi iteration

- docs/source/bibliography.bib
- src/pymor/reductors/h2.py
- src/pymordemos/dd_heat.py
> Add vector fitting

- docs/source/tutorial_ph.md
- src/pymor/models/examples.py
- src/pymordemos/dd_heat.py
- src/pymordemos/dd_parametric_heat.py
- src/pymordemos/delay.py
- src/pymordemos/heat.py
- src/pymordemos/parametric_heat.py
- src/pymordemos/phlti.py
- src/pymortests/demos.py
- src/pymortests/reductors/loewner.py
- src/pymortests/reductors/mt.py
> Move some models from demos and tests to models.examples

- docs/source/bibliography.bib
- docs/source/tutorial_basis_generation.md
- docs/source/tutorial_bt.md
- docs/source/tutorial_builtin_discretizer.md
- docs/source/tutorial_external_solver.md
- docs/source/tutorial_interact.md
- docs/source/tutorial_interpolation.md
- docs/source/tutorial_lti_systems.md
- docs/source/tutorial_mor_with_anns.md
- docs/source/tutorial_optimization.md
- docs/source/tutorial_ph.md
- docs/source/tutorial_projection.md
- docs/source/tutorial_unstable_lti_systems.md
- docs/source/tutorial_vectorarray.md
- docs/source/tutorials.md
- src/pymor/algorithms/krylov.py
- src/pymor/tools/plot.py
> Add tutorial on interpolation for LTI systems

- src/pymor/algorithms/scm.py
Using `eigs` with `mode='SM'` does not work for harder problem. In particular, the following example will fail. With this PR, we use the shift-invert mode of eigs to get a more robust algorithm.
```python
from pymor.models.examples import thermal_block_example
fom = thermal_block_example()
from pymor.algorithms.scm import construct_scm_functionals
initial_parameter = problem.parameter_space.sample_randomly(1)[0]
training_set = problem.parameter_space.sample_randomly(50)
coercivity_estimator, _, _ = construct_scm_functionals(
fom.operator, training_set, initial_parameter, product=fom.h1_0_semi_product, max_extensions=10, M=5)
```
> Use shift-invert mode of eigs in successive constraints method

- docs/source/index.md
- docs/source/mor_methods.md
- docs/source/tutorials.md
- src/pymor/algorithms/greedy.py
- src/pymor/models/examples.py
See https://docs.pymor.org/mor-methods-howto/mor_methods.html
Fixes #1563.
> Add MOR methods overview to documentation

- src/pymor/algorithms/ei.py
- src/pymortests/algorithms/ei.py
> Fix ei_greedy for complex-valued arrays

- src/pymor/algorithms/krylov.py
- src/pymortests/algorithms/krylov.py
> Block Arnoldi

- README.md
I noticed that our affiliation is not mentioned anywhere, so I made a small badge.
> add NumFOCUS badge

- README.md
- src/pymor/algorithms/chol_qr.py
- src/pymor/algorithms/rand_la.py
- src/pymor/models/examples.py
- src/pymor/parameters/base.py
- src/pymor/reductors/loewner.py
- src/pymortests/algorithms/chol_qr.py
- src/pymortests/reductors/loewner.py
This PR fixes bugs reported in #2245 and others in the `LoewnerReductor`. The tests are also improved and now require that the correct order of the approximated rational function is (approximately) recovered.
Fixes #2245.
> Fix Loewner Bugs and Improve Tests

- .github/workflows/conda_tests.yml
See https://github.com/actions/runner-images/issues/10721.
> Use macos-13 CI image

- src/pymor/algorithms/eigs.py
- src/pymor/algorithms/symplectic.py
- src/pymor/core/cache.py
- src/pymor/core/defaults.py
- src/pymor/discretizers/builtin/grids/referenceelements.py
- src/pymor/models/basic.py
- src/pymordemos/neural_networks.py
- src/pymordemos/neural_networks_instationary.py
- src/pymortests/demos.py
ran a spell checker and found some bad guys :)
> fix spelling

- AUTHORS.md
- docs/source/release_notes/2024.1.rst
- docs/source/release_notes/2024.2.rst
- docs/source/release_notes/all.rst
Please take a look @pymor/main which features should be included where and write the release notes for those things you feel responsible for.
Rendered notes are [here](https://docs.pymor.org/release-notes-2024-2/release_notes/all.html#pymor-2024-2-december-20-2024).
> Release notes for 2024.2 release

- src/pymor/models/iosys.py
- src/pymor/reductors/bt.py
- src/pymordemos/heat.py
> Change `_sv_U_V` to `_hankel_svd`

- src/pymor/bindings/scipy.py
This fixes a bug introduced by #2405.
> Fix shape of scipy solver return values

- docs/source/substitutions.py
- src/pymor/algorithms/timestepping.py
- src/pymor/operators/constructions.py
- src/pymortests/algorithms/timestepping.py
- src/pymortests/operators/operators.py
> Allow for `VectorArrays` as right hand side in time stepping methods

- src/pymor/discretizers/builtin/gui/jupyter/matplotlib.py
- src/pymor/discretizers/builtin/gui/matplotlib_base.py
Declared as:
if isinstance(U, VectorArray):
U = (U,)
It yields an attribute error that messes with the plot.
> Fix jupyter visualizer with matplotlib backend

- src/pymor/discretizers/builtin/gui/jupyter/matplotlib.py
- src/pymor/discretizers/builtin/gui/matplotlib_base.py
> Backport "Fix jupyter visualizer with matplotlib backend"

- src/pymor/operators/constructions.py
- src/pymor/parameters/functionals.py
- src/pymortests/parameters/parameter_functionals.py
Implements conjugate method for ParameterFunctional. Overwrites in ConjugateParameterFunctional to return the original functional.
> implement conjugate method for ParameterFunctional
