- src/pymor/gui/qt.py
When experimenting with the VTK exporter I notices that the export does not work in case of the given argument `U` being a tuple. This is because the function erroneously tries to access `self.U` which does not exists and must be replaced by `U` itself.
> [gui.qt] fix vtk export for tuples

- src/pymor/gui/qt.py
pymor broke down in case of `separate_colorbars=True` because the wrong Qt entity was added to `plot_layout` (`plot`, but `hlayout` is correct here). The issue is resolved by this commit.
> [gui.qt] fix separate_colorbars in case of no legend

- src/pymor/gui/qt.py
If you put multiple plots into one GUI the behaviour is to always have two columns. I would like to be able to choose the number of columns that is used, thus I introduced a new argument `columns` (with a default value of 2 in order to keep the old behaviour).
This new argument has to be added to both the function `visualize_patch` and the method `PatchVisualizer.visualize`. Since I think it is advisable to keep the former order of arguments I added it the the end.
I did not implement an assert of the form
```python
assert (type(columns) is int) and (columns > 0)
```
since I find it superfluous.
> [gui.qt] user can set column count for PatchVisualizer

- src/pymor/core/cache.py
- src/pymor/playground/functions/bitmap.py
1. Fix logger import in case of disabled caching. Sorry, Stephan, I think your fix is wrong, or do I miss something?
2. In older versions of PIL (for example the version shipped with Ubuntu 14.04), the "Image" does not support the array-Interface. Therefore it is not possible to put an "Image" directly into the numpy-array constructor. You end up with a 1x1 array of type "object". This is fixed here.
> Two bugfixes

- src/pymor/domaindescriptions/interfaces.py
- src/pymor/grids/interfaces.py
The has_only_{dirichlet, neumann} functions are unused and seem to be superfluous.
> has_only_{dirichlet, neumann} removed from BoundaryInfo/DomainDescriptionInterface

- src/pymor/domaindescriptions/interfaces.py
- src/pymor/grids/interfaces.py
- src/pymor/operators/cg.py
To support Robin boundary conditions the following modifications were made:
- `DomainDescriptionInterface` and `BoundaryInfoInterface` extended so that the Robin condition can be handled just like Dirichlet and Neumann conditions
- `L2ProductFunctional{P|Q}1` can be supplied with `robin_data` to assemble the rhs part of the Robin BC
- `RobinBoundaryOperator` introduced to supply Robin BC contribution to the stiffness matrix
> Support for Robin boundary conditions

- .travis.yml
- docs/source/substitutions.py
- src/pymor/core/pickle.py
- src/pymor/parallel/__init__.py
- src/pymor/parallel/defaultimpl.py
- src/pymor/parallel/dummy.py
- src/pymor/parallel/interfaces.py
- src/pymor/parallel/ipython.py
- src/pymor/parallel/manager.py
- src/pymor/tools/counter.py
- src/pymortests/core/interface.py
The pull request contains pyMOR's parallelization framework from the pymor-paper branch (only the framework, not the parallelized algorithms).
Before we merge to master, we should double-check if we are satisfied with the interfaces. (A bit of documentation would also be nice, I guess.)
As a first commit I would propose to rename some methods as follows:
- distribute -> push
- distribute_array -> scatter_array
- distribute_list -> scatter_list
Any comments?
> Add parallelization framework

- .travis.yml
- src/pymor/algorithms/greedy.py
- src/pymor/core/pickle.py
- src/pymor/parallel/__init__.py
- src/pymor/parallel/defaultimpl.py
- src/pymor/parallel/dummy.py
- src/pymor/parallel/interfaces.py
- src/pymor/parallel/ipython.py
- src/pymor/parallel/manager.py
- src/pymor/tools/context.py
- src/pymor/tools/counter.py
- src/pymordemos/thermalblock.py
- src/pymortests/core/interface.py
This pull request contains the (updated) parallelized version of `pymor.algorithms.greedy` from the pymor-paper branch.
> Parallelize greedy algorithm

- setup.py
- src/pymor/discretizers/advection.py
- src/pymor/discretizers/elliptic.py
- src/pymor/grids/_unstructured.pyx
- src/pymor/grids/defaultimpl.py
- src/pymor/grids/interfaces.py
- src/pymor/grids/oned.py
- src/pymor/grids/rect.py
- src/pymor/grids/tria.py
- src/pymor/grids/unstructured.py
- src/pymor/gui/qt.py
- src/pymortests/affine_grid.py
- src/pymortests/fixtures/grid.py
This adds pymor.grids.unstructured.UnstructuredTriangleGrid as a base class for unstructured 2d grids with triangle reference elements, partially resolving #9.
> Add UnstructuredTriangleGrid

- src/pymor/core/cache.py
- src/pymor/discretizations/basic.py
- src/pymor/grids/interfaces.py
- src/pymordemos/burgers.py
- src/pymordemos/burgers_ei.py
- src/pymordemos/thermalblock.py
- src/pymordemos/thermalblock_fenics.py
- src/pymortests/cache.py
Cache regions are marked as persistent or not. Non-persistent cache regions are cleared at program exit. State ids are automatically generated when persistent cache regions are selected.
This addresses #121, #180.
> Add support for persistent cache regions

- docs/source/substitutions.py
- src/pymor/algorithms/genericsolvers.py
- src/pymor/algorithms/newton.py
- src/pymor/algorithms/timestepping.py
- src/pymor/operators/basic.py
- src/pymor/operators/cg.py
- src/pymor/operators/constructions.py
- src/pymor/operators/ei.py
- src/pymor/operators/fenics.py
- src/pymor/operators/fv.py
- src/pymor/operators/interfaces.py
- src/pymor/operators/mpi.py
- src/pymor/operators/numpy.py
- src/pymor/playground/operators/numpy.py
- src/pymortests/base.py
- src/pymortests/operators.py
- src/pymortests/solver.py
This pull request contains the following changes:
- `options` is removed from `OperatorInterface.apply_inverse`
- `invert_options` is removed from `OperatorInterface`
- `solver_options` is added to `OperatorInterface`
- `solver_options` can be given to the implict Euler algorithm.
If not `None`, `solver_options` is a dict which can contain the keys
`'inverse'` and `'jacobian'`. The following rules apply:
- `OperatorInterface.apply_inverse` uses the `'inverse'` entry
of `solver_options` for solver selection and configuration.
If not available, or `None`, defaults are used.
- `OperatorInterface.jacobian` uses the values of the `'jacobian'`
entry of `solver_options` as `solver_options` for the Jacobian
operator. If missing, `solver_options` is set to `None`.
- `OperatorInterface.assemble` …
> Repace 'invert_options' by 'solver_options' (second try)

- src/pymor/discretizers/disk.py
- src/pymor/operators/numpy.py
- src/pymor/tools/io.py
- src/pymor/vectorarrays/numpy.py
This pull request adds a `tools.io.load_matrix` helper function, which tries hard to load matrix data from different possible file formats. `NumpyMatrixOperator.from_file` and `NumpyVectorArray.from_file` use this method to create new instances from data in a given file. Moreover, `discretizers.disk` have been adapted to use the new functionality.
This addresses #118.
> Add from_file factory methods for NumpyMatrixOperator and NumpyVectorArray

- src/pymor/algorithms/ei.py
- src/pymor/parallel/dummy.py
- src/pymordemos/burgers_ei.py
This pull request contains the parallelized ei_greedy implementation from the pymor-paper branch.
> Parallelize ei_greedy algorithm

- src/pymor/algorithms/adaptivegreedy.py
- src/pymor/core/logger.py
- src/pymordemos/thermalblock_adaptive.py
This pull request adds a greedy search algorithm with adaptive training set refinement according to
> Haasdonk, B.; Dihlmann, M. & Ohlberger, M.,
> A training set and multiple bases generation approach for parameterized
> model reduction based on adaptive grids in parameter space,
> Math. Comput. Model. Dyn. Syst., 2011, 17, 423-442
This pull request depends on #212.
> add adaptive greedy algorithm for basis generation

- src/pymor/playground/operators/__init__.py
- src/pymor/playground/operators/block.py
- src/pymortests/block.py
Code: src/pymor/playground/block.py
Tests: src/pymortests/block.py
> BlockOperator and BlockDiagonalOperator

- src/pymor/algorithms/genericsolvers.py
- src/pymor/playground/vectorarrays/disk.py
- src/pymor/vectorarrays/block.py
- src/pymor/vectorarrays/fenics.py
- src/pymor/vectorarrays/interfaces.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/mpi.py
- src/pymor/vectorarrays/numpy.py
- src/pymortests/vectorarray.py
> l2_norm2 methods

- setup.py
I observed strange effects on my machine when installing a lot of packages at once. For example, the command
`pip install scipy Sphinx docopt pytest-runner ipython ipyparallel matplotlib pyopengl pyside pyamg mpi4py pytest`
managed to install Sphinx without its dependencies. The dependencies are only installed correctly when installing packages one by one. Therefore I'd like to change the suggested command to install packages from "pip install foo bar" to "for pname in foo bar; do pip install $pname; done"
> [build] change suggested pip command to install packeges one by one

- docs/source/technical_overview.rst
- src/pymor/playground/vectorarrays/disk.py
- src/pymor/vectorarrays/block.py
- src/pymor/vectorarrays/interfaces.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/mpi.py
- src/pymor/vectorarrays/numpy.py
- src/pymortests/complex_values.py
- src/pymortests/vectorarray.py
and its implementations. See #261
> This removes `replace` from the VectorArray interface

- src/pymor/analyticalproblems/parabolic.py
- src/pymordemos/parabolic_extended.py
Hi everyone!
Since there were complaints at the user meeting that I didn't contribute yet to pyMOR.. I'll try my first pull request ;-)
Andreas added advection terms, reaction terms and Robin boundary conditions to EllipticProblem and the corresponding operators. Since I need these for parabolic equations, I modified the ParabolicProblem to also support the new terms. 
So, hopefully, after some fun with my messy git branches, I got this right at the end...
> Extend parabolic

- src/pymortests/demos.py
I want this since I won't be attempting to install a python 3 version of the fenics stack on centos 5, which I would need to get the wheels tests working.
> [tests] skip tests with needed, but missing, fenics

- src/pymor/gui/gl.py
This is some work I have done a while ago. We still need to wire everything up ...
> Support different colormaps in GLPatchWidget

- src/pymor/operators/numpy.py
- src/pymortests/fixtures/operator.py
- src/pymortests/operators.py
> Add NumpyGenericOperator.apply_adjoint

- src/pymor/analyticalproblems/burgers.py
- src/pymor/functions/basic.py
- src/pymortests/fixtures/function.py
This makes defining ExpressionFunctions much more elegant. Also, we already do the same for `ExpressionParameterFunctional`.
> [ExpressionFunction] add components of mu to locals

- src/pymor/analyticalproblems/burgers.py
- src/pymor/functions/basic.py
- src/pymordemos/elliptic_oned.py
- src/pymordemos/elliptic_unstructured.py
- reshape evaluations if possible instead of failing (e.g.
shape_range=(1,) vs. shape_range=())
- rename locals_ parameter to values
- inject values into global namespace to make them available inside
lambdas
- add 'norm' and 'polar' functions
> [functions] some improvements to ExpressionFunction/GenericFunction

- src/pymor/analyticalproblems/elliptic.py
- src/pymor/analyticalproblems/helmholtz.py
- src/pymor/analyticalproblems/thermalblock.py
- src/pymor/discretizers/elliptic.py
- src/pymordemos/elliptic.py
- src/pymordemos/elliptic2.py
- src/pymordemos/elliptic_oned.py
- src/pymordemos/elliptic_unstructured.py
- src/pymordemos/parabolic.py
- src/pymordemos/parabolic_mor.py
- src/pymordemos/thermalblock_adaptive.py
- src/pymortests/fixtures/analyticalproblem.py
- src/pymortests/gui.py
> [analyticalproblems] use LincombFunction to represent affine decompositions

- src/pymor/discretizations/iosys.py
- src/pymor/reductors/bt.py
- src/pymordemos/heat.py
- src/pymorexamples/heat.ipynb
This pull request replaces the hand-rolled caching in `InputOutputSystem` and subclasses by pyMOR's caching infrastructure. Not only is the code simplified, the change also makes it easier to ensure that the semantics of `ImmutableInterface` are fulfilled by these classes. (E.g., in the old implementation, the `_gramian` dict did not keep track of the `me_solver`. So if `compute_gramian` was called before calling `compue_sv_U_V`, the `me_solver` parameter of the latter method would have had no effect.)
Some remarks:
- I have defaulted the `cache_region` to `memory` to reproduce the old behavior.
- For the Hinf-norm computation `fpeak` is now returned along with the norm. If this is unwanted, alternatives would be to drop the `fpeak` value or have an optional parameter to the `norm` method …
> [iosys] use caching in discretizations

- pytest.ini
- requirements-optional.txt
- requirements.txt
- setup.cfg
IIRC we held off on this due to
restricting ourselves to py.test >= 2.7.
This should be fine now woth py.test
already at 2.9.
> merge pytest.ini into setup.cfg

- src/pymor/grids/boundaryinfos.py
This bug is fixed in master, it would be great to also have it fixed in 0.4.x
> [grids] bugfix for boundary handling in subgrid

- src/pymor/operators/constructions.py
- src/pymor/vectorarrays/block.py
`ProxyOperator` can be used as a base class for other operators which mainly pass interface calls to a wrapped Operator.
> [operators] add ProxyOperator

- docs/source/substitutions.py
- docs/source/technical_overview.rst
- src/pymor/algorithms/image.py
- src/pymor/algorithms/preassemble.py
- src/pymor/algorithms/projection.py
- src/pymor/algorithms/rules.py
- src/pymor/algorithms/to_matrix.py
- src/pymor/basic.py
- src/pymor/core/defaults.py
- src/pymor/core/exceptions.py
- src/pymor/core/interfaces.py
- src/pymor/discretizations/basic.py
- src/pymor/discretizers/cg.py
- src/pymor/discretizers/fv.py
- src/pymor/operators/basic.py
- src/pymor/operators/constructions.py
- src/pymor/operators/ei.py
- src/pymor/operators/interfaces.py
- src/pymor/operators/numpy.py
- src/pymor/reductors/basic.py
- src/pymor/reductors/residual.py
- src/pymor/tools/table.py
- src/pymordemos/burgers_ei.py
- src/pymordemos/elliptic2.py
- src/pymortests/operators.py
This addresses #274 and #262. Documentation is still missing, but the overall concept is there. @pymor/pymor-devs, @andreasbuhr, please take a close look if you like the design. (Note that it is still impossible to dynamically add rules to a RuleTable, etc.)
> Use RuleTables for algorithms on Operator hierarchies 

- src/pymor/operators/block.py
- src/pymor/operators/constructions.py
- src/pymor/operators/numpy.py
- src/pymor/vectorarrays/block.py
- src/pymor/vectorarrays/constructions.py
- src/pymor/vectorarrays/numpy.py
- src/pymortests/complex_values.py
This pull request is to enable automatic type promotion and correct handling of complex types. This is as discussed in #333, except unlike there, I decided not to include special handling when imaginary part is zero. The main reason is that I noticed that such conditions can be handled in "higher-level" functions (e.g. reductors). Also, it just seems like too much work to do it in all "lower-level" function (e.g. operator and vectorarray methods)...
So far, I only made some changes in `vectorarrays` and `operators`. @pymor/pymor-devs @andreasbuhr, please check the changes, and see if additional changes are necessary.
Besides `vectorarrays` and `operators`, I noticed one thing in `algorithms` which should be changed. In [line 341 in …
> Type promotion

- src/pymor/core/config.py
- src/pymor/discretizers/cg.py
- src/pymor/discretizers/fv.py
- src/pymor/gui/jupyter.py
- src/pymor/gui/matplotlib.py
- src/pymor/gui/qt.py
- src/pymor/gui/visualizers.py
- src/pymordemos/minimal_cpp_demo/demo.py
This pull request adds a matplotlib-based patch visualizer for the jupyter notebook. Performance is relatively bad, but it should be usable enough for tutorial notebooks, etc. @pymor/pymor-devs, please check if this works on your machines. (For testing, you should say `%matplotlib notebook` before using pyMOR.)
> Add basic support for visualization in juypter notebooks

- src/pymor/functions/bitmap.py
Non-grayscale images are now automatically converted to grayscale. Also, we no longer use `img.rawdata`, which has been failing for some images.
@andreasbuhr, if you are currently actively using `BitmapFunction`, could you see if these changes work for you?
> Let BitmapFunction accept non-grayscale images

- README.md
- README.txt
- debian/README.source
- debian/control
- debian/python-pymor-demos.install
- debian/python-pymor-doc.docs
- debian/python-pymor.install
- debian/python3-pymor-demos.install
- debian/python3-pymor-demos.lintian-overrides
- debian/python3-pymor.install
- debian/rules
- setup.cfg
- versioneer.py
Switch all packages to use python 3 only. I dropped python 2 because I wasn't able to reliably delay the lib3to2 source transformation until the entire python 3 build was complete. This resulted in transformed sources being installed into the python 3 dirs, which resulted in an unusable installation.
> Switch debianization to python 3

- .ci/travis/run_travis_builders.py
- .ci/travis/script.bash
- dependencies.py
- setup.py
In theory you can now do 
```
pip install git+https://github.com/pymor/pymor@setup_extras#egg=pymor[full]
```
in practice this has problems with Qt. As in either it fails the install because pip cannot locate a wheel for pyside, or it might only install Qt.py but not PyQt. It's weird. This'll be tricky to impossible to solve because:
- no environment specifiers or wheel URI etc are allowed in extras (or install_requires, etc.)
- this is considered 'good': https://caremad.io/posts/2013/07/setup-vs-requirement/
- https://www.python.org/dev/peps/pep-0426/ is _still_ in draft
- whether setuptools' dependency_links feature is used in any given install scenario is unclear (and probably too brittle to use anyway)
Ideas welcome.
> Setup extras

- src/pymor/algorithms/to_matrix.py
- src/pymortests/to_matrix.py
Changes:
- `format=None` now does automatic format decision and `format='dense'` forces dense format
- `getattr` is used instead of the `mapping` dictionary
- `to_matrix` test is more extensive
> Add automatic format option in to_matrix

- src/pymor/analyticalproblems/text.py
- src/pymor/basic.py
- src/pymordemos/thermalblock_simple.py
- src/pymortests/demos.py
and hook it up in thermalblock_simple demo
> [analyticalproblems] add text_problem

- dependencies.py
- requirements.txt
- src/pymor/tools/mpi.py
> Support mpi4py > 2.0

- src/pymor/bindings/scipy.py
- src/pymor/core/config.py
- src/pymor/vectorarrays/interfaces.py
also, remove FEniCS version warning. (Until now, we didn't
have any issues with newer FEniCS versions breaking things.)
> use packaging.version to improve version handling

- docs/source/technical_overview.rst
- src/pymor/algorithms/ei.py
- src/pymor/algorithms/genericsolvers.py
- src/pymor/algorithms/projection.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/operators/constructions.py
- src/pymor/operators/ei.py
- src/pymor/operators/interfaces.py
- src/pymor/vectorarrays/block.py
- src/pymor/vectorarrays/interfaces.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/mpi.py
- src/pymor/vectorarrays/numpy.py
- src/pymordemos/minimal_cpp_demo/wrapper.py
- src/pymortests/operators.py
- src/pymortests/to_matrix.py
- src/pymortests/vectorarray.py
`components` always was a slightly awkward name. Moreover, we want to use `component` in the future to extract `VectorArrays` associated with subspaces of a given system `VectorSpace`.
> [VectorArrays] rename VectorInterface.components -> VectorInterface.dofs

- .ci/travis/deploy.bash
- setup.cfg
- versioneer.py
See https://wheels.pymor.org/branches/wheel_versioning/index.html
Non-release/tag wheels names now carry an epoch version to make them newer than everything else, as far as pip is concerned. To make this work with branches, wheels.pymor.org now has an index per branch dir instead of listing everything on the root index. 
I've also dropped the 'dirty' suffix from the local version part because every wheel will now de birty due to me changing the versioning routine in setup.cfg in the deploy step. I thought doing that change explicitly this way instead of having it being controlled via an environment variable setting was somewhat safer.
> Build wheels that can install without --pre

- notebooks/heat.ipynb
- src/pymor/discretizations/iosys.py
- src/pymor/reductors/bt.py
- src/pymordemos/heat.py
This PR moves LQG and BR Gramians from `LTISystem` to reductors. Thus:
- `LTISystem.gramian` only computes standard (Lyapunov) Gramians,
- `solver_options` in `LTISystem` now only refers to the Lyapunov equations,
- `LQGBTReductor` and `BRBTReductor` have their own `solver_options` for LQG/BR Riccati equations,
- `BTReductor` still uses `LTISystem.gramian`.
Additionally:
- `notebook/heat.ipynb` now also demonstrates LQGBT and BRBT,
- `LTISystem.sv_U_V` was replaced by `LTISystem._hsv_U_V`, `LTISystem.hsv`, `LTISystem.hsU`, and `LTISystem.hsV`, since now it only computes Hankel singular values and vectors,
- `LTISystem.hsv`, `LTISystem.hsU`, and `LTISystem.hsV` are a properties for ease of use.
> [sys-mor] moving Gramians from LTISystem to reductors

- src/pymor/operators/cg.py
1st order integration for boundary integrals in operators.cg was broken.
All dimensions of size 1 of the array of shape functions, evaluated at integration points, were removed using "np.squeeze". This works fine as long as there is more than one integration point. When you integrate first order, there is only one integration point and the dimension for the integration point number is removed from the array.
Then "np.einsum" failed because it expected to have a dimension for the integration point number.
> [operators.cg] fix first order integration

- src/pymor/parameters/base.py
- src/pymor/parameters/spaces.py
Iterating over a `ParameterTypes` is now always ordered. In particular, the order of Parameters is `CubicParameterSpace.sample_uniformly` is now deterministic.
> [ParameterType] base implementation on OrderedDict

- src/pymor/algorithms/error.py
- src/pymor/algorithms/projection.py
- src/pymor/algorithms/to_matrix.py
- src/pymor/bindings/pyamg.py
- src/pymor/bindings/scipy.py
- src/pymor/discretizers/disk.py
- src/pymor/operators/numpy.py
- src/pymor/playground/discretizers/numpylistvectorarray.py
- src/pymor/playground/operators/numpy.py
- src/pymor/reductors/coercive.py
- src/pymortests/complex_values.py
- src/pymortests/fixtures/operator.py
Subclasses of `ImmutableInterface` should have equally-named attributes for their `__init__` attributes. Otherwise a custom `with_` implementation is needed. (Right now, `NumpyMatrixOperator._with` is broken.) Also, you often need access to the `matrix` attribute in interactive work, and tab completion will not show private attributes.
Any objections, @pymor/pymor-devs?
> [NumpyMatrixOperator] rename '_matrix' attribute to 'matrix'

- src/pymor/operators/constructions.py
and 'apply_inverse_transpose' for the special case of len(self.operators) == 1.
See discussion in #272.
> [LincombOperator] implement 'apply_inverse' 

- src/pymor/operators/basic.py
- src/pymor/operators/constructions.py
These are the fixes from #433 which can be applied to master.
> Fix VectorArrayOperator, generalize as_range/source_array

- src/pymor/vectorarrays/block.py
- src/pymor/vectorarrays/interfaces.py
- src/pymor/vectorarrays/numpy.py
> Add conj method for vectorarrays

- notebooks/string.ipynb
- src/pymor/discretizations/iosys.py
- src/pymor/operators/block.py
- src/pymor/reductors/basic.py
- src/pymor/reductors/bt.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/lti.py
- src/pymor/reductors/sobt.py
- src/pymor/reductors/sor_irka.py
New reductors:
- `SOBT`, `SOBTp`, `SOBTv`, `SOBTpv`, `SOBTvp`, `SOBTfv` (balancing-related reductors for second order systems)
- `SOR-IRKA` (`IRKA`-inspired reductor for second order systems, the version where the intermediate reductor is `IRKA`)
Demo:
- Jupyter notebook `string.ipynb` demonstrating the above methods
Misc:
- added `SecondOrderOperator` and `ShiftedSecondOrderOperator` such that the generic solver (LGMRES) is not used
- fixed a few bugs in `VectorArrayOperator`
- made `GenericRBReductor` and `GenericPGReductor` more similar concerning `orthogonal_product`
- made `as_source_array` and `as_range_array` for `VectorArrayOperator` work for vectorarrays from `BlockVectorSpace`
> Balancing and interpolation related reductors for SecondOrderSystems

- .ci/travis/travis.yml
Without this fix, builds on travis are not started due to the invalid condition "type IS push". According to [this document](https://docs.travis-ci.com/user/conditions-v1) it has to be "type = push".
@renemilk, you may want to take a look, but I will merge now to get travis running again.
> [travis] fix deploy stage check

- src/pymor/operators/basic.py
- src/pymor/operators/constructions.py
> [operators] Improve subtraction of LincombOperators

- src/pymor/algorithms/projection.py
> [project] ensure solver_options are removed from projected operators

- src/pymor/algorithms/to_matrix.py
- src/pymor/discretizations/iosys.py
- src/pymor/operators/block.py
- src/pymor/reductors/sor_irka.py
- src/pymortests/block.py
- src/pymortests/fixtures/operator.py
Fixes #485. Should also simplify the situation for #478.
> [operators.block] add BlockRowOperator, BlockColumnOperator

- src/pymor/analyticalproblems/elliptic.py
- src/pymor/discretizers/cg.py
- src/pymor/discretizers/fv.py
- src/pymor/functions/basic.py
- src/pymor/grids/interfaces.py
- src/pymor/operators/cg.py
- src/pymor/operators/numpy.py
- src/pymortests/function.py
This PR adds support for assembling arbitrary l2 output functionals (on the interior or the boundary) for cg discretizations:
- `InstationaryProblem` gets an additional `functionals` attribute to specify output functionals.
- Assembly of these functionals is only implemented for CG. FV is still missing.
- In `pymor.operators.cg`, the boundary treatment is moved to `BoundaryL2ProductFunctionalP/Q1` which handles the assembly of dirichlet / neumann or arbitrary boundary l2 functionals. `BoundaryDirichletFunctional` is used for enforcing dirichlet constraints.
Additionally:
- A small fix for `NumpyMatrixBasedOperator.H`.
- `Functions` can now be multiplied, yielding a `ProductFunction`.
> Output functionals in CG discretizations

- src/pymor-demo
Without this fix I am getting the following warning on Python 3.5:
```
/usr/lib/python3.5/runpy.py:125: RuntimeWarning: 'pymordemos.thermalblock' found in sys.modules after import of package 'pymordemos', but prior to execution of 'pymordemos.thermalblock'; this may result in unpredictable behaviour
warn(RuntimeWarning(msg))
```
> [pymor-demo] prevent RuntimeWarning due to already loaded module

- .ci/travis/deploy.bash
- setup.cfg
This makes pymor use the PEP440 scheme for building releases from git tags
and our custom epoch+tag-distance for other push builds.
> Rewire versioning scheme

- versioneer.py
Before the fix:
```bash
$ flake8 | grep W605
./versioneer.py:941:-13592: W605 invalid escape sequence '\s'
./versioneer.py:941:-13408: W605 invalid escape sequence '\s'
./versioneer.py:941:-13228: W605 invalid escape sequence '\s'
./versioneer.py:941:-11196: W605 invalid escape sequence '\d'
./versioneer.py:941:-8162: W605 invalid escape sequence '\d'
./src/pymor/core/logger.py:97:14: W605 invalid escape sequence '\-'
./src/pymor/core/logger.py:104:22: W605 invalid escape sequence '\ '
./src/pymor/grids/tria.py:48:-1615: W605 invalid escape sequence '\ '
./src/pymor/grids/tria.py:48:-1593: W605 invalid escape sequence '\ '
./src/pymor/grids/tria.py:48:-1483: W605 invalid escape sequence '\ '
./src/pymor/grids/tria.py:48:-1461: W605 invalid escape sequence '\ ' …
```
> Fixing flake8 W605

- src/pymor/reductors/residual.py
This fixes residual computation in `NonProjectedResidualOperator` as in #566.
Addresses #555.
> Fix NonProjectedResidualOperator.apply

- src/pymor/algorithms/image.py
- src/pymor/reductors/residual.py
fix two bugs:
Riesz representative calculation was broken in NonProjectedResidualOperator if the residual was zero. This resulted in a division by zero and thereby nan entries.
estimate_image was broken for an adjoint of a concatenation operator.
Both fixed here.
> Residual bugfix [0.4.x]

- setup.cfg
- src/pymor/discretizers/fv.py
Fixes #564.
- ignores pycodestyle errors `E731` and `E741`
- sets `max-doc-line` to 100
- replaces pep8 section with pycodestyle
- removes `nonlinear_advection_upwind_operator`
> Fixes for #564

- src/pymor/algorithms/gram_schmidt.py
- src/pymortests/algorithms/gram_schmidt.py
Closes #491.
- adds an option to compute the R matrix
- some improvements (no more flake8 issues with `old_norm`)
- adds unit tests
> Gram-Schmidt with R

- notebooks/heat.ipynb
- notebooks/string.ipynb
- src/pymor/models/iosys.py
- src/pymor/reductors/bt.py
- src/pymor/reductors/h2.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/sobt.py
- src/pymor/reductors/sor_irka.py
- src/pymordemos/delay.py
- src/pymordemos/heat.py
- src/pymordemos/string_equation.py
Renaming is as follows:
- `n` -> `order`
- `m` -> `input_dim`
- `p` -> `output_dim`
Other suggestions are welcome. `order` is used in places related to quadrature. Maybe shortening `input_dim` and `output_dim` would be good, e.g., `in_dim` and `out_dim`. Or replacing `input_dim` and `output_dim` with an attribute `shape = (m.output_space.dim, m.input_space.dim)`.
> Rename system attributes n, m, p

- src/pymor/algorithms/rules.py
by exploiting the fact that the class attribute definition order is preserved in Python 3.6 and greater.
Fixes #543.
> Simply implementation of RuleTable

- notebooks/heat.ipynb
- notebooks/string.ipynb
- src/pymor/models/iosys.py
- src/pymor/reductors/interpolation.py
- src/pymordemos/delay.py
- src/pymordemos/string_equation.py
This moves the generic `__add__`, `__neg__` and `__sub__` from `InputStateOutputModel` to `LTIModel`, `TransferFunction`, and `SecondOrderModel`. (Those should be added to other system classes after resolving #580.)
The motivation was to allow, e.g. `lti + tf` and `lti + so`, without making `InputStateOutputModel` even more convoluted. As a benefit, this removes the requirement that the `input_space`, `state_space` and `output_space` are different. There is quite some code repetition, which I'm not sure how to remove in a nice way.
The `__sub__` now does not depend on `__neg__` so that it can check if the two `D` operators are the same. (It is good for `fom - rom` to have the explicit zero `D` term when `rom` is obtained from `fom` by projection.)
This PR also adds `__mul__` to …
> Moving arithmetic operators from InputStateOutputModel

- notebooks/delay.ipynb
- src/pymor/algorithms/ei.py
- src/pymor/algorithms/error.py
- src/pymor/basic.py
- src/pymor/discretizers/cg.py
- src/pymor/models/basic.py
- src/pymor/models/interfaces.py
- src/pymor/models/iosys.py
- src/pymor/models/mpi.py
- src/pymor/reductors/basic.py
- src/pymor/reductors/bt.py
- src/pymor/reductors/coercive.py
- src/pymor/reductors/h2.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/parabolic.py
- src/pymor/reductors/sobt.py
- src/pymordemos/analyze_pickle.py
- src/pymordemos/burgers_ei.py
- src/pymordemos/parabolic_mor.py
- src/pymordemos/thermalblock.py
- src/pymordemos/thermalblock_simple.py
This is non-functional code to give the @pymor/pymor-devs an idea of what I have in mind for the future Reductor design. It's probably more helpful to look at the new `reductors/basic.py` instead of looking at the diff. Comments welcome ..
As you can see, I have decided to completely remove the projection code from the base class. My impression was that there were too many corner cases to take care of and it might be clearer to explicitly write down the projections.
Fixes #587 when finished.
> Simplify Reductors and Models

- src/pymor/models/basic.py
- src/pymor/models/iosys.py
As suggested in #609, I have removed most `VectorSpace` id code from `models.iosys`. What remains is the ability to assign space ids when loading matrices from disk.
> [models.iosys] remove space id handling except for factory methods

- .ci/azure/pipeline-osx.yml
- src/pymor/algorithms/projection.py
- src/pymor/models/iosys.py
- src/pymor/operators/basic.py
- src/pymor/operators/ei.py
- src/pymor/reductors/basic.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/sobt.py
- src/pymordemos/delay.py
As discussed in #609. Also, since some sys-mor reductors used `from_matrices` and now ids are removed when projecting, I decided to also remove the `input_id` and `output_id` parameters from the iosys factory methods (which defaulted to `'INPUT'` and `'OUTPUT'`) as they felt somewhat less useful than `state_id`. (ATM, all models coming from pyMOR's discretizations have `'STATE'` as state space id.)
> Remove VectorSpace id handling from projection methods

- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/reductors/h2.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/sor_irka.py
- src/pymor/vectorarrays/interfaces.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/numpy.py
- src/pymortests/vectorarray.py
As discussed in #544. 
Note that I decided to let `value` be the first argument in `full` since `count` is an optional argument in `zeros`, `ones` and `empty`. Unfortunately, it's the other way around for `numpy.full`. However, I believe it is still better to keep the interface in pyMOR consistent.
> Implement VectorArrayInterface.ones and VectorArrayInterface.full

- src/pymor/operators/block.py
- src/pymor/vectorarrays/block.py
This removes the feature to specify a id for `BlockVectorSpaces`. The rationale is that we no longer need ids for the reduction process and a `BlockVectorSpace` should usually be uniquely determined by the ids of its subspaces.
See #609.
> Remove id from BlockVectorSpace

- src/pymor/algorithms/timestepping.py
- src/pymor/operators/interfaces.py
- src/pymor/vectorarrays/interfaces.py
- src/pymor/vectorarrays/numpy.py
By requiring that `VectorArrays` representing the real/complex numbers should have no space id, the `space` parameter from `OperatorInterface.as_vector` becomes obsolete. This also means that there is one and only one `VectorSpace` representing real/complex numbers, namely `NumpyVectorSpace(1)`.
See #609.
> Remove 'space' parameter from as_vector

- notebooks/heat.ipynb
This fixes the bug in `heat.ipynb` with setting `input_id` and `output_id` in `rom0` for TSIA, removes setting `state_id` in the same, and shows results of TSIA similar to other reductors.
Related to #609.
> Fixes and improvements in heat.ipynb

- src/pymor/bindings/fenics.py
- src/pymor/vectorarrays/interfaces.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/numpy.py
- src/pymortests/vectorarray.py
As discussed in #544, this adds a `random` method to `VectorArrayInterface`. It has a default implementation for all backends that implement `from_numpy`. The exact signature is
```python
def random(self, count=1, distribution='uniform', random_state=None, seed=None,
reserve=0, **kwargs):
```
where `kwargs` are additional parameters depending on `distribution`. The names of these parameters are chosen to agree with the parameters of the respective NumPy methods.
`random_state` and `seed` behave as for `CubicParameterSpace.sample_randomly`: either a (mutable) [NumPy RandomState](https://www.numpy.org/devdocs/reference/generated/numpy.random.RandomState.html) can be provided which is then used to sample random numbers, or a `seed` from which a new `RandomState` is initialized. If neither …
> Add 'random' method to VectorArrayInterface

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
These are auto-deleted after 6 months.
This should help with failures like https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/82828 since you can just download the `*changed` files in an archive afterwards.
> [ci] upload test logs and new check results

- src/pymor/operators/block.py
> Fix as_source_array/as_range_array for BlockRowOperator/BlockColumnOperator

- src/pymor/algorithms/lradi.py
- src/pymor/reductors/h2.py
- src/pymor/reductors/sor_irka.py
@pmli, I am wondering: Now that the interface supports it, would it maybe be better to always initialize with random values? Should the user always have to specify a seed? Also, is there mathematical reason why the normal distribution is chosen over a uniform distribution?
This is the remaining step to implement #544.
> Use VectorArrayInterface.random where possible

- docs/source/technical_overview.rst
- src/pymor/algorithms/lincomb.py
- src/pymor/algorithms/rules.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/operators/block.py
- src/pymor/operators/constructions.py
- src/pymor/operators/interfaces.py
- src/pymor/operators/mpi.py
- src/pymor/operators/numpy.py
- src/pymor/playground/operators/numpy.py
- src/pymortests/complex_values.py
- src/pymortests/operators.py
This moves all `assemble_lincomb` methods for generic `Operators` into `pymor.algorithms.lincomb`. The `RuleTable` also takes care of eliminating `ZeroOperators`. ATM, the backends still need to handle `IdentitiyOperators`. Before merging, this issue should be resolved (e.g. by introducing a `ShiftedOperator` and `apply_inverse_shifted` interface methods or a separate argument to `_assemble_lincomb`).
This addresses #548.
> Move all backend-agnostic assemble_lincomb logic to algorithms.lincomb

- src/pymor/algorithms/lradi.py
As requested by @pmli this is another PR for removing the `z_columns` and `implicit_subspace` options for the low-rank ADI iteration. The actual improvements will then be part of #634 .
> [algorithms.lradi] Remove options for ADI iteration shift parameters

- notebooks/delay.ipynb
- src/pymor/models/iosys.py
- src/pymor/reductors/interpolation.py
Closes #645.
`InputStateOutputModel` looks a bit weird without `state_space`, but maybe we can change it somehow later.
> Remove state_space in input-output system classes

- docs/source/substitutions.py
- src/pymor/models/iosys.py
- src/pymor/reductors/basic.py
- src/pymor/vectorarrays/interfaces.py
This adds and fixes some substitutions and fixes an issue with the `Parameter` section.
There is still the issue of `release_notes.rst` using system and discretization substitutions.
> Sphinx warning fixes

- src/pymor/models/iosys.py
- src/pymor/reductors/bt.py
Some changes to API which should improve things:
- turn some methods in `reductors.bt` private, to show that only `reduce` and `error_bounds` should be used
- remove `hsU` and `hsV` methods from `LTIModel` since `hsv` is far more useful and it could be confused with `hsV`
- give `gamma` in `BRBTReductor` a default value 1, because "bounded real" means "H_inf-norm bounded by 1" in standard terminology
> sys-mor API changes

- notebooks/delay.ipynb
- notebooks/heat.ipynb
- notebooks/string.ipynb
- src/pymor/basic.py
- src/pymor/reductors/bt.py
- src/pymor/reductors/h2.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/sobt.py
- src/pymor/reductors/sor_irka.py
- src/pymordemos/delay.py
- src/pymordemos/heat.py
- src/pymordemos/string_equation.py
- removes `reduce_arnoldi` from `LTI_BHIReductor`, merges `use_arnoldi` option with `projection`
- initializes reductor attributes in `__init__`
- makes `pg_redutor` a private attribute
- sets reduced `D` operator in `SOBTReductor`
- renames `TFInterpReductor` to `TF_BHIReductor` to fit with other "BHI" reductors
- docs and other minor improvements
> [sys-mor] various reductor improvements

- notebooks/heat.ipynb
- src/pymor/models/iosys.py
Adds `TransferFunction.h2_norm`, using `scipy.integrate.quad`.
> Transfer function h2_norm

- .ci/azure/pipeline-osx.yml
- .ci/azure/pipeline-win.yml
- dependencies.py
- requirements-optional.txt
Basically sometime between 
https://dev.azure.com/pymor/pymor/_build/results?buildId=487
and 
https://dev.azure.com/pymor/pymor/_build/results?buildId=490
the conda setup on OSX just broke. Now updating packages in the env is stalling forever/the python interpreter is missing, depending on if I update conda or not. As a short time workaround I will remove the branch protection requirement for the OSX builds. Other open PRs should still rebase on master after I merge this PR to have OSX fail inside of 20 minutes instead of 2 hours per build.
> Not actually a Azure OSX fix

- src/pymor/algorithms/gram_schmidt.py
Example:
```
from pymor.basic import *
v = NumpyVectorSpace(3).random(3, seed=0)+1j*NumpyVectorSpace(3).random(3, seed=1)
print(gram_schmidt(v,return_R=True)[1])
```
Output:
```
array([[1.36703713, 0.89474946, 1.30606313],
[0.        , 0.43790411, 0.42856623],
[0.        , 0.        , 0.49438602]])
```
Output should be:
```
array([[1.36703713+0.j    , 0.89474946-0.15063988j,   1.30606313-0.17295746j],
[0.        +0.j    , 0.43790411+0.j        ,    0.42856623+0.25122766j],
[0.        +0.j    , 0.        +0.j        ,        0.49438602+0.j        ]])
```
In line 87 in `R[j, i] += p` the complex valued `p` is casted to float. 
I suggest to replace line 62: `R = np.eye(len(A))`
by `R = np.eye(len(A), dtype=A.data.dtype)`.
> Gram_schmidt algorithm discards complex values in the R matrix. 

- AUTHORS.md
- dependencies.py
- docs/source/bibliography.rst
- requirements-optional.txt
- src/pymor/algorithms/randrangefinder.py
- src/pymortests/randrangefinder.py
I added randomized range finder algorithms: one adaptive algorithm and one with power iterations.
> adding randomized algorithms

- src/pymor/discretizers/cg.py
- src/pymor/operators/cg.py
Currently discretizing a problem with a robin boundary condition on a RectGrid raises a NotImplementedError. Replacing `NI = bi.neumann_boundaries(1)` in line 310 in operators.cg with `NI = bi.boundaries(self.boundary_type, 1) if self.boundary_type else g.boundaries(1)` as in line 136 worked as a fix for me. 
Since then `BoundaryL2ProductFunctionalP1` and `BoundaryL2ProductFunctionalQ1` are basically the same, it might be an idea to have just one `BoundaryL2ProductFunctional`. 
Example:
```
from pymor.basic import *
from pymor.grids.rect import RectGrid
p = StationaryProblem(domain=RectDomain(bottom='robin'),
diffusion=ConstantFunction(1, dim_domain=domain.dim),
robin_data=(ConstantFunction(1, dim_domain=domain.dim), ConstantFunction(1, dim_domain=domain.dim))
)
d,data = …
```
> Discretizing robin boundary conditions on a RectGrid

- src/pymor/algorithms/lincomb.py
- src/pymor/operators/numpy.py
- src/pymortests/operators.py
- adds a test to `pymortests.operators`
- fixes the issue in `algorithms.lincomb`
> Fix lincomb of IdentityOperator and NumpyMatrixOperator

- src/pymor/discretizers/cg.py
- src/pymor/operators/cg.py
This PR simplifies the implementation in `operators.cg` by removing the optional integration `order` arguments from all `Operators`. All data functions are now evaluated at the entity centers, corresponding to the mid-point integration rule. For the implemented first-order schemes this should be sufficient (assuming regularity of the coefficient functions).
For discontinuous diffusion tensors, it is now in particular clear, that these are approximated by entity-wise constant functions (given by evaluation at the entity centers).
> Remove 'order' arguments from CG operators

- src/pymor/algorithms/lincomb.py
- src/pymor/algorithms/projection.py
- src/pymor/algorithms/to_matrix.py
- src/pymor/basic.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/core/interfaces.py
- src/pymor/domaindiscretizers/default.py
- src/pymor/functions/basic.py
- src/pymor/functions/bitmap.py
- src/pymor/grids/boundaryinfos.py
- src/pymor/grids/gmsh.py
- src/pymor/grids/interfaces.py
- src/pymor/grids/oned.py
- src/pymor/grids/subgrid.py
- src/pymor/grids/unstructured.py
- src/pymor/gui/matplotlib.py
- src/pymor/models/iosys.py
- src/pymor/operators/block.py
- src/pymor/operators/cg.py
- src/pymor/operators/constructions.py
- src/pymor/operators/ei.py
- src/pymor/operators/fv.py
- src/pymor/operators/mpi.py
- src/pymor/operators/numpy.py
- src/pymor/parameters/functionals.py
- src/pymor/parameters/spaces.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/numpy.py
- src/pymortests/fixtures/grid.py
This rather large PR adds some code to `ImmutableMeta.__call__` which checks if all `__init__` arguments of an immutable class are available as attributes of the generated object. This is necessary for `with_` to work correctly.
All other commits in this PR fix various classes for which this condition is not satisfied. In some cases some attributes are renamed (from _foo to foo) and many missing attributes are added. Some refactoring happened along the way:
- `UnstructuredTriangleGrid` now has a factory method `from_vertices` which will be usually used to instantiate the grid.
- `GmshGrid` has been removed. Instead an `UnstructuredTriangleGrid` is instantiated directly.
- `BoundaryInfoFromIndicators` is now `GenericBoundaryInfo` with a `from_indicators` factory method.
- …
> Ensure that with_ works for all immutable objects

- src/pymor/models/basic.py
(Part of the changes from #652)
Since `rhs` and `mass` are asserted to be linear, it should be enough to add `self.linear = operator.linear`.
> Add 'linear' attribute to StationaryModel and InstationaryModel

- notebooks/parametric_delay.ipynb
- notebooks/parametric_heat.ipynb
- notebooks/parametric_string.ipynb
- notebooks/parametric_synthetic.ipynb
- src/pymor/algorithms/lradi.py
- src/pymor/algorithms/lyapunov.py
- src/pymor/algorithms/riccati.py
- src/pymor/bindings/pymess.py
- src/pymor/bindings/scipy.py
- src/pymor/bindings/slycot.py
- src/pymor/models/basic.py
- src/pymor/models/iosys.py
- src/pymor/reductors/bt.py
- src/pymor/reductors/h2.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/sobt.py
- src/pymor/reductors/sor_irka.py
Closes #487.
This is not yet ready to merge, so I'm testing the draft pull request feature.
I would like to hear comments from @pymor/pymor-devs about the changes concerning the usage of parameters, e.g. how often should `parse_parameters` be used and should matrix equation solvers expect a parameter or only work with non-parametric operators.
> Parameterizing input-output models

- src/pymor/core/interfaces.py
- src/pymor/functions/basic.py
- src/pymor/grids/oned.py
- src/pymor/grids/rect.py
- src/pymor/grids/tria.py
- src/pymor/operators/numpy.py
- src/pymor/parameters/functionals.py
- src/pymor/parameters/spaces.py
- src/pymor/tools/formatrepr.py
- src/pymor/vectorarrays/interfaces.py
- src/pymor/vectorarrays/numpy.py
In view of #392, #652 and the `__repr__` implementation [here](https://github.com/pymor/pymor/pull/652/files#diff-316acb549dbd98b6e3ec9b278a6f2a06R31), I decided to try to implement a generic `__repr__` for all `BasicInterface` instances.
While the code surely needs refactoring and leave a lot of room for improvements, I quite like the result as a baseline. E.g.
```python
from pymor.basic import *
p = thermal_block_problem()
m, _ = discretize_stationary_cg(p)
print(repr(p))
print()
print(repr(m))
```
yields
```
StationaryProblem(
RectDomain(domain=array([[0, 0], [1, 1]])),
rhs=ConstantFunction(dim_domain=2),
diffusion=LincombFunction(
[ExpressionFunction(
'(x[..., 0] >= ix * dx) * (x[..., 0] < (ix + 1) * dx) * (x[..., 1] >= iy * dy) * (x[..., 1] < (iy + 1) * dy) * 1.',
dim_domain=2, …
```
> Add generic __repr__ method to BasicInterface

- src/pymor/algorithms/lincomb.py
- src/pymortests/operators.py
The issue seems to be entirely due to using a list instead of a tuple.
> Fix block identity assemble lincomb

- notebooks/delay.ipynb
- notebooks/heat.ipynb
- notebooks/string.ipynb
- src/pymor/models/basic.py
- src/pymor/models/iosys.py
- src/pymor/tools/formatrepr.py
This includes some basic `__repr__` and `__str__` methods for models. Comments are welcome.
Closes #392.
> __repr__ and __str__ for models

- notebooks/delay.ipynb
- notebooks/heat.ipynb
- notebooks/parametric_delay.ipynb
- notebooks/parametric_heat.ipynb
- notebooks/parametric_string.ipynb
- notebooks/parametric_synthetic.ipynb
- notebooks/string.ipynb
- src/pymor/models/iosys.py
- src/pymordemos/delay.py
- src/pymordemos/heat.py
- src/pymordemos/string_equation.py
Based on return values of
- Matlab's [`bode`](https://www.mathworks.com/help/control/ref/bode.html),
- Matlab's [`freqresp`](https://www.mathworks.com/help/control/ref/freqresp.html),
- [`scipy.signal.bode`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.bode.html),
- [`scipy.signal.freqresp`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.freqresp.html),
and
- Matlab's frequency response [definition](https://www.mathworks.com/help/control/ref/freqresp.html#btcn_7u)
a better name for [`pymor.models.iosys.InputOutputModel.bode`](https://github.com/pymor/pymor/blob/6fa6e21d49712469b5aa9d7a99dc87b6cfc959fc/src/pymor/models/iosys.py#L60) would be `freqresp` ([python-control's `freqresp`](https://python-control.readthedocs.io/en/0.8.2/generated/control.freq …
> Rename bode and Bode plot

- docs/source/bibliography.rst
- src/pymor/algorithms/lrradi.py
- src/pymor/algorithms/riccati.py
- src/pymortests/riccati.py
This is an implementation of the low-rank RADI algorithm mentioned in #692. One issue I encountered was that the other solvers can be applied to equations of the type  `AXE^T+EXA^T-(EXC^T+S) R^{-1}(EXC^T+S)^T+BB^T=0`, whereas the RADI implementation can not deal with the matrices `S` and `R`. Since `LQGBTReductor` does not need `S` and `R` as well for solving Riccati equations, this should not be too big of an issue. But I'm not sure if my workaround in `riccati.py` is appropriate.
> Low-rank RADI solver for Riccati equations

- .ci/docker/install_checks/debian_stretch/Dockerfile
- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
- notebooks/delay.ipynb
- notebooks/heat.ipynb
- notebooks/parametric_heat.ipynb
- src/pymor/analyticalproblems/elliptic.py
- src/pymor/discretizers/cg.py
- src/pymor/discretizers/fv.py
- src/pymor/models/basic.py
- src/pymor/models/interfaces.py
- src/pymor/reductors/basic.py
- src/pymordemos/heat.py
This implements the proposal discussed in #698 and supersedes #698.
> Add notion of output to ModelInterface 2

- src/pymor/analyticalproblems/thermalblock.py
- src/pymor/parameters/functionals.py
- src/pymordemos/thermalblock.py
- src/pymordemos/thermalblock_simple.py
In https://github.com/pymor/pymor/pull/748, we discussed that `index` is a better name for a certain index of a parameter component than `coordinates`. Thus, we also change it in `ProjectionParameterFunctional`.
> Rename parameter coordinates to index

- AUTHORS.md
- src/pymor/operators/basic.py
- src/pymor/operators/constructions.py
- src/pymor/operators/interfaces.py
- src/pymor/parameters/functionals.py
- src/pymor/parameters/interfaces.py
- src/pymortests/mu_derivatives.py
This pull request adds a basic version of parameters derivatives to pymor. 
1. Parameters package:
- `ParameterFunctionalInterface` has now a `partial_derivative` method that returns a new `ParameterFunctional` representing the derivative to a specific component and coordinate of the parameter 
- For this pull request, it is only possible to differentiate `ProjectionParameterFunctional` and `ExpressionParameterFunctional`. For the latter the user has to provide a `dict` that contains all partial derivatives of the given Parameter. An assertion on the size of this dict might be useful. All shapes of parameters are possible ( scalar, vector and matrix) 
2. Operators package:
- I added a `mu_derivative` method to the `OperatorInterface` and thus also to `OperatorBase`. This method returns a …
> Add partial derivatives w.r.t. parameters

- src/pymor/tools/deprecated.py
- src/pymor/vectorarrays/interfaces.py
- use stacklevel=2 to actually display output when the deprecated method
is run from `__main__`
- improve deprecation message
> Fix Deprecated decorator and improve it's output

- AUTHORS.md
- src/pymor/discretizers/cg.py
This PR addresses #727. For now the discretizer does not decompose the rhs functional F and the diffusion part of the robin boundary data although LincombFunctions might be given. 
In this PR, the discretizer check for all inputs whether the input is a LincombFunction. If that's the case, the rhs functionals and robin operators in the model will also be decomposed now
> [discretizers.cg] affine decomposition of robin operator and rhs functionals

- src/pymor/operators/basic.py
- src/pymor/parameters/functionals.py
I pushed two small fixes.
One is only a typo.
The other is about ZeroOperator not being available in basic.py.
> Fix OperatorBase.d_mu

- src/pymor/algorithms/projection.py
By applying `product` to `range_basis` before applying `ProjectRules`, we don't need to pass the `product` everywhere.
> Simplify implementation of project

- src/pymor/algorithms/projection.py
- src/pymor/operators/basic.py
- src/pymortests/fixtures/operator.py
> Handle projection of parametric BlockOperators

- src/pymor/algorithms/greedy.py
- src/pymordemos/parabolic_mor.py
> Default to POD-Greedy for instationary problems

- src/pymor/algorithms/genericsolvers.py
- src/pymor/algorithms/gram_schmidt.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/operators/basic.py
- src/pymor/vectorarrays/list.py
- src/pymordemos/thermalblock_simple.py
- src/pymortests/algorithms/basic.py
- src/pymortests/algorithms/gram_schmidt.py
- src/pymortests/fixtures/vectorarray.py
- src/pymortests/vectorarray.py
This PR adds generic support for complex-valued VectorArrays for PDE solvers with `ListVectorArray`-based bindings. The construction is generic and does not require any complex number support within the PDE solver. The approach is similar to #747, but provides base classes for `Vectors` and `Operators` that can be used for arbitrary solver bindings.
Unlike #747, complex linear combinations are completely handled by `LincombOperator`. Should the need arise, an `assemble_lincomb` rule could be added, which separately assembles real and imaginary parts.
Moreover, this PR adds complex data to the `VectorArray` fixtures and fixes various complex number issues, both in the tests and the implementations.
I have tried to fix `lgmres`, but more testing / checking the code is required. The …
> Complex arithmetic for PDE solvers 2

- README.md
Makefile does not have the 'doc' target, but it does 'docs'.
Should this be backported to 0.5.x?
> [README] fix instructions for building docs

- dependencies.py
- requirements-optional.txt
- src/pymor/core/config.py
- src/pymor/core/exceptions.py
- src/pymor/domaindiscretizers/gmsh.py
- src/pymor/grids/gmsh.py
- src/pymortests/demos.py
> Use meshio for Gmsh file parsing

- src/pymor/algorithms/newton.py
- add relaxation parameter
- disable stagnation criterion by default
> Minor improvements to newton algorithm

- src/pymor/algorithms/timestepping.py
- src/pymor/models/basic.py
- src/pymor/reductors/parabolic.py
We allow `mass` to be `parametric` and depend on time.
Fixes #782.
> Make assumptions on mass Operator in InstationaryModel consistent

- src/pymor/operators/fv.py
This was a small bug that prevented fv from using parametric dirichlet.
> Enable to have parametric dirichlet in fv

- src/pymor/algorithms/lincomb.py
- src/pymor/algorithms/to_matrix.py
- src/pymor/operators/constructions.py
- src/pymortests/low_rank_op.py
- src/pymortests/to_matrix.py
So far, this adds `LowRankOperator` and `LowRankUpdatedOperator` to `operators.constructions`. The `LowRankUpdatedOperator` uses [Sherman-Morrison-Woodbury formula](https://en.wikipedia.org/wiki/Woodbury_matrix_identity) in `apply_inverse` and `apply_inverse_adjoint`.
The motivation for L M<sup>-1</sup> R<sup>H</sup> form of the low-rank operator is from Riccati equations appearing in variants of balanced truncation (LQG balanced truncation with nonzero D, balanced stochastic truncation, bounded real balanced truncation with nonzero D, ...). In particular, I'm considering removing the `S` part in [`riccati.solve_ricc_lrcf`](https://github.com/pymor/pymor/blob/e64ad5ca229fe6e72403ad9f25158e5b8908e1bd/src/pymor/algorithms/riccati.py#L20) and instead expect it to be given as a low-rank …
> Low-rank updated operators and Sherman-Morrison-Woodbury formula

- src/pymor/bindings/fenics.py
- src/pymor/core/config.py
- src/pymor/operators/mpi.py
- src/pymordemos/fenics_nonlinear.py
- src/pymortests/demos.py
- src/pymortests/fixtures/operator.py
This adds `FenicsOperator` which can be used to wrap nonlinear UFL forms as pyMOR `Operators`.
Fixes #752.
> Add support for nonlinear Operators in FEniCS bindings

- src/pymor/reductors/h2.py
- src/pymor/reductors/sor_irka.py
This prevents repeated calls to `reduce` to modify existing lists.
> Add method to reductors.h2 for clearing list attributes

- src/pymor/algorithms/hapod.py
- src/pymor/algorithms/pod.py
- src/pymor/algorithms/svd_va.py
- src/pymor/reductors/basic.py
- src/pymordemos/hapod.py
- src/pymordemos/minimal_cpp_demo/demo.py
- src/pymortests/algorithms/pod.py
- src/pymortests/algorithms/svd_va.py
I've added a basic implementation in `algorithms.qr_svd` and a notebook comparing it to `algorithms.pod.pod` which is based on the eigenvalue decomposition of the Gramian matrix.
`pod` is less accurate for small singular values, which is not unexpected, since the eigenvalue decomposition tries to compute the squares of the singular values. I'm not sure why `pod` doesn't try to compute all singular values with `rtol=0`.
I'm also not sure if "Gram-Schmidt + SVD" is the best possible approach. In particular, section 2 of [1] talks about how QR with column pivoting is a good preconditioner for Jacobi SVD. Besides the issue that Jacobi SVD is not yet an option in `scipy.linalg.svd`, I don't see how to compute QR with column pivoting using pyMOR's interfaces.
@pymor/pymor-devs Thoughts?
[1] New …
> SVD for vectorarrays using Gram-Schmidt

- README.md
The link now points to `requirements.txt` in 2019.2.x branch.
> Fix dependencies link in README

- src/pymor/analyticalproblems/functions.py
Similar to what we did with `OperatorBase`, this PR merges the default implementations of `FunctionBase` into the `Function` interface class.
> Merge FunctionBase into Function

- src/pymor/parameters/base.py
Fixes #726. @TiKeil, please take a look.
> Ensure that ParameterType.__str__ is always ordered alphabetically

- setup.cfg
- src/pymor/core/config.py
- src/pymortests/demos.py
- switch junit output format ahead of time, avoiding a warning
- skip buggy Ipython test on macosx
> CI updates

- src/pymor-demo
With my proposed modification a demo script user would 
experience something like this if they only had installed
the minimal requirements:
```
$ pymor-demo 
Usage:
/home/rene/.local/share/virtualenvs/issues_tmp-DKykuLNR/bin/pymor-demo DEMO_NAME | -h [DEMO_OPTIONS]
Arguments:
-h           this message
DEMO_NAME    select one from these: analyze_pickle,burgers,burgers_ei,delay,elliptic,elliptic2,elliptic_oned,elliptic_unstructured,fenics_nonlinear,hapod,heat,parabolic,parabolic_mor,string_equation,thermalblock,thermalblock_adaptive,thermalblock_gui,thermalblock_simple
DEMO_OPTIONS any arguments for the demo, including -h for detailed help
There are some pyMOR Demos for which additional packages need to be installed:
analyze_pickle
delay
heat
string_equation
thermalblock_gui
You can try to …
```
> Fix issue #836

- docs/source/bibliography.rst
- src/pymor/parameters/functionals.py
- src/pymortests/min_max_theta_functionals.py
Adds support for a variant of Bernards {min,max}-theta approach. However, we need an energy product which is not simply `fom.operator.assemble(mu=mu_star)`, since we also need to clear columns.
This is of interest to @TiKeil
> Min-theta approach

- src/pymor/operators/constructions.py
- src/pymortests/operators.py
This PR implements `VectorArrayOperator.apply_inverse` via a QR decomposition of the corresponding `VectorArray` (using `gram_schmidt`).
In particular this is relevant for nonlinear least-squares ROMs without hyperreduction, in which case the projected Jacobians are `VectorArrayOperators` and `apply_inverse` is called with `least_squares=True`.
> Implement VectorArrayOperator.apply_inverse

- src/pymor/vectorarrays/interface.py
This is primarily needed for `DummyPool` which will fail to push unpicklable `VectorArrays`.
Fixes #893.
> Implement VectorArray.__deepcopy__ via VectorArray.copy(deep=True)

- src/pymor/models/iosys.py
This basically copies `from_files` method from `LTIModel` to `SecondOrderModel`.
I'm hesitant about adding `from_mat_file` (SLICOT benchmarks that use .mat files only use the first-order form) or something like `from_mekbcd_files` (in Oberwolfach benchmarks there is usually one C matrix which conflicts with our Cp and Cv notation).
> Add from_files method to SecondOrderModel

- .github/workflows/automerge.yml
After I ran into _very_ subtle problems with the buildozer auto merge app I've decided to get rid of it in favor of a Github "built-in". You can use the new label "automerge" just the same way as you could comment "merge when ready" before.
> [ci] add a github action to replace the external buildozer app

- AUTHORS.md
- docs/source/bibliography.rst
- src/pymor/algorithms/samdp.py
- src/pymortests/algorithms/samdp.py
I implemented the the subspace accelerated dominant pole algorithm (https://ieeexplore.ieee.org/document/1717547) which computes the dominant poles of the transfer function of a LTI system. It can be used in the future to add modal MOR methods to pyMOR.
> [algorithms.samdp] add samdp algorithm

- src/pymor/parallel/basic.py
in order to differentiate from interface object with the same name.
Fixes #899.
> Rename RemoteObject  to GenericRemoteObject

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
for some reason the WWU IT runners refuse to 
run the manylinux1 wheel builder images.
As a temporary measure thses builds are now pinned to 
our institute's server
> [ci] pin wheel building to amm runner

- src/pymor/algorithms/newton.py
- src/pymortests/algorithms/stuff.py
Addresses #927.
This merge request fixes a bug that occurred when the residual in the Newton algorithm becomes exactly 0.
> [newton] fixed bugs with residual being exactly 0

- AUTHORS.md
- src/pymor/operators/constructions.py
- src/pymortests/operators.py
Especially while using the derivative of parameter functionals with the `d_mu()` method, it is very likely to happen that most of the evaluated coefficients in the `LincombOperator` are just zero. All operators that are multiplied by zero are thus wasted time. 
For large dimensions of the parameter space (for example 30), this would mean that we waste 29 `apply` methods (or `apply2`, `apply_adjoint`, `pairwise_apply`). Especially for high resolutions this waste of time is large. 
Thus, we propose to check the value of the coefficients before applying.
> [Operators] Speed up apply methods for LincombOperator

- src/pymor/analyticalproblems/thermalblock.py
> Fix order of parameters in thermalblock_problem

- AUTHORS.md
- docs/source/bibliography.rst
- src/pymor/algorithms/eigs.py
- src/pymortests/algorithms/eigs.py
I implemented the implicitly restarted arnoldi method for computing a few eigenvalues of a real `Operator`. This is related to the issues #774 and #772.
> [algorithms.eigs] add implicitly restarted arnoldi method

- src/pymor/algorithms/genericsolvers.py
- src/pymor/algorithms/timestepping.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/bindings/pyamg.py
- src/pymor/bindings/scipy.py
- src/pymor/operators/block.py
- src/pymor/operators/constructions.py
- src/pymor/operators/interface.py
- src/pymor/operators/list.py
- src/pymor/operators/mpi.py
- src/pymor/operators/numpy.py
- src/pymortests/fixtures/operator.py
and apply_inverse_adjoint.
It is used in the following places:
- `Operator.apply_inverse` passes `initial_guess` to `newton` in case of a nonlinear operator.
- Generic `lgmres`, as well as SciPy `bicgstab`, `lgmres`, `lsmr`, `lsqr`.
- The FEniCS bindings pass `initial_guess` to the backend.
- `implicit_euler` sets `initial_guess` to the solution of the last time step.
Fixes #924.
> Add initial_guess parameter to apply_inverse

- src/pymor/algorithms/rules.py
This pull request contains some minor improvements to the `RuleTable` mechanism to make it easier to debug:
- Fix the `repr` of `RuleTable` instances to also print a summary of all rules. So when I am with the debugger in `RuleTable.apply` I can just write `print(self)` to get a table of all rules. `print_rules(failed_rules)` will give me a summary of all rules which have failed to apply so far.
- Refactor `RuleTable.apply` to make it faster to step through with a debugger.
- Provide hooks to set conditional breakpoints for `RuleTable.apply`. For instance I can now write
```python
from pymor.algorithms.projection import ProjectRules
ProjectRules.breakpoint_for_obj(fom.operator)
ProjectRules.breakpoint_for_name('diffusion')
```
This will cause `ProjectRule.apply` to break when it …
> Simplify debugging of RuleTables

- AUTHORS.md
- docs/source/bibliography.rst
- src/pymor/algorithms/line_search.py
- src/pymor/algorithms/newton.py
- src/pymortests/algorithms/stuff.py
- src/pymortests/fixtures/operator.py
- src/pymortests/operators.py
When solving nonlinear problems for several different parameters, finding a proper value for the `relax` parameter of the Newton solver that works for every parameter is quite difficult. Thus, I implemented a (very) simple line search algorithm that, at least in my application, led to convergence of the Newton method for every parameter.
To check the original Armijo-Goldstein condition, one needs the gradient of the objective function. Thus, if no gradient is provided, a weaker version of this condition is checked; namely that the function value is decreasing, no matter to what extend.
To be able to compute the gradient of the error function in the Newton method, we switched from `error_norm` to `error_product` in the Newton. Thus, we can derive the gradient for any `error_product`. …
> [line-search] implement Armijo line search algorithm

- AUTHORS.md
- src/pymor/parameters/functionals.py
- src/pymortests/parameter_functionals.py
This PR implements a `LincombParameterFunctional`. 
Moreover this enables to use + and - operators for `ParameterFunctional.` Moreover, it is now possible to multiply `ParameterFunctional` by numbers. 
Also, a small test is added to a new file. (Didn't we have a test file for parameters/functionals.py yet?) 
This PR is of much interest for the product rule in https://github.com/pymor/pymor/pull/934
> [parameters/functionals] Add LincombParameterFunctional

- AUTHORS.md
- src/pymor/parameters/functionals.py
- src/pymortests/mu_derivatives.py
If the `ProductParameterFunctional` is simply a number times a `ParameterFunctional`, we can easily compute the `d_mu` for this. However, it is required to automatically detect this case. So, we first count the actual number of `ParameterFunctional`s in the product and compute the derivative in case, there is only one  `ParameterFunctional` . 
With this code, one can then go ahead and implement product rules and generalizations for more parameters, if needed.
> [parameters/functionals] Add derivative of products

- src/pymor/parameters/functionals.py
As proposed in https://github.com/pymor/pymor/pull/950, we can use a better name for derivatives of `ParameterFunctionals`.
> verbose name for d_mu functionals

- src/pymor/algorithms/newton.py
- src/pymor/operators/interface.py
- src/pymortests/algorithms/stuff.py
This PR improves/extends `pymor.algorithms.newton.newton` in the following ways:
- The new `error_measure` parameter allows choosing between the norm of the `'residual'` and the norm of the `'update'` vector as a measure for the error. In the case of the update vector, the realtive tolerance is to be understood in relation to the norm of the current solution.
- The defaults were changed to use the norm of the update vector with a relative tolerance of `1e-7` (about half machine precision).
- Armijo line search is enabled by default.
- `error_product` has been replaced with `range_product` and `source_product` as different inner products may be needed for computing the norm of the residual and the norm of the solution/update vector.
- The `atol` and `rtol` arguments have switched places in …
> Add norm of update vector as error measure in Newton algorithm

- src/pymor/parameters/base.py
- src/pymortests/parameters.py
I noticed that the explanation in https://github.com/pymor/pymor/blob/781dfe63414807e6d761989729fab0fdceb2eaaa/src/pymor/parameters/base.py#L96 is not true. 
it is user input dependent how `Parameters` are parsed. In particular, 
`Parameters(b=2, a=1)`
`Parameters(a=1, b=2)`
will parse input lists differently. The `parse` method will first fill the 'b' part although `__str__` shows the alphabetical order. This can be easily fixed by also considering a sorted dict in the parse method.
> [parameters] Fix a serious bug in Parameters.parse()

- AUTHORS.md
- src/pymor/parameters/functionals.py
- src/pymortests/min_max_theta_functionals.py
As discussed in https://github.com/pymor/pymor/issues/935 and first proposed in https://github.com/pymor/pymor/pull/861 , we can add a generalization for the max theta approach.  
This is a generalization of the max theta approach from https://github.com/pymor/pymor/pull/861 . It introduces a lower bound for a bilinear form which reads
gamma_UB_new(mu) = gamma_mu_bar * max{q = 1}^Q theta_prime_q(mu)/theta_q(mu_bar).
This enables to bound the continuity with the continuity constants of a bilinear form which has the same affine decomposition and only differs in terms of 'theta_q'. Note that before it was only possible to evaluate 
gamma_UB_standard(mu) = gamma_mu_bar * max{q = 1}^Q theta_q(mu)/theta_q(mu_bar).
Note, however, that I have also further generalized gamma_UB_new(mu) to the case …
> add BaseMaxThetaParameterFunctional to generalize max-theta approach 

- src/pymor/__init__.py
- src/pymor/core/cache.py
- src/pymor/parameters/base.py
- src/pymor/tools/frozendict.py
In the past, there have been several issues with parameters not being ordered, e.g. #977. With this PR all `Parameters` and `Mu` instances will always be ordered alphabetically.
The implementation relies on Python >= 3.7 and CPython >= 3.6 dicts being insertion ordered.
Obviously this may have some impact on performance. (Creating a `Frozendict(b=3, a=2)` takes 1.5 microseconds on my machine whereas creating a `SortedFrozenDict(b=3, a=2)` takes 2.5 microseconds.) But I would assume that this is negligible in most cases, and avoiding subtle bugs due to invalid implicit assumptions seems more important.
> Ensure that Parameters and Mu instances are always ordered alphabetically

- .coveragerc
- docs/Makefile
Running `make docs` on my machine raised a lot of warnings of the form `failed to import pymor.some.module`. It seems the issue were leftover ReST files in `docs/source/generated/` from before the moving of different subpackages. With this PR, running `make clean` in `docs/` will also remove these files.
I also noticed that `playground/` was referenced in `.coveragerc`, so I removed that part.
Sphinx still complains about instance attributes documented in the `Attributes` sections of classes:
<details>
<summary>The list of warnings</summary>
```
Didn't find CircleDomain.domain in pymor.analyticalproblems.domaindescriptions
Didn't find CircularSectorDomain.angle in pymor.analyticalproblems.domaindescriptions
Didn't find CircularSectorDomain.radius in …
```
> Doc build warning fixes

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
- src/pymor/algorithms/pod.py
> Set gram_schmidt tolerances in POD to 0 to never truncate pod modes

- src/pymortests/demos.py
see also https://github.com/pymor/pymor/pull/1001#issuecomment-658048218
> refactor demo test xfails

- docs/source/bibliography.rst
- docs/source/index.rst
- docs/source/tutorial-rb.rst
The time series plots still depend on #1009 to work in the rendered documentation.
The generated output should be [here](https://docs.pymor.org/tutorial-basisgen) after CI has finished.
> Add tutorial on how to build a reduced basis

- .github/labeler.yml
- .github/workflows/label.yml
This adds automatic labeling to PRs via Github actions and configurable path matching. 
I've seeded the `.github/labeler.yml` with a few labels and would welcome additional commits to this branch that expand that config before merging.
> [github] add a workflow for Labeler

- docs/source/getting_started.rst
I generated the documentation by running "make docs" and only found some minor inconsistencies that I fix in this PR. One thing I noticed though is that the images after calling `fom.visualize` in the "Getting started" section are flipped, but the results seem to be correct. Is there any part of the documentation that needs to be double checked?
> Documentation for 2020.1 Release

- src/pymor/algorithms/line_search.py
- src/pymor/algorithms/newton.py
When the maximum number of iterations in the Newton algorithm was exceeded, the number of iterations was not replaced by the actual number in the output. This is fixed within this PR. Furthermore, the output of the algorithms is made slightly more consistent.
> Fix of Newton error output

- src/pymor/bindings/pymess.py
- src/pymortests/lyapunov.py
I found out recently that `pymess.glyap` returns a NumPy matrix. This PR fixes it.
I guess it might be good to backport it to 2020.1.x.
> Fix solve_lyap_dense to always return a NumPy array

- src/pymor/algorithms/lrradi.py
- src/pymor/algorithms/riccati.py
- src/pymor/bindings/pymess.py
- src/pymor/bindings/scipy.py
- src/pymor/bindings/slycot.py
- src/pymortests/riccati.py
I have a few reasons for removing `S`.
- A Riccati equation with `S` can be converted, just by rearranging the terms, into one without `S`, in which case `A` becomes a low-rank updated operator (and, since recently, we have `LowRankUpdatedOperators`).
- Py-M.E.S.S. and `pymor.algorithms.lrradi` do not have (direct) support for `S`.
- For MOR applications, it seems beneficial to use the form without `S`. E.g., LQGBT with nonzero `D` needs to solve APE<sup>T</sup> + EPA<sup>T</sup> - (EPC<sup>T</sup> + BD<sup>T</sup>) (I + DD<sup>T</sup>)<sup>-1</sup> (EPC<sup>T</sup> + BD<sup>T</sup>)<sup>T</sup> + BB<sup>T</sup> = 0</center>, i.e., without the `S` term, (A - BD<sup>T</sup>(I + DD<sup>T</sup>)<sup>-1</sup>C)PE<sup>T</sup> + EP(A - BD<sup>T</sup>(I + …
> Remove S parameter from Riccati equation solvers

- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/numpy.py
- src/pymortests/vectorarray.py
This fixes `__str__` for `NumpyVectorArrayView` and `ListVectorArrayView`. Maybe the CI finds some more bugs.
The `__str__` methods for `ListVectorArray` and `ListVectorArrayView` could probably be improved, e.g., one is referring to the space and the other to the dimension. Also `ListVectorArrayView` used `self.vector_type` for some reason, which does not exist anywhere.
Closes #1057.
> Fix __str__ for VectorArray views

- docs/source/tutorial_bt.rst
- src/pymor/models/iosys.py
This PR adds the `bode_plot` method to `InputOutputModel` for drawing the Bode plot (with both magnitude and phases).
Also, an example is added to the BT tutorial. I used the [`constrained_layout`](https://matplotlib.org/3.3.0/tutorials/intermediate/constrainedlayout_guide.html) option since the suptitle is otherwise too high, but it is an experimental feature. The documentation suggests getting axes positions and setting them explicitly for reproducibility, but I guess this would have to be done for all 12 subplots...
See #389.
_Update_: This PR also adds the `bode` method that returns magnitudes and phases used in `bode_plot`.
> Add Bode plot

- docs/source/minimal_cpp_demo/model.cc
- docs/source/minimal_cpp_demo/model.hh
- docs/source/tutorial_external_solver.rst
- src/pymor/algorithms/genericsolvers.py
- src/pymor/algorithms/line_search.py
- src/pymor/algorithms/lrradi.py
- src/pymor/algorithms/projection.py
- src/pymor/algorithms/samdp.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/operators/constructions.py
- src/pymor/operators/interface.py
- src/pymor/operators/mpi.py
- src/pymor/reductors/coercive.py
- src/pymor/reductors/residual.py
- src/pymor/vectorarrays/block.py
- src/pymor/vectorarrays/interface.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/mpi.py
- src/pymor/vectorarrays/numpy.py
- src/pymordemos/minimal_cpp_demo/model.cc
- src/pymordemos/minimal_cpp_demo/model.hh
- src/pymordemos/minimal_cpp_demo/wrapper.py
- src/pymortests/algorithms/gram_schmidt.py
- src/pymortests/complex_values.py
- src/pymortests/operators.py
- src/pymortests/vectorarray.py
As proposed in #930, this PR deprecates the `dot` and `pairwise_dot` methods of `VectorArray` which are equivalent to calling `inner` or `pairwise_inner` without a `product` argument.
Any reservations @pymor/pymor-devs?
Note that currently we don't explicitly state anywhere that `inner` without a `product` is the Euclidean inner product. I would like to keep it that way as there might be use cases, where you want to implement `inner` with some 'special' product. (We already had several discussion about removing the `product` arguments and equipping `VectorSpaces` with `products`. I'm still not convinced that this is the right thing to do, but I at least want to have an open door for hacks in that direction.)
> Deprecate dot/pairwise_dot in favor of inner/pairwise_inner

- src/pymor/parameters/functionals.py
With the new parameter handling the index `()` changed to `0` which has the effect that it is very likely to instantiate `ExpressionParameterFunctional` in the wrong way. However, currently the user only realizes this while calling the `d_mu('mu',  0)` method. 
To be precise: 
```
ExpressionParameterFunctional('mu ** 2' , {'mu': 1}, derivative_expressions={'mu': '2*mu'}) 
```
currently results in an index error because a `numpy.ndarray` with shape `()` can not be called with `0`. The correct call is 
```
ExpressionParameterFunctional('mu ** 2' , {'mu': 1}, derivative_expressions={'mu': ['2*mu']}) 
```
Note the brackets in `derivative_expressions`. 
This error is very likely to happen and thus one could either 
1. `assert` the wrong call 
2. just catch it with an `if` statement. 
In this …
> [parameters] prevent a wrong user input for derivative_expressions

- docs/source/tutorial_external_solver.rst
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/vectorarrays/block.py
- src/pymor/vectorarrays/interface.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/mpi.py
- src/pymor/vectorarrays/numpy.py
- src/pymordemos/minimal_cpp_demo/wrapper.py
- src/pymortests/algorithms/basic.py
- src/pymortests/vectorarray.py
I don't know a single example, where this method has been used.
> Remove l1_norm from VectorArrayInterface

- docs/source/release_notes.rst
- docs/source/substitutions.py
- src/pymor/algorithms/image.py
- src/pymor/algorithms/preassemble.py
- src/pymor/algorithms/projection.py
- src/pymor/algorithms/to_matrix.py
- src/pymor/basic.py
- src/pymor/discretizers/builtin/fv.py
- src/pymor/discretizers/builtin/list.py
- src/pymor/operators/constructions.py
- src/pymor/operators/ei.py
- src/pymor/operators/interface.py
- src/pymor/reductors/basic.py
- src/pymortests/fixtures/operator.py
- src/pymortests/to_matrix.py
> Append Operator to LinearAdvectionLaxFriedrichs, Concatenation and ComponentProjection

- .ci/gitlab/common_test_setup.bash
- .ci/gitlab/test_pip_installed.bash
So for once we not seem to be hit with negative effects of a new pip feature. The new dependency resolver that will become the default some time after october seems to work fine for us.
> [ci] use new pip resolver for installs

- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/numpy.py
- src/pymortests/vectorarray.py
> Make VectorArrays iterable

- docs/source/tutorial_external_solver.rst
- docs/source/tutorial_mor_with_anns.rst
- src/pymor/algorithms/basic.py
- src/pymor/algorithms/ei.py
- src/pymor/algorithms/eigs.py
- src/pymor/algorithms/genericsolvers.py
- src/pymor/algorithms/greedy.py
- src/pymor/algorithms/krylov.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/models/iosys.py
- src/pymor/reductors/coercive.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/parabolic.py
- src/pymor/reductors/residual.py
- src/pymor/vectorarrays/block.py
- src/pymor/vectorarrays/interface.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/mpi.py
- src/pymor/vectorarrays/numpy.py
- src/pymordemos/analyze_pickle.py
- src/pymordemos/fenics_nonlinear.py
- src/pymordemos/minimal_cpp_demo/demo.py
- src/pymordemos/minimal_cpp_demo/wrapper.py
- src/pymordemos/neural_networks.py
- src/pymordemos/neural_networks_fenics.py
- src/pymortests/algorithms/basic.py
- src/pymortests/algorithms/eigs.py
- src/pymortests/solver.py
- src/pymortests/vectorarray.py
Following #1066, the implementations of `VectorArray.l2_norm`, `VectorArray.l2_norm2` are moved to private `_norm`, `_norm2` methods. `l2_norm` and `l2_norm2` are deprecated so that there is only one method to compute the Euclidean norm of a `VectorArray`. What that means (the Euclidean norm of the `dofs` of the array) is clarified in the docstring.
Moreover, `almost_equal` has been simplified by replacing the (unused) `norm` parameter by the `sup_norm` parameter.
> Deprecate l2_norm/l2_norm2 in favor of norm/norm2

- docs/source/_static/pymor.css
- docs/source/conf.py
This PR adds our new logo to the documentation and changes the colors such that they match the colors in the logo. The main color is chosen to be the same as on the webpage.
Unfortunately, it is not possible to set `color_primary` to some hex value, but one can only select certain values from a predefined list (the reason is that some other colors, for instance the font colors, are adjusted according to the value of `color_primary`). I selected `indigo` as `color_primary` since that seemed to be the closest possible choice to the main colors of our logo.
This is the result:
> [docs] add logo to documentation, adjust colors and fix minor bugs

- AUTHORS.md
- src/pymor/analyticalproblems/functions.py
- src/pymor/operators/constructions.py
- src/pymor/operators/interface.py
- src/pymor/parameters/functionals.py
- src/pymortests/function.py
- src/pymortests/parameter_functionals.py
Currently '+', '-' and '*' produce nested functionals which I find a little bit difficult to read and has potential to be a lot slower in evaluating the functional. 
In particular, suppose that a, b, c and d are `ParameterFunctionals`, then 
product = a * b * c * d 
would currently result in 
`ProductParameterFunctional ( [ProductParameterFunctional( [ ProductParameterFunctional( [a, b] ) , c ]) , d] ) `
which will now be changed to
`ProductParameterFunctional ( [ a, b, c ,d ] )`
Same goes for `LincombParameterFunctional`. 
In addition, I think the same goes for `LincombFunction` and `LincombOperator`. I propose to also avoid nesting in these functions. Do you agree ?
> Avoid nested parameter functionals and functions for sums and products

- src/pymor/parameters/functionals.py
This PR contains two changes:
- `ProductParameterFunctional.factors` is made a tuple.
- When two `ParameterFunctionals` are multiplied, their order is retained.
> Small ProductParameterFunctional improvements

- src/pymor/discretizers/builtin/cg.py
654b0f4e5 introduced a bug in the assembly of `AdvectionOperatorP1` causing wrong calculation of the element matrices, which is corrected by this PR.
> Fix AdvectionOperatorP1

- docs/source/substitutions.py
- src/pymor/algorithms/simplify.py
- src/pymor/basic.py
- src/pymortests/algorithms/simplify.py
This add `algorithms.simplify.expand` which will
- expand `ConcatenationOperators` of `LincombOperators`.
- merge `LincombOperators` of `LincombOperators`.
- merge `ConcatenationOperators` of `ConcatenationOperator`
Compared to #822, the scope of this algorithm is narrower, but the behavior is clearly defined.
Documentation and unit tests still missing.
> Add algorithm to expand concatenations of LincombOperators

- src/pymor/algorithms/greedy.py
Currently, specifying `extension_params={'pod_modes': 5}` for `rb_greedy` causes `gram_schmidt` to be chosen as extension algorithm instead of POD. This PR changes the behavior to always use POD for solution snapshots with more than one vector unless another `extension_method` is explicitly specified.
> Make changing number of POD modes for POD-greedy less error prone

- src/pymor/algorithms/projection.py
This PR in particular allows to properly project `LincombOperator @ VectorOperator` as needed for handling non-zero Dirichlet boundaries.
> Improve projection of ConcatenationOperator

- src/pymor/discretizers/builtin/cg.py
> decompose output functional in discretizer

- src/pymor/discretizers/builtin/cg.py
This started as a simple fix for the advection operator, but I got annoyed at the code duplication involving the shape functions, which lead to exactly these kind of errors. I do not like my solution too much, but it could be a start. Once we are there, there would also be much more code that could be share between the different Pk and Qk variants (only the mapping might differ, did not look at that).
> Refactor builtin cg discretizer

- src/pymortests/vectorarray.py
This fixes the test for all CI runner types. 
This previously failed if the python 3.6 vanilla job randomly landed on
a non-virtualized runner.
> weaken cmp tol for test_axpy_one_x

- docs/source/tutorial_projection.rst
- src/pymor/algorithms/error.py
- src/pymor/algorithms/greedy.py
- src/pymor/models/basic.py
- src/pymor/models/interface.py
- src/pymor/models/iosys.py
- src/pymor/models/mpi.py
- src/pymor/models/neural_network.py
- src/pymordemos/analyze_pickle.py
With this PR, `Model` gets a new `compute` method which realizes the computation of the model's solution and of derived quantities such as outputs or error estimates.
- `solve`, `output` and `estimate_error` are implemented by calling `compute` with appropriate arguments.
- By relying on a central method, we can avoid having to pass computed values from the outside, e.g. the solution to `estimate_error`. (Note that it might depend on the `Model` which values have to be passed.) 
- `compute` returns a dict of all computed values. `solve`, etc. remain as convenience methods.
- `compute` can be easily extended to return further quantities of interest. E.g. an optional `stages` argument might indicate to return intermediate Newton stages as an additional item of the return value.
- …
> add compute() to Model

- .github/workflows/enforce-labels.yml
- src/pymor/core/cache.py
- src/pymortests/cache.py
This PR changes the behavior of `MemoryRegion` to always make a `deepcopy` of any values stored in the cache and to only return deep copies of the values contained in the cache. While this may increase the memory footprint and somewhat hurt performance, it seems like the only way to make using `MemoryRegion` really safe. The practical impact of the increased memory usage should be quite small, IMHO.
Note that the current provisions of returning copies of `VectorArrays` and making NumPy arrays immutable had no effect since all values stored in the cache are actually 2-tuples.
See #1133 for a non-obvious real world example of `MemoryRegion` being corrupted.
> Prevent corruption of memory cache

- src/pymor/algorithms/projection.py
- src/pymortests/algorithms/projection.py
- src/pymortests/operators.py
- Added tests.
- Actions for `SeclectionOperator`, `ZeroOperator`, `VectorArrayOperator`, `BlockRowOperator`, `BlockColumnOperator`.
- Detect case when `dim_range is None` and `dim_source is None`.
- Ensure that ids are preserved when projection `NumpyMatrixOperator`.
> Minor project_to_subbasis improvements

- src/pymor/models/basic.py
- src/pymor/reductors/basic.py
- src/pymor/reductors/residual.py
When `InstationaryModel` is instantiated with `mass=None` or `rhs=None`, this PR causes corresponding attributes to be initialized with an appropriate `IdentityOperator` or `ZeroOperator`. In particular, this is in agreement with the behavior of `LTIModel`.
Also see #1121.
> Always initialize mass and rhs attributes of InstationaryModel

- src/pymor/operators/interface.py
- src/pymor/operators/numpy.py
- src/pymortests/operators.py
Also add a guard to let the default implementation of `as_source_array`/`as_range_array` fail when the resulting array might be too large.
Fixes #1096. @meretp, does this work for you?
> Implement as_source_array/as_range_array for sparse NumpyMatrixOperators

- AUTHORS.md
- docs/source/bibliography.rst
- src/pymor/models/neural_network.py
- src/pymor/reductors/neural_network.py
- src/pymordemos/neural_networks_instationary.py
- src/pymortests/demos.py
This pull request adds a `NeuralNetworkInstationaryReductor` that handles instationary problems. Furthermore, a demo solving Burgers' equation is implemented and added to `pymortests`.
> Neural networks for instationary problems

- src/pymor/models/iosys.py
It also fixes flake8 issues about long lines.
Closes #1063.
> Simplify __sub__ for iosys models, check D operator in h2_norm

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
Since our dedicated build box has intermittent docker daemon connection
problems this PR moves most of the jobs to the openstack
autoscaled machines exclusively
> [ci] move more jobs onto autoscaled machines

- notebooks/delay.ipynb
- notebooks/heat.ipynb
- notebooks/parametric_delay.ipynb
- notebooks/parametric_heat.ipynb
- notebooks/parametric_string.ipynb
- src/pymor/models/basic.py
- src/pymor/models/interface.py
- src/pymor/models/iosys.py
- src/pymor/models/neural_network.py
- src/pymor/reductors/bt.py
- src/pymor/reductors/h2.py
- src/pymor/reductors/interpolation.py
- src/pymor/reductors/sor_irka.py
- src/pymordemos/delay.py
- src/pymordemos/heat.py
- src/pymordemos/string_equation.py
As discussed, outputs of Models are made NumPy arrays instead of VectorArrays to facilitate interfaces with pyMOR Models from user code / external code. 
**Edit:**
~I chose `output_dim` over `dim_output` to be consistent with the choice in `models.iosys` and also because I think it sounds nicer. However, this is somewhat inconsistent with the rest of pyMOR where 'dim_***' is used.~
The dimension of the output is given by `dim_output` attribute. `output_dim` of `IntputOutputModel` has been renamed accordingly. Its `input_dim` attribute has been renamed to `dim_input`. The old names are deprecated.
In addition, `input_space` and `output_space` have been removed from `InputOutputModel` and the `b` and `c` arrays of tangential directions for the interpolatory reductors have been made numpy …
> Let Model outputs be NumPy arrays

- src/pymor/algorithms/gram_schmidt.py
See discussion in #1067
Fixes #1067.
> Increase gram_schmidt default reiteration_tol to 9e-1

- src/pymor/discretizers/builtin/gui/jupyter/matplotlib.py
- src/pymor/discretizers/builtin/gui/matplotlib.py
Following up on #1171, I tried to get away without specifying the absolute figure size, cause that is never a good idea. I found a way to only scale the axes which works well in my example. I also place the colorbar horizontally, if the grid is thin, cause it looks really ugly otherwise. This is of course a serious design decision...
> Allow to change aspect ratios of matplotlib plots

- docs/source/heat_equation.txt
- docs/source/tutorial_bt.rst
- docs/source/tutorial_lti_systems.rst
- docs/source/tutorials.rst
- src/pymor/models/iosys.py
- src/pymor/reductors/interpolation.py
This is still a work in progress. The idea is to add an LTI tutorial and for the existing BT tutorial to reuse the model from there. An IRKA tutorial could be added in a new PR
> Restructure sys-mor tutorial

- .ci/gitlab/test_oldest.bash
While documenting the CI setup in the other PR I discovered
that the "oldest" job actually no longer uses the packages
from the "oldest" pypi mirror. This PR makes sure of that
by removing all installed packages and installing again
from the "oldest" mirror.
> fix "oldest" CI job

- src/pymordemos/delay.py
- src/pymordemos/heat.py
- src/pymordemos/parametric_delay.py
- src/pymordemos/parametric_heat.py
- src/pymordemos/parametric_string.py
- src/pymordemos/parametric_synthetic.py
- src/pymordemos/string_equation.py
- src/pymortests/demos.py
This PR does some major changes in sys-mor tutorials: adding more MOR methods, improving consistency across demos, and removing some code duplication and unneeded plots. Also, it reduces problem dimensions for system testing.
> Improve sys-mor demos

- CONTRIBUTING.md
- docs/RELEASE_CHECKLIST.md
- docs/source/getting_started.rst
- setup.py
I just found that there are still some mentions of the now non-existent pymor-dev mailing list. I removed some, but there is still one in `setup.py`. @renefritze, any idea what to do about the `author_email` field in `setup.py`?
> Remove mailing list mentions

- AUTHORS.md
- docs/source/bibliography.rst
- src/pymor/models/basic.py
- src/pymor/models/interface.py
- src/pymor/operators/block.py
- src/pymor/reductors/basic.py
- src/pymordemos/linear_optimization.py
- src/pymortests/demos.py
- src/pymortests/mu_derivatives.py
This PR adds code for handling PDE-constrained parameter optimization. We only cover simple linear optimization in the sense that the output functional is linear. For that, we add code to compute the gradient of the output functional w.r.t. the parameter.
To compute the gradient, two approaches are feasible. One is to compute the sensitivities of the solutions and one is the adjoint approach, where a dual solution is used. 
We also added a demoscript where we test all of the code by comparing the computational time between FOM and ROM implementation. 
For more information on the topic, we also have a tutorial in #1205,
> Towards linear optimization (dual problem, sensitivity problem, output gradient)

- .ci/azure/pipeline-win.yml
- docs/source/try_on_binder.py
- docs/source/tutorial_optimization.rst
- docs/source/tutorials.rst
This PR contains a very detailed tutorial for optimization. The content is highly related to my talk on the online pymor school 2020. 
I will rebase this PR after #1110  has been merged. So please ignore all commits except the last two and only look at [this file](https://github.com/TiKeil/pymor/blob/tutorial_optimization/docs/source/tutorial_optimization.rst).
@pymor/all it would be nice if you could read through it, there might be some typos or other issues. 
Let me know what you think.
> Tutorial for optimization

- docs/source/conf.py
Sourcing the scipy url for numpy's object db started failing recently.
Also added a couple more that could be useful.
> fix interpshinx mapping

- src/pymor/operators/block.py
When initailizing a `BlockOperator`, `None` objects in `blocks` are automatically converted to `ZeroOperators`. For a case when a `BlockOperator` has a very sparse structure, this can end in `apply` and `apply_adjoint` computing `op.apply` for many `ZeroOperators`. This PR adds an if statement to neglect all `ZeroOperators` which gave significant speed up in my use case.
Other methods apart from `apply` and `apply_adjoint` in `BlockOperator` may also suffer from this issue, but as far as my investigations showed, the performance is still good enough.
> [operators/block] skip ZeroOperators in apply and apply_adjoint

- src/pymor/discretizers/builtin/grids/interfaces.py
While looking for some inspiration for the implementation of spacetime meshes, I stumbled across this small bug.
> Fixed computation of intersection_codim in _neighbours

- .ci/gitlab/deploy_docs.bash
- src/pymor/operators/constructions.py
- src/pymortests/operators.py
I have found a small bug in `apply_inverse` and `apply_inverse_adjoint` in `LincombOperator`. 
The first commit of this PR tweaks a simple test which should go through but doesn't, the second fixes the bug.
> Fix bug in apply_inverse for LincombOperators

- .ci/gitlab/test_mpi.bash
- src/pymortests/mpi_run_demo_tests.py
This workaround treats the result of pytest as the success/fail trigger for the pipeline
not the exit code of the mpirun script.
The background here are intermittent failures were one rank does not call `MPI_Finalize` 
before exiting. While I made it configurable for pyMOR to tell mpi4py to do that
or not on module de-init, mpirun still sometimes errors out with "unclean"
process exits. These are never reproducable (locally or on pipeline re-run), not limited to 
python versions, nor have any other descernible pattern. Which is why I propose this workaround. 
This PR also forces the mpi runtime to use the in memory transport which
should stop the "slow transport fallback" message from popping up in logs.
> intermittent MPI CI failure workaround

- src/pymor/algorithms/lincomb.py
- src/pymor/models/iosys.py
- src/pymor/operators/block.py
After I found another issue with `assemble_lincomb` and `RecursionError`, this time with multiplying `SecondOrderModelOperator` by `-1`, I concluded it might be best to remove `ShiftedSecondOrderModelOperator` and generalize `SecondOrderModelOperator`. In particular, with this PR, `SecondOrderModelOperator` represents 2x2 block operators of the form `[[a * I, b * I], [B, A]]`.
> Simplify SecondOrderModel-related operators

- docs/source/tutorial_projection.rst
- src/pymor/algorithms/rules.py
- src/pymor/tools/formatsrc.py
- src/pymortests/tools.py
Fixes #1189.
I find `rule.__repr__` showing source code and potentially not just returning a string a bit strange, so I removed it. I'm open to other ideas.
Edit: This PR:
- edits methods in `tools.formatsrc`, removes `source_repr`
- edits `rule.__repr__` to only return `str`
- adds `rule._ipython_display_`
> Fix `make docs` printing `rules`, edit `tools.formatsrc` and `rule.__repr__`

- src/pymor/discretizers/builtin/gui/jupyter/__init__.py
- src/pymor/discretizers/builtin/gui/jupyter/threejs.py
- Use `Label`s from ipywidgets to render colorbar.
- Fix the behavior of `rescale_colorbars`.
- Some minor layout improvements.
In addition, the threejs backend is made the default jupyter visualization backend as already advertised in the release notes of 2020.1.
Fixes #1289.
> Some improvements to WebGL visualizations

- docs/source/tutorial_basis_generation.rst
- docs/source/tutorial_mor_with_anns.rst
- src/pymor/parameters/base.py
- src/pymortests/parameters.py
The current behavior of `ParameterSpace.sample_randomly` with `count=None` is to return an inexhaustible iterator. A feature, which was probably never used. This PR changes the behavior to return a single `Mu` instance instead. Thus, one can write:
```python
m.solve(parameter_space.sample_randomly())
```
instead of
```python
m.solve(parameter_space.sample_randomly(1)[0])
```
I think this new behavior is very useful for interactive use.
> Let sample_randomly return a Mu instance in case count=None

- src/pymor/models/neural_network.py
- src/pymor/reductors/neural_network.py
To make the training algorithm reusable, it is moved out of the reductor class.
> [neural-networks] restructured training of neural networks

- src/pymor/algorithms/lincomb.py
- src/pymor/operators/constructions.py
- src/pymortests/operators.py
> Simplify semantics of assemble_lincomb / fix #1276

- src/pymor/models/interface.py
While working on https://github.com/pymor/pymor/pull/1282#discussion_r622018563, I stumbled across this small bug, where `dtype` was set to `0` in `np.zeros`. This call happens in the case of a missing `output_functional` when `compute` is called with `output=True`.
> Small bug fix in models.interface

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
- .ci/gitlab/test_mpi.bash
- .pre-commit-config.yaml
Since I was unable to find the actual
cause for the MPI processes to sometimes hang on gitlab
those jobs are now restarted automatically.
For the next person to look into this:
- if a hang happens, it will happen never happen in the first demo to use mpi
- Doesn't matter if it's auto-mpi pools for algorithms or MPI-wrapped models
- Doesn't matter if in-memory or tcp transport is used
- Output verbosity, probably due to changing timing of calls between processes,
seems to affect frequency of hangs
- Restarting the event loop, and clearing remote objects between demos, produced
crashes, but might be worth looking into again
- making mpirun produce stack traces on job timeout fails with input/output 
errors in pstack (after symlinking pstack to gstack)
> Workaround for MPI hangs in CI

- src/pymor/tools/floatcmp.py
- src/pymortests/tools.py
This PR fixes `pymor.tools.floatcmp.almost_less` for negative numbers by taking the absolute value of `y`. It also removes `compare_with_tolerance` in favor of directly implementing `almost_less`.
> Fix almost_less for negative numbers

- src/pymor/algorithms/hapod.py
- src/pymordemos/hapod.py
- src/pymortests/demos.py
- `hapod` launches now its own asyncio event loop in order to avoid conflicts with already running event loops (e.g. when running form juypter).
- It is now possible to explicitly specify that a node has to be processed after certain other nodes. In particular, this can be used to ensure the right execution order for incremental POD computations.
- HAPOD trees are now created dynamically, which should significantly simplify specifying own tree topologies.
- `dist_hapod` now has an `arity` argument, which allows to control the number of intermediate POD levels.
- `inc_hapod` now accepts arbitrary iterables for the snapshot data.
In particular, now the following code works:
```python
from pymor.analyticalproblems.thermalblock import thermal_block_problem
from pymor.discretizers.builtin.fv …
```
> Various Improvements to the HAPOD algorithm (v2)

- src/pymor/vectorarrays/mpi.py
Currently, calling `real`, `imag` or `conj()` on an MPIVectorArray accesses the methods of vectorarrays.interface that don't implement what they are pretending to.
With this change, the corresponding methods of the wrapped object are executed.
It breaks lradi when executed with mpi.
> Use complex vector handling of wrapped object in MPIVectorArray

- src/pymor/models/iosys.py
- src/pymor/tools/io.py
- src/pymortests/iosys_save_load.py
- src/pymortests/tools.py
This PR adds `to_*` methods to `LTIModel` and `SecondOrderModel`, tests for `from_*` and `to_*` methods, and output methods to `tools.io`. The tests should cover most of what is not covered by #1300 in `models.iosys`. I'm not sure how the CI will react to creating temporary files; I guess we'll see.
> Add methods to `models.iosys` for exporting matrices

- src/pymor/algorithms/lradi.py
- src/pymor/bindings/pymess.py
- src/pymortests/lyapunov.py
- src/pymortests/riccati.py
This PR:
- adds `subspace_columns` option to `lradi`,
- changes the corresponding default option for `pymess`, and
- makes other edits in `lradi` (one bigger change is how much memory is reserved for the low-rank factor; I'm not sure if it's better to reserve a lot and clear a lot or just not reserve anything, so I went for the simpler option).
This was motivated by the Gramian computation for the [Penzl's FOM model](https://morwiki.mpi-magdeburg.mpg.de/morwiki/index.php/FOM). Here is the code:
```python
import numpy as np
import scipy.sparse as sps
from pymor.core.defaults import set_defaults
from pymor.models.iosys import LTIModel
set_defaults({
'pymor.algorithms.lyapunov.solve_lyap_lrcf.default_sparse_solver_backend': 'lradi',
})
A1 = np.array([[-1, 100], [-100, -1]])
A2 = …
```
> Improve shift selection in `lradi`

- src/pymor/__init__.py
- src/pymor/core/defaults.py
- src/pymor/parallel/ipython.py
- src/pymor/tools/mpi.py
This pr synchronizes defaults according to the instructions in #1329.
I have never used anything of the `pymor.parallel` package before, so someone should take a closer look at this part. Especially because I am assuming that 'job scheduling' refers to `_push_object`. Maybe there are cases where it is necessary to check the defaults in `_apply`/ `_apply_only` too?
Kept all commits to make the code review easier. But as they all perform just small changes, you might want to squash merge them.
> Keep consistent defaults with multiple processes

- .ci/gitlab/ci.yml
- .ci/gitlab/template.ci.py
- src/pymor/parameters/base.py
Otherwise `parameters.parse(mu)` fails, if `isinstance(mu, Mu)`. Was I really the first one to stumble upon this?
> fix parse(mu) for a mu that is a Mu

- docs/source/bibliography.bib
- src/pymor/algorithms/ei.py
- src/pymor/analyticalproblems/functions.py
- src/pymor/basic.py
- src/pymor/discretizers/builtin/grids/oned.py
- src/pymordemos/function_ei.py
- src/pymortests/demos.py
- `ei_greedy` improvements:
- The `nodal_basis` option allows to compute a nodal interpolation basis.
- The interpolation matrix is now returned in the data dictionary.
- The `coefficients` array of `data` contains the coefficients of the computed basis w.r.t. the input data vectors.
- `error_norm` can be set to `'sup'` to use `sup_norm` for the error as it makes sense for the interpolation of functions.
- The new `interpolate_function` uses `ei_greedy` (and the new `coefficients` return value) to build an `EmpiricalInterpolatedFunction` from an arbitrary pyMOR `Function`.
- The new `function_ei` demo demonstrates the new functionality.
> Several EI improvements

- CITATION.cff
- MANIFEST.in
so we get a nice GitHub widget for it:
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">We’ve just added built-in citation support to GitHub so researchers and scientists can more easily receive acknowledgments for their contributions to software.<br><br>Just push a CITATION.cff file and we’ll add a handy widget to the repo sidebar for you.<br><br>Enjoy! 🎉 <a href="https://t.co/L85MS5pY2Y">pic.twitter.com/L85MS5pY2Y</a></p>&mdash; Nat Friedman (@natfriedman) <a href="https://twitter.com/natfriedman/status/1420122675813441540?ref_src=twsrc%5Etfw">July 27, 2021</a></blockquote>
> adds a CITATION.cff

- .ci/gitlab/install_checks/debian_buster/check.bash
apt will now error out b/c the suite value changed.
Buster is now oldstable
> [ci] adjust for new debian release

- src/pymortests/demos.py
This reverts commit b3771516808e1a2f236a90f5cb9fce2bfcf7858b.
Installing Pytorch from conda-forge now results in conflicts.
> Disable torch tests on windows azure

- src/pymor/algorithms/lrradi.py
This PR fixes a bug in shift generation which caused problems when the `C` matrix of the LTI system had many rows. Additionally, it fixes a small bug in the main algorithm.
> Bugfixes in lrradi

- src/pymor/core/config.py
- Prevents `_get_qt_version` from raising an error when no Qt bindings are installed.
- Remove Cython from config object.
> Fix qt config check

- src/pymor/bindings/fenics.py
- src/pymortests/fixtures/operator.py
- src/pymortests/operators.py
This PR makes `FenicsMatrixOperator.apply_inverse_adjoint` not use pyMOR's `lgmres` by working with the underlying `PETScMatrix`.
> Add `FenicsMatrixOperator._real_apply_inverse_adjoint_one_vector`

- src/pymor/algorithms/timestepping.py
- src/pymor/analyticalproblems/functions.py
- src/pymor/core/cache.py
- src/pymor/parameters/base.py
- src/pymor/tools/frozendict.py
- src/pymortests/fixtures/parameter.py
- src/pymortests/function.py
- src/pymortests/parameters.py
- src/pymortests/strategies.py
This PR introduces support for time-dependent parameter values:
- `Mu` can be instantiated with values which are a `Function` with `dim_domain == 1` and `len(shape_range) == 1`.
- If the value for parameter `k` is such a `Function`, `mu[k]` will be given by the function evaluated at `mu[t]`.
- If `t` has no value in `mu` the value `0` is used instead.
- One can check whether a parameter value depends on time (and will change in `mu.with_(t=new_value)`) using the new `is_time_dependent` method.
- The time dependent function can be recovered using `mu.get_time_dependent_value`, which will return a `ConstantFunction` for values that do not depend on time.
- `Parameters.parse` has been extended accordingly. Instead of a `Function`, also a `str` can be provided, which is then converted to an …
> Time dependent parameter values

- src/pymor/algorithms/projection.py
- src/pymor/models/basic.py
- src/pymortests/model.py
This PR add a `deaffinize` method to `StationaryModel` which returns an equivalent `Model` with linear solution space. This is in particular useful for treating non-homogeneous Dirichlet boundary conditions with MOR methods that use linear approximation spaces.
A similar method for `InstationaryModel` (#1411) and a corresponding tutorial (#1412) will be added later.
> Add StationaryModel.deaffinize

- src/pymor/models/iosys.py
The parameter passed to the `LTIModel.get_ast_spectrum` method is now parsed. Also, a bug w.r.t. indexing is fixed.
> Bugfix in get_ast_spectrum

- docs/source/bibliography.bib
- src/pymor/algorithms/lradi.py
- src/pymordemos/heat.py
This PR adds a new shift selection to the Low-Rank ADI iteration. The shifts are optimal but can only be expected to work for symmetric system matrices. The shifts are tested in the `heat.py` demo.
> Wachspress' shifts

- src/pymor/algorithms/samdp.py
Currently the SAMDP algorithm considers each pair of complex conjugate eigenvalues as one computed pole. For modal truncation this behavior does not make sense because `r` poles are needed for a ROM of order `r` (and not `r` pairs of complex conjugate poles). Accordingly, up to twice as many poles as necessary are currently computed in the modal truncation reductor. This PR changes the SAMDP behavior to be more in line with the `MTReductor`.
> SAMDP improvement

- src/pymortests/vectorarray.py
This adds a test for copy on write of VectorArrays and increases the `max_examples` count to 20 in `dev` and `debug` sessions.
I stumbled upon broken COW functionality when binding a vector from an external PDE solver, and this was not catched by our tests.
Regarding the increase in `max_examples`: when adding an additional backend to the `strategies.py`, it is most likely not tested by hypothesis (don't know why, perhaps since last in list after `numpy`, `numpy_list` and `block`). In addition, there are rarely any `valid_indices` chosen apart from `[]`. Increasing the count to 20 helped a lot here.
> Add vectorarray cow test

- src/pymor/discretizers/builtin/list.py
- src/pymor/models/basic.py
- src/pymor/models/interface.py
- src/pymor/models/neural_network.py
- src/pymor/reductors/basic.py
- src/pymor/reductors/neural_network.py
So far, `StationaryModel`, `InstationaryModel` and `NeuralNetworkModel` allowed `output_functional` to be `None`. This PR changes the behavior to set `output_functional` to `ZeroOperator(NumpyVectorSpace(0), self.solution_space)` in case no functional is provided.
This reduced the need for special cases, better aligns these `Models` with a mathematical definition and is in line with what is done for the system-theoretic `Models`.
> Ensure that output_functional is never None

- src/pymor/bindings/fenics.py
- src/pymor/core/cache.py
- src/pymor/core/exceptions.py
- src/pymor/core/pickle.py
- src/pymor/models/mpi.py
- src/pymor/vectorarrays/mpi.py
- Don't generally disable caching in `mpi_wrap_model` (see #1328).
- Let `DiskRegion` log a warning instead of failing when a value cannot be pickled.
- Add `unpicklable` class decorator which produces an `UnpicklableError` when the decorated class is pickled.
- Catch `UnpicklableError` in `DiskRegion.set` to generate better error messages.
Supersedes #1335.
> Improve error handling in DiskRegion / Don't disable caching in mpi_wrap_model

- src/pymortests/demos.py
This reverts commit a15a0a352200f4a7e5fcd76932a6853fcaf2d822.
Underlying issue was fixed in matplotlib
closes #1293
> Revert "[tests] fall back on `plt.show = nop` for python 3.7"

- docs/source/_static/pymor.css
- docs/source/_templates/layout.html
To improve the appearance of the API documentation, I made some changes to the custom CSS file. The result looks like this:
One can take a closer look here: https://docs.pymor.org/github-push-improvements-docs/autoapi/index.html
> Improvements to API documentation

- src/pymor/models/basic.py
- src/pymor/models/interface.py
- src/pymor/models/iosys.py
- src/pymor/parameters/base.py
This PR adds an `input` parameter to `Model.compute` and related methods. As we want to treat inputs internally as time-dependent parameter values, the value of `input` is added to `mu` in `compute` before called methods such as `_compute_solution`.
Further, to allow transparent handling of `Operators` of the `Model` which take the `input` as a parameter, `Model.__init__` now expects `dim_input` as an additional argument and automatically sets `parameters_internal` to `{'input': dim_input}`, thus, preventing `input` from appearing as a parameter of the `Model`.
> Add input parameter to interface methods of Model

- src/pymor/core/cache.py
This change will cause `@cached` to fail in case the decorated function has an argument `mu` which does not take `Mu` instances. However, I do not think that this will happen and it makes `@cached` quite a bit more convenient to use.
> Ensure that mu arguments are parsed before cache keys are built

- src/pymor/models/neural_network.py
The `for`-loop over time in the instationary neural network models is replaced by passing all inputs as a single batch to the neural network. This improves the online running time of the neural network ROMs and leads to much better speedups in the demos.
> Speedup computations by passing inputs as batch in the instationary ANN models

- src/pymor/core/base.py
- src/pymor/parameters/base.py
`*args/**kwargs` are not considered when inheriting `Parameters`. This PR causes `ParametricObjects` for which `__init__` takes a variable number of arguments to produce a warning when the `parameters` attribute is accessed.
This is a safety feature for developers to ensure that such arguments are handled correctly. The warning can be silenced by setting the `_parameters_varargs_warn` class attribute to `False`.
> Warn when __init__ of a ParametricObject takes a variable number of arguments

- .ci/azure/pipeline-win.yml
- src/pymortests/demos.py
- [ci|azure] move python setting to env creation
- [ci|azure] use correct comment statement
- [ci|azure] replace deprecated windows platform with most current one
- [ci|azure] fix wrong section displayNames
- [ci|azure] switch mesa installer version
- Revert "Revert "[tests] fall back on `plt.show = nop` for python 3.7""
Supersedes #1494
> fix windows azure CI

- AUTHORS.md
- src/pymor/models/basic.py
- src/pymor/models/interface.py
- src/pymor/reductors/coercive.py
- src/pymor/reductors/parabolic.py
- src/pymordemos/output_error_estimation.py
- src/pymortests/demos.py
This supersedes #1337 . We added the following items:
1. Move the computation of the gramian to a separate function `assemble_output_error_estimate`.
2. Make it possible to have vector valued outputs.
3. Add a small test case for the coercive and parabolic case.
4. Use features of `CoerciveRBReductor` for computation of gramian
I am also currently preparing a PR that will supersede #1418. However, the code has no intersection with this PR. Thus, we merge it separately.
> Simple output estimator with dual norm

- src/pymor/vectorarrays/block.py
- src/pymor/vectorarrays/interface.py
- src/pymor/vectorarrays/list.py
- src/pymor/vectorarrays/mpi.py
- src/pymor/vectorarrays/numpy.py
- src/pymortests/strategies.py
- src/pymortests/vectorarray.py
This PR fixes incorrect slicing of VectorArrays in some corner cases.
It also removes the filtering of slices in VectorArray tests.
closes #1348
> Fix VectorArray slicing and disable slice filtering in VectorArray tests

- .ci/check_mailmap.py
- .ci/gitlab/ci_sanity_check.bash
- .mailmap
- docs/RELEASE_CHECKLIST.md
Compared to #1491 this drops adding mailmap updates from release checklist,
and adds a gitlab CI check instead.
> update mailmap and add CI check

- setup.cfg
- src/pymor/bindings/dunegdt.py
- src/pymor/bindings/fenics.py
- src/pymor/bindings/ngsolve.py
- src/pymor/bindings/pymess.py
- src/pymor/bindings/slycot.py
- src/pymor/core/config.py
- src/pymor/core/defaults.py
- src/pymor/core/exceptions.py
- src/pymor/discretizers/builtin/grids/vtkio.py
- src/pymor/discretizers/builtin/gui/gl.py
- src/pymor/discretizers/builtin/gui/jupyter/__init__.py
- src/pymor/discretizers/builtin/gui/jupyter/matplotlib.py
- src/pymor/discretizers/builtin/gui/matplotlib.py
- src/pymor/discretizers/builtin/gui/matplotlib_base.py
- src/pymor/discretizers/builtin/gui/qt.py
- src/pymor/discretizers/builtin/gui/visualizers.py
- src/pymor/discretizers/skfem/cg.py
- src/pymor/discretizers/skfem/domaindiscretizer.py
- src/pymor/models/neural_network.py
- src/pymor/parallel/ipython.py
- src/pymor/reductors/neural_network.py
- src/pymor/tools/io/__init__.py
- src/pymor/tools/io/vtk.py
- src/pymortests/core/config.py
- src/pymortests/gui.py
- src/pymortests/tools.py
This pr adds ~`require_dependency` to `pymor.core.config`~ a `require` method to `pymor.core.config.config`, which will raise an `DependencyMissing` error when the provided config item is not available. I refactored all relevant modules to use this mechanism instead of the current `if config.HAVE_FOO` checks, which lead to unnecessary indents and leads to the surprising behavior that an imported module is empty. As a consequence, importing e.g. `pymor.bindings.fenics` will raise an error, when fenics is unavailable. To avoid an exception one, thus, has to check first for fenics availability and then conditionally import the bindings. In practice this should be only necessary in very few places.
Also see discussion in #1343.
> Remove 'if config.HAVE_...' checks in modules that require optional dependencies

- docs/source/environment.rst
- src/pymor/__init__.py
- src/pymor/models/mpi.py
- src/pymor/tools/mpi.py
- In `mpi_wrap_model` ensure proper cleanup of objects managed by pyMOR's MPI event loop.
- Issue a warning when there are still managed objects when the event loop is shut down.
- Switch import order for petsc4py and mpi4py.
The last commit locally fixes petsc trying to communicate after MPI_Finalize during interpreter shutdown. @renefritze, was there any reason for the prior import oder?
> Improve MPI related interpreter shutdown issues

- src/pymor/core/logger.py
Fixes the default value of the `filename` argument of `getLogger`, to allow specification using our defaults.
Reasoning: `@default` values are only inserted if the function is called with `None` as argument. Since the signature of `getlogger` was `getLogger(module, ...filename='')`, any call to `getLogger('foo')` translates to `filename=''`. This results in a scenario, where a user calls
```python
set_defaults({'pymor.core.logger.getLogger.filename': 'bar.txt'})
```
without getting output in `bar.txt`. Defaulting `filename=None` fixes this.
> Fix setting of logger filename via defaults

- src/pymor/operators/numpy.py
fixes #1560.
I could not test whether the doc-link works due to #1557 but I don't see a reason that it shouldn't.
> add spmatrix to docstring of `NumpyMatrixOperator`

- AUTHORS.md
- docs/source/bibliography.bib
- src/pymor/algorithms/to_matrix.py
- src/pymor/operators/numpy.py
- src/pymortests/fixtures/operator.py
- src/pymortests/operators.py
Following the discussion #1535 and #1537, this PR introduced a new `NumpyHankelOperator` class that implements FFT-accelerated `apply` methods.
Please refer to #1537 for the math and some basic benchmarks.
The idea behind this is to use it together with a randomized range finder to enable the Eigensystem Realization Algorithm with high-dimensional data. This class could maybe be useful for other MOR-methods that work with the Hankel matrix as well.
The `__init__` method takes an `array` of Markov parameters that represent the Hankel matrix.
For an uneven number of Markov parameters, i.e. <img src=
"https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cbegin%7Balign%2A%7D%0Ah%5Cin%5Cmathbb%7BR%7D%5E%7B2s-1%7D%0A%5Cend%7Balign%2A%7D">, this is the matrix …
> `NumpyHankelOperator` class

- src/pymor/core/config.py
- Only warn when dolfin version is too old. (Since development of dolfin has ceased in favor of dolfinx, it is safe to only check for old versions.)
- Properly report version of dealii bindings.
- Report ngsolve version.
- Report meshio version.
> Improve config checks for FEniCS and dealii

- .ci/gitlab/test_numpy_git.bash
- .github/workflows/process_linter_results.yml
Numpy git has bumped its dependencies, but due to https://github.com/pymor/pymor/pull/1555
we currently cannot update docker images. So we'll allow unfrozen dependencies in the numpy job for now
> [ci] allow numpy to pull in unfrozen dependencies

- docs/source/tutorial_optimization.md
- src/pymordemos/linear_optimization.py
This is cherry-picked from #1562, where it was needed to make the Azure pipeline pass. I guess the issue is that SciPy's `minimize` handles array-valued objective functions differently in different SciPy versions.
Indeed, I tried testing it, and it seems that at least L-BFGS-B changed from SciPy 1.7 to 1.8.
```python
import numpy as np
from scipy.optimize import minimize, rosen, rosen_der
def fun(x):
return np.array([rosen(x)])
x0 = [1.3, 0.7, 0.8, 1.9, 1.2]
res = minimize(fun, x0, method='L-BFGS-B', jac=rosen_der)
print(res.fun)
```
Output with SciPy 1.7.0:
```python
[1.3003449e-12]
```
Output with SciPy 1.8.0 (needs at least Python 3.8):
```python
1.3003448967631297e-12
```
> [demos.linear_optimization] use floats for objective functions

- Makefile
- docs/source/developer_docs.md
- requirements-ci.txt
I inserted a hint on installing the `requirements-ci.txt` for checking the code style in `developer_docs.md`. I tried to be brief not to uselessly extend the document. If you have an idea how to shorten it, feel free to alter it. If I'm not mistaken, `pep8` was missing in the requirements list?
> Remark on requirements-ci.txt in developer_docs.md

- src/pymor/core/pickle.py
This actually passes the `protocol` variable to the respective pickler.
> fix pickling to respect specified protocol

- src/pymor/models/iosys.py
- src/pymortests/iosys_save_load.py
Some SLICOT benchmarks do not give the C matrix and it is assumed to be B^T (e.g., MNA benchmarks) and some store some of the matrices using `int16` or `uint8` dtype (MNA, beam, build, eady, fom, heat-cont, heat-disc, pde, peec).
(Orr-Som benchmark is special; it does not provide either B or C.)
> Improve `LTIModel.from_mat_file`

- src/pymor/algorithms/rand_la.py
This PR will fix some typos in the docstring and logger of `random_generalized_svd`. I also had a read of the cited paper and I think the new docstring is easier to understand.
> `random_generalized_svd` dostring fixes

- src/pymor/algorithms/gram_schmidt.py
- src/pymor/discretizers/builtin/grids/interfaces.py
By throwing out vectors whose norm exactly equals the tolerance, we avoid division by zero when `atol = 0`.
> Avoid division by zero in gram_schmidt

- docs/source/getting_started.md
- docs/source/release_notes/0.4.rst
- docs/source/technical_overview.rst
- docs/source/tutorial_external_solver.md
- setup.py
- src/pymor/algorithms/bernoulli.py
- src/pymor/analyticalproblems/expressions.py
- src/pymor/bindings/dunegdt.py
- src/pymor/discretizers/builtin/domaindiscretizers/gmsh.py
- src/pymor/discretizers/builtin/gui/qt.py
- src/pymor/models/symplectic.py
- src/pymor/operators/numpy.py
- src/pymor/tools/frozendict.py
- src/pymordemos/elliptic_unstructured.py
- src/pymordemos/unstable_heat.py
- src/pymortests/algorithms/bernoulli.py
- src/pymortests/iosys_add_sub_mul.py
- versioneer.py
I went ahead and replaced most `http://` URLs with `https://`.
Eight instances of `http://` remain.
- MORWiki and SLICOT do not seem to use TLS
- Four instances are in the bib file which I left untouched
- which leaves pyamg.org and the link to NA-digest which both didn't work when I tested them
I also added a missing word while I was at it.
> change URLs to https (and more)

- .ci/conda-env.yml
- dependencies.py
- docs/source/conf.py
- requirements-optional.txt
where wheels are available for it. 
This allows `pip install pymor[full]` to succeed on those system where no DUNE wheels are available.
> [deps] restrict DUNE suggestion to systems

- src/pymor/algorithms/rules.py
- src/pymortests/algorithms/simplify.py
Instead of allowing arbitrary Mappings or Iterables, only dicts, tuples and list are allowed as containers.
This avoids unwanted side-effects like iterating over a numpy array.
Fixes #1656.
> Make RuleTable.get_children more restrictive

- src/pymor/algorithms/genericsolvers.py
- src/pymor/algorithms/symplectic.py
- src/pymor/bindings/scipy.py
- src/pymor/discretizers/builtin/gui/gl.py
- src/pymordemos/parametric_heat.py
- src/pymordemos/thermalblock_simple.py
- [gui] fix non-int input for text width draw
- [demos] fix deprecated `ListVectorArray._list` usage
- [demos] silence "too many open figures" warning
- [algorithms] `scipy.linalg.basic` is deprecated, now private namespace
- [scipy] explicitly set `atol='legacy'` for bicgstab
- [symplectic] fix deprecated usage of `BlockVectorArray.block`
> Fix Issue #1661

- AUTHORS.md
- docs/source/bibliography.bib
- docs/source/substitutions.py
- src/pymor/algorithms/to_matrix.py
- src/pymor/models/iosys.py
- src/pymor/models/transforms.py
- src/pymortests/transforms.py
I have this code here that I would like to integrate in order to have Bilinear Transformations of LTI-systems similarly to Matlabs `c2d` and `d2c` commands. So far I have implemented Tustin's method and I am looking to extend this to higher order approximations in the future. 
I am particularly interested in arbitrary Moebius substitutions of the frequency argument (not only the bilinear transformation) which is why I chose a more functional approach and implemented a `MoebiusTransform` operator directly. Maybe this can be used elsewhere in the future (I have added the CayleyTransform as an inspiration).
I would love to get some feedback, IMO the method `LTIModel.moebius_substitution` could use some improvement in both naming and the code. The method substitutes the frequency argument …
> Moebius Transform Operator and Tustin's method for LTI-Systems

- AUTHORS.md
- src/pymor/models/iosys.py
Following the discussion in #1570, this PR adds the ability to supply preset values for nearly all attributes of `LTIModel` as a dict of `presets` that can be passed to the constructor as keyword argument. If an attribute is preset this way, no computations are performed and the preset value is returned instead.
The following attributes can be set:
`poles`, `c_lrcf`, `o_lrcf`, `c_dense`, `o_dense`, `hsv`, `h2_norm`, `hinf_norm`, `l2_norm` ,`linf_norm` as well as `fpeak` (the frequency at which `linf` is attained).
Todos:
> preset values for `LTIModel`

- src/pymor/discretizers/builtin/cg.py
- src/pymordemos/parabolic_mor.py
Two issues were cleared:
1.) With mat0 and h0_1_mat, two matrices had identity for Dirichlet DOFs, i.e. mat0 was dispensable.
2.) A new mass matrix was generated with zero rows for the Dirichlet DOFs respecting the algebraic equations in time-integration.
The issue can be tested by shifting the Dirichlet BC and the initial value by one
```
bc = df.DirichletBC(V, df.Constant(1.), dirichlet_boundary)
u0 = df.project(initial_data, V).vector() + 1
```
and looking at the Dirichlet values with 'Plot over line' in Paraview
> Fix non-hom. Dirichlet BC for parabolic MOR demo

- src/pymor/algorithms/to_matrix.py
- src/pymor/bindings/pymess.py
- src/pymortests/to_matrix.py
- ignores `PendingDeprecationWarning` from `pymess`
- replaces `np.bmat` with `np.block`
On my computer, this reduces the number of warnings raised by `pytest src/pymortests` from 55051 to 399.
> Remove np.matrix warnings

- conftest.py
- src/pymor/core/config.py
- src/pymortests/docker_ci_smoketest.py
- [tests] ensure we get no dune import warnings in our CI
- [config] bump supported dune versions
> 2022.1.x dune versions

- requirements-optional.txt
- src/pymor/bindings/slycot.py
I saw that a new slycot version was released last week. It includes my bugfix PR for an incorrectly set `ldwork` variable in the discrete-time case. If we update our requirements to version 0.5.0 or higher, we can remove the workaround bugfix from our bindings.
The new release does not seem to contain drastic changes, although they have switched to a different license and version of SLICOT and there seems to be an issue with NumPy 1.23.0 (but not 1.23.1 and greater).
https://github.com/python-control/Slycot/releases/tag/v0.5.0
> branch off new slycot version

- src/pymor/parameters/functionals.py
This pull request should fix issue #1744.
> Fixes #1744

- src/pymor/operators/interface.py
This PR fixes some minor errors in the default implementation of `Operator.apply_inverse` via `to_matrix`. Further, for a non-parametric operator the result is cached internally such that repeated calls to `apply_inverse` can benefit from an already computed LU decomposition stored in `NumpyMatrixOperator`.
> Improve Operator.apply_inverse default impl via to_matrix

- src/pymor/discretizers/builtin/gui/qt.py
`logger.warn` is deprecated. This is the only instance I could find.
> small deprecation fix

- docs/source/tutorial_unstable_lti_systems.md
- docs/source/unstable_heat_equation.py
- src/pymor/models/iosys.py
- src/pymor/reductors/bt.py
- src/pymordemos/heat.py
So far, only the Gramians from `BTReductor` were cached, which was done by the `LTIModel`.
> Add caching for LQGBTReductor and BRBTReductor Gramians

- src/pymor/algorithms/rules.py
Returning a list instead of a set (as was done previously) ensures a deterministic order of children. 
In particular, a deterministic order is required to ensure that in the call to preassemble in `discretizers.fenics.cg.discretize_stationary_cg` all operators are assembled in the same order on all MPI ranks.
> Let RuleTable.get_children return a list

- docs/source/_static/pymor.css
- src/pymor/core/defaults.py
~This PR removes the ugly looking white background of the plots in our documentation and instead makes the background color and alpha value changeable via defaults. Further,~ a small mistake in the border color of the admonitions, resulting from our customizations of the style sheets, is fixed. The last commit fixes a small typo in the documentation of `core/defaults.py`.
> Some small improvements of the documentation

- AUTHORS.md
- src/pymor/reductors/dwr.py
- src/pymordemos/output_error_estimation_with_dwr.py
- src/pymortests/demos.py
This PR supersedes #1418. We introduce a complete new `DWRCoerciveRBReductor` (not as subclass of `CoerciveRBReductor`) which is only used for the dual weighted residual (DWR) or primal-dual residual approach as discussed in [haa17], section 2.4. 
The `DWRCoerciveRBReductor` can be used for using the corrected output functional (only available for linear outputs for now) as well as the better output estimation. Furthermore, the reductor can be used to construct the corresponding dual models.
In the demofile `output_error_estimation_with_dwr`, we compare this approach to the standard output estimation from #1474.
> DWR reductor for output estimation with primal-dual approach

- src/pymor/parameters/base.py
- src/pymortests/parameters/parameters.py
The method implemented here will allow any `ParameterSpace` to project any given parameter of suitable dimensions into its respective parameter ranges. This feature will in particular come in handy when trying to implement optimization algorithms such as TR-RB because of the often imposed rectangular parameter bounds.
One small problem that needs to be addressed is the nomenclature of the method: usually `project` methods call upon generalizable `ProjectionRules` as these methods refer to the projection of operators, etc. onto subbases and the like. Here however no such behaviour is intended because of the simple use case (we only ever want to "project" a parameter when in use with a `ParameterSpace`). If you've got any better suggestions for naming the method, please let me know or amend …
> Allow ParameterSpace to project parameters into its ranges

- src/pymor/operators/numpy.py
This aligns the behavior of `apply_inverse` for the dense case with the sparse case, i.e. the inverse of a dense matrix is kept for subsequent solves.
> keep factorization of dense numpy matrices for subsequent solves

- src/pymortests/algorithms/samdp.py
So far our tests check whether poles computed with `samdp` are more dominant than other poles computed with `scipy.linalg.eig`. In theory however, there is really no guarantee for this (e.g., if we start with bad initial shifts resulting in convergence to "locally dominant poles", but the most dominant poles might be very far away and thus out of reach for the method). In practice this rarely happens but since test failures occur every now and again I adjust the test here, such that we only check whether the computed poles are actually eigenvalues rather than checking some (rather arbitrary) dominance criterion.
> Adjust `samdp` tests

- conftest.py
- src/pymortests/algorithms/basic.py
- src/pymortests/algorithms/bernoulli.py
- src/pymortests/algorithms/ei.py
- src/pymortests/algorithms/eigs.py
- src/pymortests/algorithms/lyapunov.py
- src/pymortests/algorithms/projection.py
- src/pymortests/algorithms/rand_la.py
- src/pymortests/algorithms/riccati.py
- src/pymortests/algorithms/samdp.py
- src/pymortests/algorithms/sylvester.py
- src/pymortests/algorithms/symplectic.py
- src/pymortests/algorithms/to_matrix.py
- src/pymortests/analyticalproblems/function.py
- src/pymortests/complex_values.py
- src/pymortests/demos.py
- src/pymortests/fixtures/function.py
- src/pymortests/fixtures/operator.py
- src/pymortests/fixtures/parameter.py
- src/pymortests/models/model.py
- src/pymortests/operators/block.py
- src/pymortests/operators/low_rank_op.py
- src/pymortests/operators/operators.py
- src/pymortests/strategies.py
- src/pymortests/tools.py
- src/pymortests/vectorarray.py
While we use the `derandomize=True` setting of hypothesis for all test runs except for the `ci_large` profile, no care is taken of pyMOR's or numpy's global random state. This PR introduces an autouse fixture which resets both random states before executing a new test function.
Further I did some cleanup and removed all manual seeding in the test functions/fixtures.
I hope this finally puts an end to suddenly appearing CI test failures when new test are added.
> Reset random state for each test

- docs/source/tutorial_bt.md
- docs/source/tutorial_lti_systems.md
- src/pymor/models/transfer_function.py
- src/pymor/tools/plot.py
- src/pymordemos/delay.py
- src/pymordemos/heat.py
- src/pymordemos/parametric_delay.py
- src/pymordemos/parametric_heat.py
- src/pymordemos/parametric_string.py
- src/pymordemos/parametric_synthetic.py
- src/pymordemos/phlti.py
- src/pymordemos/string_equation.py
- src/pymordemos/unstable_heat.py
- src/pymortests/tools.py
The goal here is to add functionality to adaptively sample the transfer function given the boundaries of the frequency interval of interest (see #389):
- adds an `adaptive` method to `pymor.tools.plot`,
- extends `freq_resp` to support adaptive sampling for `bode_plot` and `mag_plot`,
- updates `bode`, `bode_plot`, and `mag_plot` to use adaptive `freq_resp`,
- updates sys-mor demos and tutorials to use adaptive plots.
Adaptive sampling seems to be working well on Penzl's three-peak example:
```python
import matplotlib.pyplot as plt
import numpy as np
import scipy.sparse as sps
from pymor.models.iosys import LTIModel
A1 = np.array([[-1, 100], [-100, -1]])
A2 = np.array([[-1, 200], [-200, -1]])
A3 = np.array([[-1, 400], [-400, -1]])
A4 = sps.diags(np.arange(-1, -1001, -1))
A = …
```
> Adaptive frequency response

- docs/source/tutorial_lti_systems.md
- src/pymor/algorithms/timestepping.py
- src/pymor/analyticalproblems/expressions.py
- src/pymor/analyticalproblems/functions.py
- src/pymor/models/basic.py
- src/pymor/models/interface.py
- src/pymor/models/iosys.py
- src/pymor/models/transfer_function.py
- src/pymor/operators/constructions.py
- src/pymor/operators/numpy.py
- src/pymor/parameters/base.py
- src/pymortests/models/model.py
This PR is similar to #1054 but is limited to `solve` and `output`. I would be for adding impulse response and step response once #1305 is merged, as I believe that it would be expected that they avoid computing the whole solution trajectory first (the same could be said for `output`, but at least it is consistent with `InstationaryModel`).
I opened this as a draft PR since there are a few issues worth discussing before merging:
1. For now, `solve` and `output` expect the input as a callable (via the `input` keyword argument). Since caching doesn't support callables as parameters, I had to implement `_compute` to avoid caching. Is this fine, or do we want a way to enable caching? One option would be using `ExpressionParameterFunctionals`, but, comparatively, defining a lambda function is …
> Enable `solve` and `output` for `LTIModel`

- src/pymor/discretizers/builtin/cg.py
- src/pymor/discretizers/builtin/fv.py
I just came across this tiny (but potentially very costly) detail in our discretizers: Let's assume that we have a parameter $\mu$ that only acts on a small local domain $\omega$. Then, for instance, the respective analytic function would be something like a characteristic function on it. In turn, the (globally defined) stiffness matrix $A_\mu$ has a lot of zero entries not just because of the natural sparsity pattern from the discretization, but also because the analytic function is zero almost everywhere.
Currently, our discretizers do not track this and still store all zeros in the matrix.
In this PR, I simply do another `eliminate_zeros` call on all these matrices, to use as less memory as possible. For large matrices this then will also affect the time that a matrix-vector …
> [discretizers.builtin] Eliminate zeros of sparse matrices

- .github/workflows/automerge.yml
This workflow only enables github's own auto-merge function
and is intended for the requirements update functionality
in #1845. Only PRs labeled "automerge" will be considered.
> [ci] adds an automerge workflow

- .ci/conda-env.yml
- .github/workflows/conda_tests.yml
- dependencies.py
- requirements-ci.txt
- src/pymortests/strategies.py
This is blocked until https://github.com/conda-forge/hypothesis-feedstock/issues/730 is resolved, which most likely means until after https://github.com/agronholm/exceptiongroup had its first non-RC release
This will need a rebase after #1701 is merged.
> Removes deprecated complex Hypothesis strategy

- src/pymor/operators/constructions.py
I could do `A = IdentityOperator(2)` without error. This PR adds assertions for the space argument (also for `ConstantOperator`).
> add assertions to `IdentityOperator`

- .ci/gitlab/test_pip_installed.bash
See error [here](https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/1338743#L1632).
I don't understand what is affecting file ownership, but I think it is ok to just silence the error.
> [CI] silence dubious ownership git error

- src/pymordemos/era.py
- src/pymortests/demos.py
As mentioned in #1516, the `era` and `aaa` reductors are not currently tested. I have added their demos to the tests.
> add era and dd_parametric_heat to demo tests

- CONTRIBUTING.md
- docs/source/developer_docs.md
This moves the code style section from `CONTRIBUTING.md` to developer docs (along with some minor improvements in both).
There should probably be a link to `CONTRIBUTING.md` somewhere (e.g., `README.md`), but that could be a different issue/PR.
> Contributing file and developer docs

- .pre-commit-config.yaml
Use the comment `pre-commit.ci autofix` to trigger an autofix.
> Disable pre-commit.ci autofixes

- .github/markdown_link_check_config.json
- README.md
This PR is to close #1936 and #1934 and fix some other issues:
> Edit README

- src/pymor/models/transfer_function.py
- src/pymortests/models/iosys_add_sub_mul.py
Fixes #1918.
I'm not sure how to use `Functions` internally without removing the `parameters` input from `TransferFunction.__init__`, so I just used `Parameters.of` to find new parameters.
> Fix parametric transfer function operations

- docs/source/tutorial_basis_generation.md
In `main` and `2022.2.0`, the error plots in the basis generation tutorial [no longer](https://docs.pymor.org/2022-2-0/tutorial_basis_generation.html) show a [nice](https://docs.pymor.org/2022-1-1/tutorial_basis_generation.html) error decay. The reason for this are the changes in random number generation that entered `2022.2.0`. Indeed, when using the training and validation parameters generated by `2022.2.0` but using `main` otherwise, the original figures are exactly reproduced. Thus, the conclusion is that the 100 validation parameters selected in `2022.2.0`, by chance, did not approximate the entire solution manifold very well.
To mitigate this issue, I have reduced the number of block to 3 by 2, making the problem a little easier to handle. Further, to make the influence of the …
> Improve basis generation tutorial

- .markdownlint.yml
- docs/RELEASE_CHECKLIST.md
- docs/source/developer_docs.md
- docs/source/getting_started.md
- docs/source/tutorial_basis_generation.md
- docs/source/tutorial_bt.md
- docs/source/tutorial_mor_with_anns.md
- logo/README.md
- set ATX style for headers (`#` instead of dashes)
- allow `img` HTML tags everywhere
- disallow multiple blank lines
- fix issues introduced by new rules
- add "Markdown Style" section to developer docs
> Edit and document Markdown rules

- docs/source/index.rst
I removed the link to `scipy.org`, since it no longer points to the scientific computing stack.
> Update pyMOR summary in the docs

- docs/source/bibliography.bib
I noticed that the BBG19 source still referenced an arXiv preprint while a Springer publication of the same source has been published just last year. This PR updates the `bibliography.bib` entry to the Springer publication.
> Update BBG Citation to Springer Publication

- docs/RELEASE_CHECKLIST.md
- docs/RELEASE_PROCESS.md
These are the changes based on the recent bugfix release:
- ~~replace `markdownlint-cli2` pre-commit hook with `pymarkdown` hook (I had issues with old nodejs version on ubuntu)~~
- note steps that can be skipped for bugfix releases
- remove ResearchGate announcement (ResearchGate projects are getting removed, see [here](https://www.researchgate.net/researchgate-updates/retiring-projects))
- combine GitHub release and GitHub Discussions announcement (there is a checkmark that can be selected before publishing the GitHub release)
- add docs and conda-forge checks
In addition to NA Digest, we could also make announcements in the MoRePaS mailing list. Any comments on this?
> Edit release checklist

- src/pymor/models/neural_network.py
`.detach()` is preferred over `.data` and it might happen in the future that `.data` is removed. The behavior of the code in our case should not change and this is just to use the standard way recommended by PyTorch.
> Replace `.data` by `.detach()` in neural network models

- src/pymor/parameters/base.py
- src/pymortests/parameters/parameters.py
Hello, here is my code regarding the #1598. 
```sample_logarithmic_randomly()``` is just like a random but scaled on a log scale.
```sample_logarithmic_uniformly()``` does what ```sample_uniformly()``` does but on a log scale.
PS: I'm sorry I cannot add new feature label. Maybe I should have done it before I opened the pr?
> Adding Log Sampling

- AUTHORS.md
- src/pymor/parameters/base.py
- src/pymortests/parameters/parameters.py
This is a continuation of  #1824.
In essence, this makes use of `__array_priority__` as suggested by @pmli.
If there is interest in enabling the internal storage as `np.ndarray`s [as suggested again by @pmli](https://github.com/pymor/pymor/pull/1824#issuecomment-1437347393), I'd be happy to have a look at that. I can imagine however, that this change might have a few consequences further down the line.
> Algebraic ops for Mu instances

- docs/source/bibliography.bib
- src/pymor/reductors/loewner.py
- src/pymordemos/dd_heat.py
- src/pymortests/demos.py
- src/pymortests/reductors/loewner.py
- src/pymortests/reductors/mt.py
This PR implements a reductor based on the Loewner interpolation framework. This is a draft for now because there might be some room for discussion regarding:
1. `_partition_frequencies` is more or less an attempt to generalize the different partitioning choices considered [here](https://pure.mpg.de/rest/items/item_3215398/component/file_3348562/content). In the chapter it seems like frequencies are considered to be complex only (makes sense, although it would be good to at least take 0 into consideration) and also they don't seem to care about keeping complex conjugate pairs together which is something I tried to do in the implementation.
2. There is the `loewner_quadruple` function for all related matrices. However, it maybe makes sense to have separate functions to generate the …
> Loewner Reductor

- src/pymor/algorithms/preassemble.py
Apparently, we forgot about the preassmbly rule for the QuadraticFunctional. So far, the operator is assembled every time it is used.
This should probably enter the release.
> Add rule for preassembling QuadraticFunctional

- src/pymor/analyticalproblems/functions.py
- src/pymor/parameters/base.py
- src/pymortests/parameters/parameters.py
This PR allows to specify time-dependent parameter values with more than one component as a list of scalar valued expression. Also, scalar valued functions are automatically cast to vector-valued functions with shape `(1,)`. For instance, the following is now allowed:
```
Parameters(a=1, b=2).parse(['t[0]', 't[0]*2', 't*3'])
```
For the internal implementation, I have refactored `ExpressionFunction` to inherit from `SymbolicExpressionFunction`, which is instantiated with a symbolic expression object.
Fixes #1396.
> Improve parsing of time-dependent parameter values

- src/pymor/algorithms/timestepping.py
Inspired by #1529, this PR:
- improves IVP documentation
- removes time-stepping functions
- allows iterating over time steps (using a generator function)
> Add iterable time stepping

- src/pymor/algorithms/simplify.py
- src/pymor/models/iosys.py
- src/pymor/reductors/ph/basic.py
- src/pymor/reductors/ph/ph_irka.py
- src/pymordemos/phlti.py
- src/pymortests/algorithms/simplify.py
- src/pymortests/demos.py
- src/pymortests/models/iosys_add_sub_mul.py
- src/pymortests/models/iosys_save_load.py
- src/pymortests/reductors/ph/ph_irka.py
This PR refactors the PHLTIModel to inherit from the LTIModel and extends the PHLTIModel to support Q. Additional a conversion from PHLTIModel with Q to PHLTIModel without Q (Q=I) is implemented.
> Refactorization of PHLTIModel to inherit from LTIModel and support Q matrix

- src/pymor/discretizers/builtin/gui/qt/__init__.py
This PR fixes visualization using the pymor_vis script when there is no `python` executable.
> Use python3 executable to call pymor_vis script

- AUTHORS.md
- src/pymor/models/iosys.py
- src/pymor/reductors/spectral_factor.py
- src/pymordemos/phlti.py
- src/pymortests/reductors/ph/ph_irka.py
- src/pymortests/reductors/spectral_factor.py
This PR implements the method proposed in [[BU22]](#BU22). 
- This PR depends on #1837 and #1847. The method is not depending on PRBT itself, but on other bits included in #1847.
<a id="BU22">[BU22]</a> Tobias Breiten, Benjamin Unger, Passivity preserving model reduction via spectral factorization, Automatica, Volume 142, 2022, 110368, ISSN 0005-1098, https://doi.org/10.1016/j.automatica.2022.110368 (https://www.sciencedirect.com/science/article/pii/S0005109822002187)
> Passivity preserving model reduction via spectral factorization

- src/pymor/bindings/dunegdt.py
- src/pymor/vectorarrays/numpy.py
- src/pymortests/vectorarray.py
This PR ensures that `VectorSpaces` cannot be instantiated with non-integer dimensions.
Fixes #2062.
Alternative implementation to #2063.
> Integer-valued VectorSpace dimensions 2

- .github/actions/miniconda_tests/action.yml
provision-with-micromamba is abandoned. Thus, we use setup-micromamba instead.
> Use setup-micromamba instead of provision-with-micromamba

- src/pymor/core/config.py
- src/pymor/discretizers/builtin/gui/jupyter/__init__.py
- src/pymor/discretizers/builtin/gui/jupyter/logging.py
- src/pymor/parallel/ipython.py
These are some leftovers from some last-minute work for the CSE minitutorial.
- The unused `distcretizeris.builtin.gui.jupyter.progress_bar` is removed.
- `is_jupyter()` returns `True` when running under `pyolite`.
- the `IPYTHON` config item is split into `IPYTHON` and `IPYPARALLEL`.
> jupyterlite fix / config improvements / remove progress bar

- src/pymordemos/phlti.py
The MSD model in the PHLTI demo so far does not document the parameter `m` in the docstring of `msd`, but just in the arguments of `main`.
> Add missing argument docstring in PHLTI Demo

- README.md
After the removal of a bunch of optional dependencies from the conda recipe, mamba is no longer necessary to install pyMOR.
> Remove mention of mamba

- src/pymor/algorithms/svd_va.py
While preparing #2114, I came across deprecation warnings for the call to `eigh` from `scipy.linalg`. These are fixed in this pull request.
> Fixed deprecations in call to scipy `eigh`

- src/pymortests/base.py
- replaces [`pkg_resources`](https://setuptools.pypa.io/en/latest/pkg_resources.html) with [`importlib.resources`](https://docs.python.org/3/library/importlib.resources.html) (see [migration guide](https://importlib-resources.readthedocs.io/en/latest/migration.html))
pytest raises warnings about `pkg_resources`. This change fixes this for me locally.
> Remove deprecated pkg_resources

- .mailmap
- docs/source/technical_overview.rst
- docs/source/tutorial_projection.md
Updates technical overview in docs to match better reflect current state of reductors.
> docs | fix reference in technical_overview.rst

- docs/source/getting_started.md
Without the download links added in this PR, the jupyter notebook for `getting_started.md` isn't built, which causes the binder link to fail.
> Ensure that notebook for getting_started.md is built

- docs/source/conf.py
- docs/source/environment.md
- src/pymor/core/base.py
- Remove the unused `_implements_reduce` attribute of `ImmutableObjects`
- Do not copy method docstrings from base classes anymore. `help` and IPython's `?` nowadays automatically show to base class docstring.
- Remove `PYMOR_WITH_SPHINX` environment variable, which was only used to disable the copying of docstrings.
> Remove unneeded metaclass features

- src/pymor/reductors/parabolic.py
To check the change, run, e.g.,
```bash
python -W always parabolic_mor.py pymor greedy 2 3 1
```
Edit: this happens with NumPy 1.25.
> Fix NumPy scalar conversion DeprecationWarning in ParabolicRBEstimator

- src/pymor/models/iosys.py
- src/pymortests/models/iosys_norm.py
This is a proposed fix to issue #2133.
> Fix `return_fpeak` handling in `pymor.models.iosys`

- .ci/gitlab/docs_deploy.bash
- docker/Dockerfile.binder.tocopy
- docs/source/try_on_binder.py
Due to the sheer size of `pymor/docs`, launching binder takes very long or fails as the entire repo seems to be cloned.
With this PR, binder configuration is now deployed to a separate `pymor/binder` repo and the tutorial notebooks are pulled into the image using wget.
> Deploy binder config to pymor/binder

- src/pymor/algorithms/rules.py
As asciitree seems unmaintained, we just pretty print the tree in `pymor.algorithms.rules.print_children` ourselves.
Supersedes #2178.
Fixes #2098.
> Remove asciitree dependency in print_children

- src/pymor/algorithms/adaptivegreedy.py
- src/pymor/algorithms/bfgs.py
- src/pymor/algorithms/ei.py
- src/pymor/algorithms/error.py
- src/pymor/algorithms/greedy.py
- src/pymor/algorithms/newton.py
- src/pymor/analyticalproblems/elliptic.py
- src/pymor/discretizers/builtin/cg.py
- src/pymor/discretizers/builtin/fv.py
- src/pymor/discretizers/fenics/cg.py
- src/pymor/discretizers/skfem/cg.py
In [a discussion](https://github.com/pymor/pymor/pull/2027#discussion_r1288654992) for the PHDMD PR #2027, @pmli mentioned that the indentation for the dictionary key listings resemble quotes. To avoid this, I have unindented all the occurrences I am currently aware of. If there are any other docstrings where this occurs, please let me know.
> Unindent dictionary key listings to avoid confusion with quotes

- docs/Makefile
- docs/source/jupyter_init.txt
- docs/source/myst_code_init.py
- src/pymor/__init__.py
- src/pymor/discretizers/builtin/gui/jupyter/__init__.py
- src/pymor/discretizers/builtin/gui/jupyter/logging.py
- src/pymor/tools/jupyter.py
- Use monospace font and improve spacing in log output.
- Move code to `tools.jupyter`.
- Autoload extension when `is_jupyter()` is true.
> Improve jupyter logging widget

- src/pymor/models/iosys.py
- src/pymor/models/transforms.py
- src/pymortests/models/transforms.py
This PR fixes the normalization of `MoebiusTransformations` and improves the `LTIModel.moebius_substitution` method to avoid the use of `InverseOperator`.
> fix `MoebiusTransformation`

- pyproject.toml
- src/pymor/algorithms/basic.py
- src/pymor/algorithms/ei.py
- src/pymor/algorithms/eigs.py
- src/pymor/algorithms/lrradi.py
- src/pymor/algorithms/rand_la.py
- src/pymor/models/examples.py
- src/pymor/operators/constructions.py
- src/pymor/operators/numpy.py
- src/pymor/reductors/spectral_factor.py
- src/pymortests/algorithms/rand_la.py
- src/pymortests/operators/operators.py
- src/pymortests/reductors/spectral_factor.py
- src/pymortests/vectorarray.py
Closes #1052.
Since #1603, `NumpyMatrixOperator` caches the LU factorization and checks the condition number. To enable faster `apply_inverse`, especially for small matrices, this PR adds `check_finite` and `check_cond` default in `NumpyMatrixOperator.apply_inverse`.
Regarding the choice between NumPy and SciPy linalg routines, it seems that SciPy is used predominantly (see the two `grep`s below, which was enabled by forbidding `import scipy` and `from numpy.linalg import`). Therefore, this PR replaces NumPy's `solve`, `lstsq`, `inv`, `qr`, `eigvals` by SciPy's (in `src/`).
---
`NumpyMatrixOperator` uses `lu_factor` and `lu_solve`.
Places where `numpy.linalg.solve` is used:
```console
$ grep -rn 'np.linalg.solve(' src/
src/pymortests/operators/operators.py:503:    u = np.linalg.solve(O.T, …
```
> Add `check_finite` and `check_cond` in `NumpyMatrixOperator` and use SciPy solvers elsewhere

- src/pymor/bindings/pymess.py
- src/pymor/bindings/slycot.py
- src/pymortests/algorithms/lyapunov.py
- src/pymortests/algorithms/riccati.py
- tests for matrix mutation in Lyapunov and Riccati solvers
- fixes the mutation issue with `sg03ad` and `sb02od`
- fixes `Deprecated` import in `pymess` bindings
Closes #2168.
> Fix Slycot matrix mutation

- src/pymor/models/iosys.py
- src/pymor/models/transfer_function.py
- src/pymor/reductors/interpolation.py
- src/pymortests/models/iosys_add_sub_mul.py
This PR is a very crude proposal for #2122 I will continue working on this in the next few days.
Current problems:
> `Operator`-valued functions in `FactorizedTransferFunction`

- src/pymor/models/transfer_function.py
Closes #2143. As far as I can tell, `TransferFunction` currently only supports `h2_norm`, but additional keys can be added as in `LTIModel`.
This also touches the second checkbox under the $H_2$ norm section in #391.
> Add H2 norm preset for `TransferFunction`

- src/pymor/discretizers/builtin/fv.py
- src/pymor/discretizers/builtin/grids/interfaces.py
- src/pymortests/discretizers/affine_grid.py
- src/pymortests/discretizers/grid.py
- renames methods with "neighbour"
> Fix "neighbor" typo

- Makefile
This PR proposes a default `help` target as mentioned in issue #2097. This target is self-documenting in the sense that any targets can be included in the generated help message by documenting it as follows:
```make
<target>: [dependencies] ## Target documentation
```
I've added basic docstrings for the targets where I could easily infer that they needed documentation and what their intended effects are, but this leaves out a number of other targets. Before converting this to a full PR, I would like some feedback on which targets still need documentation, as well as how to improve the current documentation.
Furthermore, I would like some feedback with regards to the formatting of the individual lines. Is some more spacing necessary? Should it include colour?
> Self-documenting help target for Makefile

- src/pymor/models/transforms.py
- src/pymortests/models/transforms.py
I just found an error in the classmethod that constructs a Moebius transformation from three points. The pre-images and images were interchanged. I've fixed it and made the docsting more descriptive to avoid confusions.
@lbalicki Maybe we can still add this to the next release although we are in soft-freeze. If you agree, feel free to change the milestone.
> fix misleading `from_points` classmethod

- src/pymor/algorithms/riccati.py
- src/pymor/bindings/scipy.py
- src/pymor/bindings/slycot.py
- src/pymor/models/iosys.py
- src/pymor/reductors/spectral_factor.py
- src/pymordemos/phlti.py
- src/pymortests/algorithms/riccati.py
- [riccati] Add `solve_pos_ricc_dense` and bindings for `scipy` and `slycot`
- [iosys] add `pr_c_dense` and `pr_o_dense` Gramians
- [spectral_factor] use `pr_o_dense` Gramian instead of `pr_o_lrcf` because we need the full dense solution anyway
- [iosys] use dense solvers in `from_passive_LTIModel` instead of lrcf ones
- [iosys] add `to_abcde_matrices` to `LTIModel` such that the standard ABCDE matrices can still be exported if a child class overrides `to_matrices` (like for instance `PHLTIModel`)
- [iosys] add `format` parameter to `to_matrices` methods
- [spectral_factor] use `LTIModel.to_abcde_matrices` instead of converting the matrices individually
> Refactoring pH and matrix solvers 

- src/pymor/analyticalproblems/expressions.py
- src/pymor/analyticalproblems/functions.py
- src/pymor/core/cache.py
- src/pymor/parameters/base.py
Classes can now implement `_reduce_cache_key` to make them viable arguments for cached methods. This is used to allow time-dependent parameter values as arguments.
Fixes #1810.
> Allow time-dependent Mus as arguments of cached functions / make cache key generation more flexible

- pyproject.toml
This addresses #2205 until numpy 2 support is tested in CI.
> Pin numpy<2

- docs/source/tutorial_builtin_discretizer.md
- src/pymor/analyticalproblems/functions.py
- src/pymor/analyticalproblems/text.py
- src/pymortests/analyticalproblems/function.py
- src/pymortests/fixtures/function.py
This adds the same features as #2050:
- `BitmapFunction.__init__` now expects a `bitmap` numpy array instead of a filename. (The old interface is still supported but deprecated.)
- `BitmapFunction.from_file` is used to load `bitmap` from a file and instantiates a `BitmapFunction` with it.
- `BitmapFunction.random` creates a random `bitmap` and instantiates a `BitmapFunction` with it.
I think this approach is preferable over the subclassing approach in #2050, as it is simpler and, IMHO, there is no need to differentiate different kinds of initialization via the function's type. Also, I really didn't like the name `DataFieldFunction`, but couldn't find a better one.
> Add 'from_file' and 'random' factory functions to BitmapFunction

- AUTHORS.md
- src/pymor/models/interface.py
- src/pymor/models/iosys.py
This PR will enable the computation of the outputs of an `LTIModel` given some inputs.
The `impulse_resp` and `step_resp` methods are refactored to call `LTIModel._compute`. This also fixes the bug where `step_resp` would not be scaled with the `sampling_time` and neglected `D`.
> `LTIModel` forced response computation

- src/pymor/models/transfer_function.py
This fixes a bug in `FactorizedTransferFunction` where there was an unnecessary `conj`. The issue only occurs for complex system matrices and if `dim_input > dim_output`. Minimal example to make the issue appear:
```
import numpy as np
from pymor.models.iosys import LTIModel
A = np.array([[1]])
B = np.array([[1j, 1]])
C = np.array([[1j]])
fom = LTIModel.from_matrices(A,B,C)
fom.transfer_function.eval_tf(1j) - (C @ np.linalg.solve(1j - A, B))
```
> Bug Fix in FactorizedTransferFunction

- src/pymor/discretizers/builtin/grids/interfaces.py
Make two `ReferenceElements` the equal if they are of the same type.
This fixes an issue with `discretizers.builtin.cg.LagrangeShapeFunctions` where the `ReferenceElement` instances defined in `discretizers.builtin.cg.grids.referenceelements` are used as keys: When a `Grid` is pickled and unpickled, it obtains a new `ReferenceElement` instance as an attribute, which no longer can used to look up shape functions in the `LagrangeShapeFunctions` dict. In particular this happens when `pymor.parallel` is used.
@niklasreich, this should fix the issue you were having.
> Implement __eq__, __hash__ for ReferenceElement

- .ci/gitlab/docs_housekeeping.sh
- .ci/gitlab/docs_makeindex.py
- .ci/gitlab/docs_update_versions.py
This adds the housekeeping scripts executed on docs.pymor.org (every five minutes ATM). After this PR has been merged, the scripts will be executed from a git checkout of the pyMOR repo such that changes here will be automatically deployed.
> Add housekeeping scripts for docs.pymor.org

- src/pymor/vectorarrays/numpy.py
numpy.ndarray.astype copies data even if the specified dtype is the same as the arrays dtype
e.g.
A.scal(2) or A.axpy(-1, B) where A and B are both NumpyVectorArray's with dtype 'float64' results in A being copied because '2' and '-1' are not of the same dtype
[https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html](
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html)
Fixes #2259.
> fix to prevent unnecessary copys in NumpyVectorArrayImpl functions

- src/pymor/models/iosys.py
For models with parameters (for instance an instationary model stemming from a PDE discretization that has been converted into an LTI system), it might be useful to be able to call `to_matrices` for a particular parameter.
Any thoughts on the usefulness of such a possibility @lbalicki, @pmli? Before changing also the other models in iosys (and adding documentation of course), I would like to hear your opinion. Maybe my use-case is too rare to justify official support for this.
> Allow `to_matrices` to accept parameter

- src/pymor/core/defaults.py
967bdcd exposed a bug in `DefaultContainer`: 
As `DefaultContainer` implements `__getitem__`, Python thinks it is a sequence. So `for k in _default_container:` calls `_default_container[0]` and so on.
This PR properly implements `__iter__` to fix this bug.
> Make DefaultContainer iterable

- .ci/gitlab/ci.yml
Do not upload coverage reports to codecov for weekly CI runs, as coverage should depend on standard CI runs. Also, the current job description was broken.
Also prevent 'tag docker images' from running in weekly pipelines.
> Remove  coverage upload for weekly CI runs

- docs/source/tutorial_optimization.md
- src/pymor/algorithms/bfgs.py
- src/pymor/algorithms/error.py
- src/pymor/algorithms/greedy.py
- src/pymor/algorithms/tr.py
- src/pymor/models/basic.py
- src/pymor/models/interface.py
- src/pymor/models/iosys.py
- src/pymor/models/mpi.py
- src/pymor/models/neural_network.py
- src/pymor/reductors/coercive.py
- src/pymor/reductors/dwr.py
- src/pymor/reductors/parabolic.py
- src/pymordemos/linear_optimization.py
- src/pymordemos/output_error_estimation.py
- src/pymordemos/output_error_estimation_with_dwr.py
- src/pymortests/parameters/mu_derivatives.py
- `estimate_error` is required to always return a 1D NumPy array, where the index corresponds to time. For time-independent problems, the array always has length 1.
- `estimate_output_error` always returns a 2D numpy array, where axis 0 corresponds to time and axis 1 corresponds to the output component.  The `return_vector` parameter is removed.
- In order to have consistent behavior for time-dependent models, the `solution_d_mu` compute option now returns a dict of the form `{(parameter, index): sensitivity}` instead of appending solution sensitivities for different parameter indices to a single array. The value of `solution_d_mu` can now either be `True` to compute all sensitivities or a sequence of tuples `(parameter, index)` to select the parameters for which to compute sensitivities. …
> Simplify and clarify Model interface

- .mailmap
- AUTHORS.md
- docs/source/bibliography.bib
- docs/source/substitutions.py
- src/pymor/algorithms/chol_qr.py
- src/pymor/algorithms/cholesky_qr.py
- src/pymor/algorithms/eigs.py
- src/pymortests/algorithms/chol_qr.py
Adds the Cholesky based QR algorithm from [this paper](https://epubs.siam.org/doi/epdf/10.1137/18M1218212) with an oblique inner product.  Shifts are applied if necessary (see Algorithm 4.1 in the paper).
> shifted Cholesky QR algorithm

- _layouts/default.html
Thanks to @TiKeil for noticing that we still link to the old pyMOR school website.
> Update link to pyMOR school website

- src/pymor/algorithms/gram_schmidt.py
When renaming the `compute_R` argument to `return_R` one instance was missed in the docstring. This is fixed here.
> docstring fix for `gram_schmidt`

- src/pymor/algorithms/rand_la.py
The general convention in pyMOR is that the 'left' product should come before the 'right' product in the argument list.
> Flip range_product and source_product args of RandomizedRangeFinder

- pyproject.toml
- requirements-ci-current.txt
- src/pymor/analyticalproblems/domaindescriptions.py
- src/pymor/analyticalproblems/expressions.py
- src/pymor/analyticalproblems/functions.py
- src/pymor/discretizers/builtin/domaindiscretizers/gmsh.py
- src/pymor/parameters/base.py
Note that with NumPy 2,
```python
np.array(..., copy=False)
```
will raise an error when a copy cannot be avoided. The old 'avoid copy when possible' can be achieved by setting `copy=None`, which won't be accepted by older NumPys. NumPy recommends using `asarray`, which does not have the `ndmin` parameter.
Fixes #2205.
> Support NumPy 2

- .ci/gitlab/docs_update_versions.py
This makes sure that the regex does not match branches containing the version string in their name.
> Fix version regex for selecting release directories on docs.pymor.org

- pyproject.toml
dune-gdt has no wheels for Python>=3.12.
> Remove dune from 'full' extra

- README.md
- docs/source/getting_started.md
Installation instructions in the `README` and the "Getting started" are written for Bash and are not robust in ZSH (default shell in macOS and also popular with some people who use, say, Ubuntu while working at Uni Münster). For example, the command
```shell
pip install pymor[full]
```
leads to the error `zsh: no matches found: pymor[full]`.
This PR updates the installation instructions so that are compatible with ZSH by enclosing `pymor[full]` and similar with single quotes (for consistency with other instructions in these files).
Closes #2326
Similar to the old issue #1427
> Update installation command to be robust in ZSH

- src/pymor/discretizers/builtin/gui/qt/__init__.py
This PR replaces the logic for choosing the name of the Python executable for the visualization subprocess with simple call to `sys.executable`, which is the path to the running Python executable.
**Why?** Previously, choosing `python` on Windows and `python3` otherwise was a bit prone to the following (edge) case.
I start a script using the `python` command (which is a Conda Python on my Ubuntu machine). Then the visualization is started in a subprocess with the command `python3`. However, on my machine somehow, the Linuxbrew python3 was on the higher priority than the Conda one, which leads to the situation when the visualizer starts with a completely wrong Python executable.
> Use for visualizer subprocess the parent Python executable

- src/pymor/__init__.py
- src/pymor/core/config.py
- mpi4py is available as a binary wheel on Windows. When no MPI library is installed `import mpi4py.MPI` will fail with a `RuntimeError`. We now catch this error in `pymor._init_mpi()`.
- `pymor.core.config` checks which fail with an exception different from `ImportError` will now longer cause pyMOR to crash. Instead, we set `HAVE_PACKAGE` to `False` and report 'import check failed' to the user.
Fixes #2344.
> Catch all exceptions in config checks and make _init_mpi() more robust

- src/pymor/parameters/base.py
- src/pymortests/parameters/parameters.py
This adds a `constraints` parameter to `ParameterSpace.__init__` and `Parameters.space`, that allows defining arbitrary inequality constraints in addition to the box constraints specified by the `ranges` parameter. The sampling methods are adapted accordingly.
Fixes #2343.
> Add arbitrary (inequality) constraints to ParameterSpace

- docs/source/technical_overview.rst
- src/pymor/basic.py
- src/pymor/core/cache.py
- src/pymortests/core/cache.py
This add a `print_cached_methods()` function which will list all methods in pyMOR that have been decorated with `@cached`. In addition, all subclasses of `CacheableObjects` are listed, for which caching is enabled by default.
Fixes #2337.
> Add print_cached_methods()

- src/pymor/core/defaults.py
- src/pymor/tools/table.py
- Set the default for `shorten_paths` to zero. This ensures that, by default, users see the exact path that needs to be used in `set_defaults`.
- Hack `format_table` a bit to allow line breaks in long paths at dots.
> Improve default behavior of print_defaults

- src/pymortests/algorithms/bernoulli.py
`test_bernoulli_stabilize` repeatedly causes some CI builds to fail due to a slightly positive eigenvalue caused by a singular A. See for instance
https://zivgitlab.uni-muenster.de/pymor/pymor/-/jobs/4126008
https://github.com/pymor/pymor/actions/runs/10944510114/job/30386549312?pr=2359
With this PR, random dense matrices are used to avoid this issue.
> Fix test_bernoulli_stabilize

- .github/actions/miniconda_tests/action.yml
- src/pymortests/algorithms/samdp.py
- src/pymortests/reductors/mt.py
For a while now, all conda tests silently fail:
https://github.com/pymor/pymor/actions/runs/10944510114/job/30386549312?pr=2359
This PR fixes this by adding the '-e' shell option where a shell is explicitly specified in the job description.
> Make sure failed conda tests actually fail the job

- src/pymor/algorithms/rand_la.py
I would like to add a new [randomized error estimator](https://epubs.siam.org/doi/10.1137/23M1558537) a new `RandomizedERAReductor`. In preparation for that, some changes to the `RandomizedRangeFinder` are needed. I figured it is a good idea to talk about the changes first and then implement the new features once they are agreed upon.
Functionalities that are needed and not currently available are
- ~Storing of the randomly sampled vectors for an efficient leave-one-out error estimator~
- Computation of the R matrix when orthogonalizing the reduced basis
- Allowing the use of `shifted_chol_qr`. For now, I would like to add an option here that can be removed once we have the interface method
- A dedicated `_draw_samples` method such that it can be overwritten by something more efficient …
> `rand_la` tweaks

- src/pymor/algorithms/chol_qr.py
- src/pymortests/algorithms/chol_qr.py
The documentation of the algorithm stated, that it returns the `R` matrix, if `return_R` is set to True. However, there was no option to specify `return_R` and both `Q` and `R` were always returned.
> Add `return_R` flag and respective logic to the `shifted_chol_qr`

- src/pymor/algorithms/rand_la.py
Adds the new `return_R` kwarg from #2383  to the `shifted_chol_qr` call in `rand_la` .
> fix small bug in `rand_la`

- src/pymor/algorithms/timestepping.py
- src/pymortests/algorithms/timestepping.py
Resolves #2310.
Time stepping backwards is now possible by choosing a larger `initial_time` compared to the `end_time`.
> Time stepping backwards in time

- docs/source/substitutions.py
- src/pymor/algorithms/error.py
- src/pymor/algorithms/timestepping.py
- src/pymor/algorithms/tr.py
- src/pymor/core/cache.py
- src/pymor/models/basic.py
- src/pymor/models/interact.py
- src/pymor/models/interface.py
- src/pymor/models/iosys.py
- src/pymor/models/neural_network.py
- src/pymor/operators/constructions.py
- src/pymor/parameters/base.py
- src/pymor/reductors/neural_network.py
- src/pymor/reductors/parabolic.py
- src/pymortests/parameters/parameters.py
- src/pymortests/strategies.py
In #2375 I proposed removing time-dependent parameter values from pyMOR. The main reasons were: 1. to simplify the concept of parameter values to make it suitable for more basic libraries like NiAS. 2. the current implementation, where time-dependent values appear as normal parameter values which magically change when `'t'` changes, is surprising and error prone.
After thinking some more about it and also about how inputs would fit into the picture, I came to the conclusion that it might make more sense to keep the feature but improve the implementation by a clearer concept. What I propose with this PR is the following:
- A `Mu` is essentially a pair of a dict of constant values and a dict of time-dependent values. The former is accessible via the usual dict protocol methods. The latter …
> New approach to time-dependent parameter values

- src/pymor/discretizers/skfem/cg.py
- src/pymortests/bindings/skfem.py
> scikit-fem: Fix boundary handling for 1.13 <= scipy < 1.15

- src/pymor/core/config.py
This issue occurred when trying to use pyMOR in jupyterlite, which does not allow to use processes.
> Execute `_get_threadpool_internal_api` in try-except-block

- src/pymor/algorithms/chol_qr.py
`scipy.linalg.cholesky` is called with `overwrite_a` in `shifted_chol_qr`. In the case of a breakdown in the Cholesky algorithm, this leaves `X` in an undefined stated. This has caused CI build failures in #2405 and also seems to be responsible for #2406. Actually, I'm quite surprised, that this usually worked before. (With the latest changes in #2405, `X` becomes Fortran ordered, which seems to select a different LAPACK code path. So maybe the code for C ordering made a copy even with `overwrite_a`. I haven't tested that.)
Fixes #2406.
> Avoid data corruption in shifted_chol_qr

- src/pymor/core/cache.py
This upcasts all numpy arrays used in Mus to the largest appropriate dtype before hashing. Among other things, this ensures that `12` and `12.` have the same hash. It also ensures that the keys passed on to cache backends are portable across OSes.
> upcast numpy arrays for portable caching

- docs/source/conf.py
- src/pymor/core/cache.py
- src/pymor/core/defaults.py
The type annotations should help type checkers / language servers to correctly understand the signatures of methods that have been decorated with `@defaults` or `@cached`.
In particular, `jedi-language-server` correctly completes the signature of `gram_schmidt` with this PR.
> Add type annotations for @defaults and @cached
